### ISSUE TITLE
[1.11.2]

### ISSUE THREAD

**Issue by ternsip** [Glitchfiend/BiomesOPlenty#1009]
Trying to generate nether while there is no players
`java.lang.NoSuchFieldError: logCascadingWorldGeneration
	at biomesoplenty.common.world.ChunkProviderGenerateBOPHell.populate(ChunkProviderGenerateBOPHell.java:464) ~[ChunkProviderGenerateBOPHell.class:?]
	at net.minecraft.world.chunk.Chunk.populateChunk(Chunk.java:1069) ~[Chunk.class:?]
	at net.minecraft.world.chunk.Chunk.populateChunk(Chunk.java:1052) ~[Chunk.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.provideChunk(ChunkProviderServer.java:164) ~[ChunkProviderServer.class:?]
	at net.minecraft.world.World.getChunkFromChunkCoords(World.java:351) ~[World.class:?]
	at net.minecraft.world.World.getChunkFromBlockCoords(World.java:343) ~[World.class:?]`

**Comment by Adubbz** [comment]
Update Forge
