### ISSUE TITLE
Game crash- BiomesOPlenty and AbyssaCraft .. newest version issue

### ISSUE THREAD

**Issue by Temil2006** [Glitchfiend/BiomesOPlenty#1040]
#### Issue Description:
if you try and run AbyssalCraft and BiomesOPlenty, causes the game to crash during game loading process. This wasn't an issue in versions BiomesOPlenty-1.11.2-6.1.0.2238, only presented its self in versions BiomesOPlenty-1.11.2-6.1.0.2239 and BiomesOPlenty-1.11.2-6.1.0.2240.

tried loading game with only these 2 mods, still fails.
failing on both single player and server.

I thought it might be considered an AbyssalCraft bug, but seeing as the version of BiomesOPlenty changed, and AbyssalCraft didn't, points to changes in BiomesOPlenty that is causing the issue.

#### Steps to reproduce:

1. load AbyssalCraft-1.11.2-1.9.4-pre-3  and BiomesOPlenty-1.11.2-6.1.0.2239
2. game crashes on loading mods, prior to start of the game.

#### Additional Information:

- fml-client-latest.log or fml-server-latest.log:
Time: 6/6/17 11:27 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from AbyssalCraft (abyssalcraft)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 32767
	at biomesoplenty.common.block.BlockBOPWhiteSandstone.func_176203_a(BlockBOPWhiteSandstone.java:107)
	at com.shinoow.abyssalcraft.common.blocks.BlockCLiquid.oresToBlocks(BlockCLiquid.java:144)
	at com.shinoow.abyssalcraft.common.blocks.BlockCLiquid.addBlocks(BlockCLiquid.java:189)
	at com.shinoow.abyssalcraft.init.BlockHandler.postInit(BlockHandler.java:494)
	at com.shinoow.abyssalcraft.AbyssalCraft.lambda$postInit$2(AbyssalCraft.java:70)
	at java.util.ArrayList.forEach(Unknown Source)
	at com.shinoow.abyssalcraft.AbyssalCraft.postInit(AbyssalCraft.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:641)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:252)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:230)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:147)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:833)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:357)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:521)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:352)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

____
#### Affected Versions (Exact numbers, do *not* use "latest"):

- Biomes O' Plenty: BiomesOPlenty-1.11.2-6.1.0.2239 OR BiomesOPlenty-1.11.2-6.1.0.2240.
- Minecraft: 1.11.2
- Forge: forge1.11.2-13.20.0.2312

**Comment by Forstride** [comment]
I pushed a possible fix for this.  New build should be up on CurseForge, so lemme know if that fixes it.

**Comment by Temil2006** [comment]
update of 	
BiomesOPlenty-1.11.2-6.1.0.2243-universal.jar confirmed to fix this issue. thank you.
