### ISSUE TITLE
Crashing when trying to join friend's server with Biomes O' Plenty biome generation

### ISSUE THREAD

**Issue by Skye97** [Glitchfiend/BiomesOPlenty#1042]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  DynamicSurroundingsCore (DynamicSurroundings-1.11.2-3.4.5.0.jar)
  ItemPatchingLoader (ItemPhysic Lite 1.3.6 mc1.11.2.jar)
  llibrary (llibrary-1.7.6-1.11.2.jar)
  CreativePatchingLoader (CreativeCore v1.7.2 mc1.11.2.jar)
  LoadingPlugin (ChunkAnimator-MC1.11-1.2.jar)
  SignPictureCorePlugin (SignPicture-1.11.2-2.7.1-universal.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.6.3-anarchy.jar)
  LoadingPlugin (NoNausea-MC1.11-1.0.jar)
  BetterFoliageLoader (BetterFoliage-MC1.11.2-2.1.5.jar)
  IC2core (industrialcraft-2-2.7.33-ex111.jar)
  MalisisCorePlugin (malisiscore-1.11.2-5.1.1.jar)
Contact their authors BEFORE contacting forge

// Don't be sad, have a hug! <3

Time: 6/8/17 12:23 AM
Description: Getting biome

java.lang.IllegalArgumentException: Couldn't find a biome with an ID of 109
	at buildcraft.energy.generation.GenLayerAddOilOcean.canReplaceBiome(GenLayerAddOilOcean.java:34)
	at buildcraft.energy.generation.GenLayerBiomeReplacer.func_75904_a(GenLayerBiomeReplacer.java:66)
	at buildcraft.energy.generation.GenLayerBiomeReplacer.func_75904_a(GenLayerBiomeReplacer.java:60)
	at net.minecraft.world.biome.BiomeProvider.func_76931_a(BiomeProvider.java:127)
	at net.minecraft.world.biome.BiomeCache$Block.<init>(SourceFile:27)
	at net.minecraft.world.biome.BiomeCache.func_76840_a(SourceFile:48)
	at net.minecraft.world.biome.BiomeCache.func_180284_a(SourceFile:57)
	at net.minecraft.world.biome.BiomeProvider.func_180300_a(BiomeProvider.java:64)
	at net.minecraft.world.chunk.Chunk.func_177411_a(Chunk.java:1199)
	at net.minecraft.world.World.getBiomeForCoordsBody(World.java:153)
	at net.minecraft.world.WorldProvider.getBiomeForCoords(WorldProvider.java:389)
	at net.minecraft.world.World.func_180494_b(World.java:142)
	at de.teamlapen.vampirism.util.Helper.isEntityInVampireBiome(Helper.java:141)
	at de.teamlapen.vampirism.client.render.RenderHandler.onClientTick(RenderHandler.java:124)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_683_RenderHandler_onClientTick_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:339)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1645)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1056)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at buildcraft.energy.generation.GenLayerAddOilOcean.canReplaceBiome(GenLayerAddOilOcean.java:34)
	at buildcraft.energy.generation.GenLayerBiomeReplacer.func_75904_a(GenLayerBiomeReplacer.java:66)
	at buildcraft.energy.generation.GenLayerBiomeReplacer.func_75904_a(GenLayerBiomeReplacer.java:60)
	at net.minecraft.world.biome.BiomeProvider.func_76931_a(BiomeProvider.java:127)
	at net.minecraft.world.biome.BiomeCache$Block.<init>(SourceFile:27)
	at net.minecraft.world.biome.BiomeCache.func_76840_a(SourceFile:48)
	at net.minecraft.world.biome.BiomeCache.func_180284_a(SourceFile:57)
	at net.minecraft.world.biome.BiomeProvider.func_180300_a(BiomeProvider.java:64)
	at net.minecraft.world.chunk.Chunk.func_177411_a(Chunk.java:1199)

-- Coordinates of biome request --
Details:
	Location: World: (9,65,9), Chunk: (at 9,4,9 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
Stacktrace:
	at net.minecraft.world.World.getBiomeForCoordsBody(World.java:153)
	at net.minecraft.world.WorldProvider.getBiomeForCoords(WorldProvider.java:389)
	at net.minecraft.world.World.func_180494_b(World.java:142)
	at de.teamlapen.vampirism.util.Helper.isEntityInVampireBiome(Helper.java:141)
	at de.teamlapen.vampirism.client.render.RenderHandler.onClientTick(RenderHandler.java:124)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_683_RenderHandler_onClientTick_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:339)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Skye97'/13, l='MpServer', x=8.50, y=65.00, z=8.50]]
	Chunk stats: MultiplayerChunkCache: 0, 0
	Level seed: 0
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 0 total; []
	Retry entities: 0 total; []
	Server brand: fml,forge,sponge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:524)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2655)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:393)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1371972864 bytes (1308 MB) / 3079323648 bytes (2936 MB) up to 5355339776 bytes (5107 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx5G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 6, tallocated: 104
	FML: MCP 9.38 Powered by Forge 13.20.0.2312 Optifine OptiFine_1.11.2_HD_U_B9 77 mods loaded, 77 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2312.jar) 
	UCHIJA	forge{13.20.0.2312} [Minecraft Forge] (forge-1.11.2-13.20.0.2312.jar) 
	UCHIJA	creativecoredummy{1.0.0} [CreativeCoreDummy] (minecraft.jar) 
	UCHIJA	itemphysic{1.4.0} [ItemPhysic] (minecraft.jar) 
	UCHIJA	foamfixcore{7.7.4} [FoamFixCore] (minecraft.jar) 
	UCHIJA	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.11.2.jar) 
	UCHIJA	aether_legacy{v1.4.1} [Aether Legacy] (aether_legacy-1.11.2-1.0.jar) 
	UCHIJA	animalium{0.2.0} [animalium] (Animalium-0.2.0.jar) 
	UCHIJA	animania{1.1.2} [Animania] (animania-1.11.2-1.1.2.jar) 
	UCHIJA	csb_armorstand{1.0.2} [Armor Stand Configurator] (ArmorStandGUI-1.11-1.0.2.jar) 
	UCHIJA	autorefresh{1.1.0} [Auto Refresh] (AutoRefresh-1.11.2-1.1.0.jar) 
	UCHIJA	betterfoliage{2.1.5} [Better Foliage] (BetterFoliage-MC1.11.2-2.1.5.jar) 
	UCHIJA	biomesoplenty{6.0.2.2168} [Biomes O' Plenty] (BiomesOPlenty-1.11.2-6.0.2.2168-universal.jar) 
	UCHIJA	buildcraftlib{7.99.4} [BuildCraft Lib] (buildcraft-7.99.4.jar) 
	UCHIJA	buildcraftcore{7.99.4} [BuildCraft] (buildcraft-7.99.4.jar) 
	UCHIJA	buildcraftfactory{7.99.4} [BC Factory] (buildcraft-7.99.4.jar) 
	UCHIJA	buildcrafttransport{7.99.4} [BC Transport] (buildcraft-7.99.4.jar) 
	UCHIJA	buildcraftbuilders{7.99.4} [BC Builders] (buildcraft-7.99.4.jar) 
	UCHIJA	buildcraftenergy{7.99.4} [BC Energy] (buildcraft-7.99.4.jar) 
	UCHIJA	buildcraftrobotics{7.99.4} [BC Robotics] (buildcraft-7.99.4.jar) 
	UCHIJA	buildcraftsilicon{7.99.4} [BC Silicon] (buildcraft-7.99.4.jar) 
	UCHIJA	calculations{1.0.0} [Calculations] (Calculations-1.11.2-1.0.0.jar) 
	UCHIJA	cfm{4.1.2} [MrCrayfish's Furniture Mod] (cfm-4.1.2-mc1.11.2.jar) 
	UCHIJA	chiselsandbits{13.10} [Chisels & Bits] (chiselsandbits-13.10.jar) 
	UCHIJA	chunkanimator{1.2} [Chunk Animator] (ChunkAnimator-MC1.11-1.2.jar) 
	UCHIJA	cleanchat{1.0.0} [Clean Chat] (cleanchat-mc1.11.2_1.0.0.jar) 
	UCHIJA	cleanview{1.10.2-v1} [CleanView] (CleanView-1.10.2-v1.jar) 
	UCHIJA	creativeplus{1.0.1} [Creative+] (Creative Plus MC1.11.2 v1.0.1.jar) 
	UCHIJA	creativecore{1.5.0} [CreativeCore] (CreativeCore v1.7.2 mc1.11.2.jar) 
	UCHIJA	customnpcs{1.11.2} [CustomNPCs] (CustomNPCs_1.11.2(25may17).jar) 
	UCHIJA	cyberware{alpha-0.2.9} [Cyberware] (cyberware-1.11.2-alpha-0.2.9.jar) 
	UCHIJA	ptrmodellib{1.0.0} [ptrmodellib] (Decocraft-2.4.2_1.11.2.jar) 
	UCHIJA	props{2.4.2} [Decocraft] (Decocraft-2.4.2_1.11.2.jar) 
	UCHIJA	dsurround{3.4.5.0} [§3Dynamic Surroundings] (DynamicSurroundings-1.11.2-3.4.5.0.jar) 
	UCHIJA	presets{3.4.5.0} [§3Presets!] (DynamicSurroundings-1.11.2-3.4.5.0.jar) 
	UCHIJA	enhancedvisuals{1.0} [Enhanced Visuals] (EnhancedVisuals v1.1.2 mc1.11.2.jar) 
	UCHIJA	fbp{2.2} [Fancy Block Particles] (FancyBlockParticles-1.11.2-2.2.jar) 
	UCHIJA	foamfix{@VERSION@} [FoamFix] (foamfix-0.6.3-anarchy.jar) 
	UCHIJA	freecam{1.0} [FreeCam] (freecam.jar) 
	UCHIJA	howlingmoon{0.6.1} [Howling Moon Rising] (howlingmoon-1.11.2-0.6.1.jar) 
	UCHIJA	ic2{2.7.33-ex111} [IndustrialCraft 2] (industrialcraft-2-2.7.33-ex111.jar) 
	UCHIJA	inventory_x{1.11-1.0.2} [Inventory X] (inventory_x-1.11-1.0.2.jar) 
	UCHIJA	inventorypets{1.4.9.5} [Inventory Pets] (inventorypets-1.11.2-1.4.9.5.jar) 
	UCHIJA	jei{4.3.5.277} [Just Enough Items] (jei_1.11.2-4.3.5.277.jar) 
	UCHIJA	journeymap{1.11.2-5.4.6} [JourneyMap] (journeymap-1.11.2-5.4.6.jar) 
	UCHIJA	llibrary{1.7.6} [LLibrary] (llibrary-1.7.6-1.11.2.jar) 
	UCHIJA	jurassicraft{2.0.5} [JurassiCraft] (JurassiCraft-2.0.5.jar) 
	UCHIJA	jaff{1.6_for_1.11.2} [Just a Few Fish] (JustAFewFish-1.6_for_1.11.2.jar) 
	UCHIJA	justenoughbuttons{1.11.2-1.4.5} [Just Enough Buttons] (justenoughbuttons-1.11.2-1.4.5.jar) 
	UCHIJA	malisiscore{1.11.2-5.1.1} [MalisisCore] (malisiscore-1.11.2-5.1.1.jar) 
	UCHIJA	malisisdoors{1.11.2-6.1.0} [MalisisDoors] (malisisdoors-1.11.2-6.1.0.jar) 
	UCHIJA	mantle{1.11.2-1.2.0.26} [Mantle] (Mantle-1.11.2-1.2.0.26.jar) 
	UCHIJA	missing_pieces{4.2.1} [Missing Pieces] (missing_pieces-1.11.2-4.2.1.jar) 
	UCHIJA	moreplayermodels{1.11.0} [MorePlayerModels] (MorePlayerModels_1.11.2(26jan17).jar) 
	UCHIJA	mw{1.10} [Modern Warfare] (mw-1.10_mc1.11.2.jar) 
	UCHIJA	mxtune{0.4.0-dev.24} [mxTune] (mxtune-1.11.2-0.4.0-dev.24.jar) 
	UCHIJA	nonausea{1.0} [NoNausea] (NoNausea-MC1.11-1.0.jar) 
	UCHIJA	notes{1.1.0} [Notes] (Notes-1.11.2-1.1.0.jar) 
	UCHIJA	harvestcraft{1.11.2g} [Pam's HarvestCraft] (Pam's HarvestCraft 1.11.2h.jar) 
	UCHIJA	personalcars{1.2} [Personal Cars] (PersonalCars-1.2.jar) 
	UCHIJA	guilib{1.11 : updated by subaraki} [GUI Library] (PSG Revamper-1.11-1.0.0.0.jar) 
	UCHIJA	paintingselgui{1.11 v1: updated by Subaraki} [PaintingSelectionGui] (PSG Revamper-1.11-1.0.0.0.jar) 
	UCHIJA	qualityorder{0.11} [Quality Order] (QualityOrder(0.11)-1.11.2.jar) 
	UCHIJA	rfpr{8.1.1} [Real First-Person Render] (Real First-Person Render-1.11.2-8.1.1.jar) 
	UCHIJA	signpic{2.7.1} [SignPicture] (SignPicture-1.11.2-2.7.1-universal.jar) 
	UCHIJA	skyesdonuts{1.2.0} [Skye's Donuts] (Skye's Donuts 1.2.0 for MC 1.11.2.jar) 
	UCHIJA	soundfilters{0.9_for_1.9} [Sound Filters] (SoundFilters-0.9_for_1.11.jar) 
	UCHIJA	stellarapi{0.6.4.1.3} [Stellar API] (Stellar API-0.6.4.1.3.jar) 
	UCHIJA	tconstruct{1.11.2-2.7.0.26} [Tinkers' Construct] (TConstruct-1.11.2-2.7.0.26.jar) 
	UCHIJA	thutcore{4.4.1} [ThutCore] (thutcore-4.4.1.jar) 
	UCHIJA	thuttech{5.0.0} [Thut's Tech] (thuttech-5.0.0.c.jar) 
	UCHIJA	vampirism{1.2.0-alpha+05-26-13-10} [Vampirism] (Vampirism-1.11.2-1.2.0-alpha+05-26-13-10.jar) 
	UCHIJA	teamlapen-lib{1.2.0-alpha+05-26-13-10} [TeamLapen Library] (Vampirism-1.11.2-1.2.0-alpha+05-26-13-10.jar) 
	UCHIJA	wit{1.0.22} [WIT] (WIT-1.11-1.0.22-41.jar) 
	UCHIJA	worldedit{6.1.6} [WorldEdit] (worldedit-forge-mc1.11-6.1.6-dist.jar) 
	Loaded coremods (and transformers): 
DynamicSurroundingsCore (DynamicSurroundings-1.11.2-3.4.5.0.jar)
  org.blockartistry.DynSurround.asm.Transformer
ItemPatchingLoader (ItemPhysic Lite 1.3.6 mc1.11.2.jar)
  com.creativemd.itemphysic.ItemTransformer
llibrary (llibrary-1.7.6-1.11.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
CreativePatchingLoader (CreativeCore v1.7.2 mc1.11.2.jar)
  
LoadingPlugin (ChunkAnimator-MC1.11-1.2.jar)
  lumien.chunkanimator.asm.ClassTransformer
SignPictureCorePlugin (SignPicture-1.11.2-2.7.1-universal.jar)
  com.kamesuta.mc.signpic.asm.SignPictureTransformer
Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.6.3-anarchy.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
LoadingPlugin (NoNausea-MC1.11-1.0.jar)
  lumien.nonausea.asm.ClassTransformer
BetterFoliageLoader (BetterFoliage-MC1.11.2-2.1.5.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
IC2core (industrialcraft-2-2.7.33-ex111.jar)
  
MalisisCorePlugin (malisiscore-1.11.2-5.1.1.jar)
  net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
  net.malisis.core.util.chunkblock.ChunkBlockTransformer
  net.malisis.core.renderer.transformer.MalisisRendererTransformer
  net.malisis.core.renderer.icon.asm.TextureMapTransformer
  net.malisis.core.util.clientnotif.ClientNotifTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 382.33' Renderer: 'GeForce GTX 1070/PCIe/SSE2'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)

	Launched Version: 1.11.2
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1070/PCIe/SSE2 GL version 4.5.0 NVIDIA 382.33, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Vaders Stacked Items Pack.zip, ItemBound v1.4.4 MC1.11.zip, Clouds-Pack (Modified) - updated.zip (incompatible), Sn0wZ0ne2.0.5-64x_All_versions.zip (incompatible)
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz
	OptiFine Version: OptiFine_1.11.2_HD_U_B9
	Render Distance Chunks: 10
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: CYBOXshaders V4 CINEMATIC Plain.zip
	OpenGlVersion: 4.5.0 NVIDIA 382.33
	OpenGlRenderer: GeForce GTX 1070/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

**Comment by Adubbz** [comment]
Delete your biome id config.

**Comment by Skye97** [comment]
Yeah I just found it out myself moment ago. I deleted config folder and it works again. Thanks anyway. :)
