### ISSUE TITLE
Rare new world crash with buildcraft and BOP versions 2240 to 2247. Certain seeds...

### ISSUE THREAD

**Issue by batlham** [Glitchfiend/BiomesOPlenty#1046]
#### Issue Description:
All versions AFTER BiomesOPlenty-1.11.2-6.1.0.2239 cause a lockup crash with buildcraft 7.99.4.
This happens during the creataion of a new world. However, it only happens with certain seeds.
The seed kas is one to make the crash.
I have been testing this out for two days now.

#### Steps to reproduce:

1.  I was using seed "kas" Using newest forge. 1.11.2-forge1.11.2-13.20.0.2315
 However, random seed 8884646567541711186 works with all versions.
I had a few random seeds not work. But I did not write them down.
I also tried my older versions of forge in case.
I tried it with Every version of BiomesOPlenty from 2238 to 2247. 2240 on up cause lockup.
I deleted configs before each test.

2.  Tried changing BiomesOPlenty  biomes numbers from 40 and 41 to 110 and 111 (Buildcraft defaults for oil biomes) to see if that was the problem. Without changing them the buildcraft oil biomes are moved to 110 and 111.

#### Additional Information:

---- Minecraft Crash Report ----
// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 6/10/17 8:40 PM
Description: Exception preparing structure feature

java.lang.IllegalArgumentException: Couldn't find a biome with an ID of -1
	at buildcraft.energy.generation.GenLayerAddOilOcean.canReplaceBiome(GenLayerAddOilOcean.java:34)
	at buildcraft.energy.generation.GenLayerBiomeReplacer.func_75904_a(GenLayerBiomeReplacer.java:66)
	at buildcraft.energy.generation.GenLayerBiomeReplacer.func_75904_a(GenLayerBiomeReplacer.java:60)
	at net.minecraft.world.biome.BiomeProvider.func_180630_a(BiomeProvider.java:186)
	at net.minecraft.world.gen.structure.MapGenStronghold.func_189104_c(MapGenStronghold.java:154)
	at net.minecraft.world.gen.structure.MapGenStronghold.func_75047_a(MapGenStronghold.java:109)
	at net.minecraft.world.gen.structure.MapGenStructure.func_180701_a(MapGenStructure.java:38)
	at net.minecraft.world.gen.MapGenBase.func_186125_a(SourceFile:34)
	at biomesoplenty.common.world.ChunkProviderGenerateBOP.func_185932_a(ChunkProviderGenerateBOP.java:179)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:144)
	at net.minecraft.world.World.func_72964_e(World.java:303)
	at net.minecraft.world.World.func_175726_f(World.java:298)
	at net.minecraft.world.World.func_180495_p(World.java:903)
	at net.minecraft.world.World.func_175623_d(World.java:223)
	at net.minecraft.world.World.func_184141_c(World.java:203)
	at net.minecraft.world.WorldProvider.func_76566_a(WorldProvider.java:69)
	at net.minecraft.world.WorldServer.func_73052_b(WorldServer.java:952)
	at net.minecraft.world.WorldServer.func_72963_a(WorldServer.java:874)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:87)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:120)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:442)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at buildcraft.energy.generation.GenLayerAddOilOcean.canReplaceBiome(GenLayerAddOilOcean.java:34)
	at buildcraft.energy.generation.GenLayerBiomeReplacer.func_75904_a(GenLayerBiomeReplacer.java:66)
	at buildcraft.energy.generation.GenLayerBiomeReplacer.func_75904_a(GenLayerBiomeReplacer.java:60)
	at net.minecraft.world.biome.BiomeProvider.func_180630_a(BiomeProvider.java:186)
	at net.minecraft.world.gen.structure.MapGenStronghold.func_189104_c(MapGenStronghold.java:154)
	at net.minecraft.world.gen.structure.MapGenStronghold.func_75047_a(MapGenStronghold.java:109)

-- Feature being prepared --
Details:
	Is feature chunk: False
	Chunk location: 7,6
	Chunk pos hash: 25769803783
	Structure type: net.minecraft.world.gen.structure.MapGenStronghold
Stacktrace:
	at net.minecraft.world.gen.structure.MapGenStructure.func_180701_a(MapGenStructure.java:38)
	at net.minecraft.world.gen.MapGenBase.func_186125_a(SourceFile:34)
	at biomesoplenty.common.world.ChunkProviderGenerateBOP.func_185932_a(ChunkProviderGenerateBOP.java:179)

-- Chunk to be generated --
Details:
	Location: 15,14
	Position hash: 60129542159
	Generator: biomesoplenty.common.world.ChunkProviderGenerateBOP@360bfe18
Stacktrace:
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:144)
	at net.minecraft.world.World.func_72964_e(World.java:303)
	at net.minecraft.world.World.func_175726_f(World.java:298)
	at net.minecraft.world.World.func_180495_p(World.java:903)
	at net.minecraft.world.World.func_175623_d(World.java:223)
	at net.minecraft.world.World.func_184141_c(World.java:203)
	at net.minecraft.world.WorldProvider.func_76566_a(WorldProvider.java:69)
	at net.minecraft.world.WorldServer.func_73052_b(WorldServer.java:952)

-- Affected level --
Details:
	Level name: Copy of kas2
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 0 Drop: 0
	Level seed: 105949
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.world.WorldServer.func_72963_a(WorldServer.java:874)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:87)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:120)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:442)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 226465744 bytes (215 MB) / 614617088 bytes (586 MB) up to 3656646656 bytes (3487 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3500M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 1, tcache: 0, allocated: 21, tallocated: 87
	FML: MCP 9.38 Powered by Forge 13.20.0.2315 13 mods loaded, 13 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAA	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCHIJAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2315.jar) 
	UCHIJAA	forge{13.20.0.2315} [Minecraft Forge] (forge-1.11.2-13.20.0.2315.jar) 
	UCHIJAA	biomesoplenty{6.1.0.2240} [Biomes O' Plenty] (BiomesOPlenty-1.11.2-6.1.0.2240-universal.jar) 
	UCHIJAA	buildcraftlib{7.99.4} [BuildCraft Lib] (buildcraft-7.99.4.jar) 
	UCHIJAA	buildcraftcore{7.99.4} [BuildCraft] (buildcraft-7.99.4.jar) 
	UCHIJAA	buildcraftfactory{7.99.4} [BC Factory] (buildcraft-7.99.4.jar) 
	UCHIJAA	buildcrafttransport{7.99.4} [BC Transport] (buildcraft-7.99.4.jar) 
	UCHIJAA	buildcraftbuilders{7.99.4} [BC Builders] (buildcraft-7.99.4.jar) 
	UCHIJAA	buildcraftenergy{7.99.4} [BC Energy] (buildcraft-7.99.4.jar) 
	UCHIJAA	buildcraftrobotics{7.99.4} [BC Robotics] (buildcraft-7.99.4.jar) 
	UCHIJAA	buildcraftsilicon{7.99.4} [BC Silicon] (buildcraft-7.99.4.jar) 
	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

____
#### Affected Versions (Exact numbers, do *not* use "latest"):

- Biomes O' Plenty:  2240 to 2247
- Minecraft:  1.11.2
- Forge:  1.11.2-forge1.11.2-13.20.0.2304     to    1.11.2-forge1.11.2-13.20.0.2315

**Comment by Adubbz** [comment]
Huh.. Interesting. Thanks for this, someone else reported it but was fairly non-specific about the versions and had a TON of other mods installed. I tried to reproduce it myself without any luck, but if you say it's only certain seeds that would make a lot more sense. The next version of Buildcraft includes a workaround for this thankfully, but this does provide me something to work with at least.

Just to double check, you don't have any biomes disabled, just some IDs changed?

**Comment by srs-bsns** [comment]
This has already been fixed in Buildcraft, but the fix hasn't been released yet. See: https://github.com/BuildCraft/BuildCraft/commit/ec81474b32a52226f4836967230d637cd950bd03

**Comment by batlham** [comment]
None disabled. Just moved biome ids. However, tested without moving ids as well.
Ok fix in BC I hope. Just wonder why conflict with bop started at 2240 with same version of bc

**Comment by Adubbz** [comment]
Can reproduce this, and can also confirm it appears to somehow be related to structures...

**Comment by Adubbz** [comment]
Fixed it. Reports like this are exactly what's needed to track down these sorts of issues, thanks again.

**Comment by batlham** [comment]
No problem. I learned solving mod conflicts back in the days of everything having IDs and conflict ALL the time. Glad to help.
Just loaded 2254 and works so far :)
My friend Kas is going to laugh that her name broke a mod :D
