### ISSUE TITLE
[1.12]Crash at Startup

### ISSUE THREAD

**Issue by BlackHorizon63** [Glitchfiend/BiomesOPlenty#1060]
Hello, i get a crash during Minecraft is starting.
BoP Version: BiomesOPlenty-1.12-7.0.0.2282-universal.jar
Forge Version: forge-1.12-14.21.0.2373.jar

---- Minecraft Crash Report ----
// But it works on my machine.

Time: 6/26/17 4:46 PM
Description: Initializing game

java.lang.NoSuchMethodError: net.minecraftforge.client.model.ModelLoader.defaultTextureGetter()Lcom/google/common/base/Function;
	at biomesoplenty.common.handler.LeavesModelEventHandler.onModelBake(LeavesModelEventHandler.java:44)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_30_LeavesModelEventHandler_onModelBake_ModelBakeEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:186)
	at net.minecraftforge.client.ForgeHooksClient.onModelBake(ForgeHooksClient.java:367)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:30)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:512)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at biomesoplenty.common.handler.LeavesModelEventHandler.onModelBake(LeavesModelEventHandler.java:44)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_30_LeavesModelEventHandler_onModelBake_ModelBakeEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:186)
	at net.minecraftforge.client.ForgeHooksClient.onModelBake(ForgeHooksClient.java:367)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:30)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:512)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 277262288 bytes (264 MB) / 759627776 bytes (724 MB) up to 8536260608 bytes (8140 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn512M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.40 Powered by Forge 14.21.0.2373 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	**UCH	minecraft{1.12} [Minecraft] (minecraft.jar) 
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.12-14.21.0.2373.jar) 
	UCH	forge{14.21.0.2373} [Minecraft Forge] (forge-1.12-14.21.0.2373.jar) 
	UCH	biomesoplenty{7.0.0.2282} [Biomes O' Plenty] (BiomesOPlenty-1.12-7.0.0.2282-universal.jar)** 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 382.33' Renderer: 'GeForce GTX 960/PCIe/SSE2'
	Launched Version: 1.12.0
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 960/PCIe/SSE2 GL version 4.5.0 NVIDIA 382.33, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x AMD FX(tm)-8150 Eight-Core Processor

**Comment by NoahJelen** [comment]
I got almost the same thing as you, BlackHorizon.

---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// You're mean.

Time: 6/26/17 4:17 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Biomes O' Plenty (biomesoplenty)
Caused by: java.lang.NoClassDefFoundError: net/minecraftforge/fml/common/registry/RegistryDelegate
	at net.minecraft.client.renderer.block.model.ModelBakery.registerItemVariants(ModelBakery.java:1081)
	at biomesoplenty.core.ClientProxy.registerItemVariantModel(ClientProxy.java:121)
	at biomesoplenty.common.init.ModBlocks.registerBlockItemModel(ModBlocks.java:339)
	at biomesoplenty.common.init.ModBlocks.registerBlock(ModBlocks.java:393)
	at biomesoplenty.common.init.ModBlocks.registerBlock(ModBlocks.java:352)
	at biomesoplenty.common.init.ModBlocks.registerBlock(ModBlocks.java:347)
	at biomesoplenty.common.init.ModBlocks.init(ModBlocks.java:104)
	at biomesoplenty.core.BiomesOPlenty.preInit(BiomesOPlenty.java:82)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:647)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:252)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:230)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:147)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:615)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:267)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.fml.common.registry.RegistryDelegate
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 48 more
Caused by: java.lang.SecurityException: class "net.minecraftforge.fml.common.registry.RegistryDelegate"'s signer information does not match signer information of other classes in the same package
	at java.lang.ClassLoader.checkCerts(ClassLoader.java:895)
	at java.lang.ClassLoader.preDefineClass(ClassLoader.java:665)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:758)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 50 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 153452960 bytes (146 MB) / 341413888 bytes (325 MB) up to 2134114304 bytes (2035 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.40 Powered by Forge 14.21.0.2373 Optifine OptiFine_1.12_HD_U_C3_pre 12 mods loaded, 12 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	minecraft{1.12} [Minecraft] (minecraft.jar) 
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.12-14.21.0.2373.jar) 
	UCH	forge{14.21.0.2373} [Minecraft Forge] (forge-1.12-14.21.0.2373.jar) 
	UCE	biomesoplenty{7.0.0.2282} [Biomes O' Plenty] (BiomesOPlenty-1.12-7.0.0.2282-universal.jar) 
	UCH	chameleoncreepers{1.4.1} [Chameleon Creepers] (chameleoncreepers-1.4.1-1.12.jar) 
	UCH	xray{1.2.0} [XRay] (fgtxray-1.12-1.2.0.jar) 
	UCH	torohealthmod{1.12-11} [ToroHealth Damage Indicators] (torohealth-1.12-11.jar) 
	UCH	veinminer{0.36.0} [Vein Miner] (VeinMiner-1.11-0.36.0.621+8499b73.jar) 
	UCH	veinminermodsupport{0.36.0} [Mod Support] (VeinMiner-1.11-0.36.0.621+8499b73.jar) 
	UCH	worldhandler{4.7} [World Handler Gui] (WorldHandler-1.12-4.7-Universal.jar) 
	UCH	xaerominimap{1.13.1} [Xaero's Minimap] (Xaeros_Minimap_1.13.1_Forge_1.12.jar) 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'Intel' Version: '4.0.0 - Build 10.18.10.4358' Renderer: 'Intel(R) HD Graphics'
	OptiFine Version: OptiFine_1.12_HD_U_C3_pre
	Render Distance Chunks: 4
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.0.0 - Build 10.18.10.4358
	OpenGlRenderer: Intel(R) HD Graphics
	OpenGlVendor: Intel
	CpuCount: 4

**Comment by acid1103** [comment]
I'm getting the same crash. The crash no longer happens when I remove optifine, so it's likely a compatibility issue. I've tried with OptiFine 1.12 HD U C2 and OptiFine 1.12 HD U C3, and both result in the same crash.

**Comment by JasonKillsUs** [comment]
well optifine is a different issue, here "due to forge changes" 1.12 Forge 2377 crash on startup:

"https://pastebin.com/v4h3sw7m"
thanks

**Comment by Adubbz** [comment]
This would be an issue with Optifine. I've just tested the mod on Forge 2379 after making a minor update and it works fine. We don't support Optifine because it causes stuff like this to happen.
