### ISSUE TITLE
Crash on latest Forge

### ISSUE THREAD

**Issue by Imnuts7** [Glitchfiend/BiomesOPlenty#1071]
#### Issue Description:

Minecraft crashes on the loading screen.

#### Steps to reproduce:

1. Try to load the game.

#### Additional Information:

- fml-client-latest.log or fml-server-latest.log: https://gist.github.com/Imnuts7/5450208d83c211487eb711f5701329a3

Crash report: 
https://gist.github.com/Imnuts7/9bab264e015489bca145cf177519f55a
____
#### Affected Versions (Exact numbers, do *NOT* use "latest"):

- Biomes O' Plenty: 7.0.0.2289
- Minecraft: 1.12
- Forge: 14.21.1.2407

**Comment by svenhjol** [comment]
I found the same issue, and on removing Chisel it started working properly.

**Comment by Imnuts7** [comment]
Now fixed since Chisel updated.

**Comment by winsrp** [comment]
I still get the same error with both updated mods

crash when launching MC, not even got to home screen.

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
LoadingPlugin (Quark-r1.2-101.jar)
MovingWorldCoreMod (movingworld-1.12-4.340-full.jar)
MalisisCorePlugin (malisiscore-1.12-6.0.1.jar)
IvToolkit (IvToolkit-1.3.3-1.12.jar)
Contact their authors BEFORE contacting forge

// Don't do that.

Time: 7/18/17 2:48 PM
Description: Initializing game

java.lang.NullPointerException: Initializing game
at biomesoplenty.common.handler.LeavesModelEventHandler$ModelLeaves.(LeavesModelEventHandler.java:55)
at biomesoplenty.common.handler.LeavesModelEventHandler.onModelBake(LeavesModelEventHandler.java:46)
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_226_LeavesModelEventHandler_onModelBake_ModelBakeEvent.invoke(.dynamic)
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
at net.minecraftforge.client.ForgeHooksClient.onModelBake(ForgeHooksClient.java:367)
at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:30)
at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121)
at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:512)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
at net.minecraft.client.main.Main.main(SourceFile:123)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Thread: Client thread
Stacktrace:
at biomesoplenty.common.handler.LeavesModelEventHandler$ModelLeaves.(LeavesModelEventHandler.java:55)
at biomesoplenty.common.handler.LeavesModelEventHandler.onModelBake(LeavesModelEventHandler.java:46)
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_226_LeavesModelEventHandler_onModelBake_ModelBakeEvent.invoke(.dynamic)
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
at net.minecraftforge.client.ForgeHooksClient.onModelBake(ForgeHooksClient.java:367)
at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:30)
at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121)
at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:512)

-- Initialization --
Details:
Stacktrace:
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
at net.minecraft.client.main.Main.main(SourceFile:123)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by BlackHorizon63** [comment]
@winsrp 
Have you installed the CTM(Connected Texture Mod) for Chisel?

Quote from Chisel Project Side:
> NOTICE: Chisel now requires a library mod, CTM. Please install this before updating to 0.0.11+. 

## Note: You do not need this for Server

I had the same issue like you, because i forget to install CTM

**Comment by winsrp** [comment]
I don't have chisel on. that one always crashes before opening the main menu so i rule that one out.

**Comment by GirafiStudios** [comment]
Same issue as https://github.com/Glitchfiend/BiomesOPlenty/issues/1110
