### ISSUE TITLE
Crash when used with Chisel (MC1.12-0.0.13.14)

### ISSUE THREAD

**Issue by spindisc** [Glitchfiend/BiomesOPlenty#1091]
#### Issue Description:
Crashes on start when used with Chisel

#### Steps to reproduce:

1.  Use only these two mods
2.  Try start
3.  Crash! ;)

#### Additional Information:

---- Minecraft Crash Report ----
// On the bright side, I bought you a teddy bear!

Time: 8/6/17 10:12 AM
Description: Initializing game

java.lang.NullPointerException: Initializing game
	at biomesoplenty.common.handler.LeavesModelEventHandler$ModelLeaves.<init>(LeavesModelEventHandler.java:55)
	at biomesoplenty.common.handler.LeavesModelEventHandler.onModelBake(LeavesModelEventHandler.java:46)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_34_LeavesModelEventHandler_onModelBake_ModelBakeEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.client.ForgeHooksClient.onModelBake(ForgeHooksClient.java:367)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:30)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:512)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at biomesoplenty.common.handler.LeavesModelEventHandler$ModelLeaves.<init>(LeavesModelEventHandler.java:55)
	at biomesoplenty.common.handler.LeavesModelEventHandler.onModelBake(LeavesModelEventHandler.java:46)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_34_LeavesModelEventHandler_onModelBake_ModelBakeEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.client.ForgeHooksClient.onModelBake(ForgeHooksClient.java:367)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:30)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:512)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 275373544 bytes (262 MB) / 523501568 bytes (499 MB) up to 6429081600 bytes (6131 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.40 Powered by Forge 14.21.1.2443 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	minecraft{1.12} [Minecraft] (minecraft.jar) 
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.12-14.21.1.2443.jar) 
	UCH	forge{14.21.1.2443} [Minecraft Forge] (forge-1.12-14.21.1.2443.jar) 
	UCH	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.12.jar) 
	UCH	biomesoplenty{7.0.0.2291} [Biomes O' Plenty] (BiomesOPlenty-1.12-7.0.0.2291-universal.jar) 
	UCH	chisel{MC1.12-0.0.13.14} [Chisel] (Chisel-MC1.12-0.0.13.14.jar) 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13491 Compatibility Profile Context 22.19.662.4' Renderer: 'AMD Radeon(TM) HD8970M'
	Launched Version: 1.12-forge1.12-14.21.1.2443
	LWJGL: 2.9.4
	OpenGL: AMD Radeon(TM) HD8970M GL version 4.5.13491 Compatibility Profile Context 22.19.662.4, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-4910MQ CPU @ 2.90GHz

____
#### Affected Versions (Exact numbers, do *NOT* use "latest"):

Biomes O' Plenty - 1.12-7.0.0.2291
Chisel - MC1.12-0.0.13.14
Forge - 1.12-14.21.1.2443
Minecraft - 1.12

**Comment by spindisc** [comment]
Found issue. Chisel dependency mod CTM was not up to date.
