### ISSUE TITLE
Server crashing after lengthy play time. Can't get back into world!

### ISSUE THREAD

**Issue by Mattrock607** [Glitchfiend/BiomesOPlenty#1098]
#### Issue Description:

After 40 to 50 hours (estimated) of gameplay, my world randomly crashed while exploring a new region. The game will not reload; after the title screen, I hit load, and then the game will freeze, either on that loading screen or in-game before anything can be seen. I'll be mighty upset if this world has to be entirely scrapped but I cannot for the life of me figure out what went wrong.

I was sailing in a DaVinci's vessel, attempting to explore/ reveal the coast line of my world by sea when I first crashed. Since then I have completely removed every single mod I've installed other than BoP (I don't want to mess up the terrain obviously), which means I've lost my ship too, and the issue is still occurring. I'm on the cusp of just scratching this world and dropping BoP entirely because it's incredibly frustrating to have to rebuild everything from scratch again, especially when using difficulty-enhancing mods like TaN and PrimalCore.

#### Steps to reproduce:

1. Not sure what to really write here. Explore a new chunk I suppose? I don't know what caused the issue because I can't log into the game to even tell you what biome(s) I was near when the crash happened. 

#### Additional Information:

Crash log
https://pastebin.com/fkH9ZLSr

____
#### Affected Versions (Exact numbers, do *NOT* use "latest"):

- Biomes O' Plenty: 1.12-7.0.0.2291-universal
- Minecraft: 1.12
- Forge: 1.12-14.21.1.2443

Other mods I had installed prior to the crash, including libs. Mods that were actively loaded in the area or had stuff in them that I was carrying are put in bold (excluding libs).

Additional Banners
Astral Sorcery
AutoRegLib
Baubles
BiblioCraft
**BiomesOPlenty**
BottledMilk
Chameleon
Chisel
CTM
Custom NPCs
**DaVinci's Vessels**
FoamFlower
FTBLib
FTBUtilities
GraveStone
Immersive Engineering
Immersive Petroleum
**JEI**
**JourneyMap**
**JustAFewFish**
**Level Up!**
Malisisadvert
Malisisblocks
Malisiscore
MalisisDoors
Malisisswitches
Mantle
Mine Colonies
ModernLights
**Moving World**
Overlord
**Pam's Harvestcraft** (had food in my inventory)
Parachute Mod
**PrimalCore** (had plants in my inventory
**Quark** (was near a pirate ship, probably 100 blocks/ meters away. Pass these regularly without problem)
Simply Conveyors
**Slurp** (always active I think
StorageDrawers
StorageDrawersExtras
Tinker's Construct
Tinker's Addons
**Tough As Nails** (had 2 or 3 canteens of water)
TreeChopper
Vending
Viescraft
Yabba

**Comment by Adaraa** [comment]
This just happen to my MPServer too! :(
BiomesOPlenty-1.12.2-7.0.1.2310-universal

Time: 11/27/17 8:53 PM
Description: Exception ticking world

java.lang.NoClassDefFoundError: net/minecraft/world/World$2
	at net.minecraft.world.World.func_190524_a(World.java:556)
	at net.minecraft.world.World.func_175685_c(World.java:491)
	at net.minecraft.world.World.func_175722_b(World.java:439)
	at net.minecraft.world.World.markAndNotifyBlock(World.java:380)
	at net.minecraft.world.World.func_180501_a(World.java:360)
	at net.minecraft.world.World.func_175656_a(World.java:424)
	at biomesoplenty.common.block.BlockBOPFarmland.func_180650_b(BlockBOPFarmland.java:130)
	at net.minecraft.block.Block.func_180645_a(Block.java:508)
	at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:475)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:225)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:754)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Unknown Source)

**Comment by Forstride** [comment]
Closing this because we either can't/won't fix it or it's not an issue in 1.13
