### ISSUE TITLE
Biomes O Plenty Crashes Minecraft 

### ISSUE THREAD

**Issue by kschenck3** [Glitchfiend/BiomesOPlenty#1101]
---- Minecraft Crash Report ----
// Why is it breaking :(

Time: 7/15/17 2:27 PM
Description: FML has discovered extracted jar files in the mods directory.
This breaks mod loading functionality completely.
Remove the directories and replace with the jar files originally provided.

java.lang.RuntimeException: Extracted mod jars found, loading will NOT continue
	at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:307)
	at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:255)
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:100)
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:79)
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:42)
	at net.minecraftforge.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:138)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12
	Operating System: Mac OS X (x86_64) version 10.12.3
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 160492848 bytes (153 MB) / 255066112 bytes (243 MB) up to 2134114304 bytes (2035 MB)
	JVM Flags: 5 total; -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0

**Comment by Adubbz** [comment]
As per the top of the crash report:

FML has discovered extracted jar files in the mods directory.
This breaks mod loading functionality completely.
Remove the directories and replace with the jar files originally provided.
