### ISSUE TITLE
Biome Finder doen't work

### ISSUE THREAD

**Issue by PongoSapiens** [Glitchfiend/BiomesOPlenty#1109]
#### Issue Description:

Biome Finder doesn't work. It is now craftable with a biome essence, but once you have done so, right clicking it causes the server to throw an exception.

#### Steps to reproduce:

1. Craft BiomeFinder.
2. Combine it with a biome essence (I've tried MushroomIsland, Mesa and Mystic Grove)
3. Right click.

#### Additional Information:
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: net.minecraft.world.biome.Biome.func_185359_l()Ljava/lang/String;
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_121]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_121]
        at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.NoSuchMethodError: net.minecraft.world.biome.Biome.func_185359_l()Ljava/lang/String;
        at biomesoplenty.common.item.ItemBiomeFinder.func_77659_a(ItemBiomeFinder.java:130) ~[ItemBiomeFinder.class:?]
        at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:217) ~[aip.class:?]
        at net.minecraft.server.management.PlayerInteractionManager.func_187250_a(PlayerInteractionManager.java:359) ~[or.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:763) ~[pa.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItem.func_148833_a(SourceFile:32) ~[mb.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItem.func_148833_a(SourceFile:9) ~[mb.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_121]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_121]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        ... 5 more
____
#### Affected Versions (Exact numbers, do *NOT* use "latest"):

- Biomes O' Plenty: 1.12.2-7.0.1.2297
- Minecraft: 1.12.2
- Forge: 2494

**Comment by Adubbz** [comment]
The issue was resolved with the commit https://github.com/Glitchfiend/BiomesOPlenty/commit/33c595f486ced4975faf752980da672b35a0404c, as per the closing message. It isn't possible for this issue to occur anymore for the Biome Finder, it involves calling getBiomeName which all server-side references to were removed with that commit.

/bop biomename is a different matter, it will only work client-side only simply because the information is not available to the server.
