### ISSUE TITLE
1.12 error in log when removing biomes

### ISSUE THREAD

**Issue by Zygus42** [Glitchfiend/BiomesOPlenty#1260]
#### Issue Description:
I'm preventing certain biomes from spawning by setting their ids to -1 in biome_ids.json.  One of these is the "dead_forest" biome.  My log file shows this error:

[09:20:05] [Server thread/ERROR] [FML]: Parsing error loading built-in advancement biomesoplenty:biomesoplenty/all_biomes
com.google.gson.JsonSyntaxException: Unknown biome 'biomesoplenty:dead_forest'
	at net.minecraft.advancements.critereon.LocationPredicate.func_193454_a(SourceFile:77) ~[aq.class:?]
	at net.minecraft.advancements.critereon.PositionTrigger.func_192166_a(SourceFile:59) ~[ar.class:?]
	at net.minecraft.advancements.critereon.PositionTrigger.func_192166_a(SourceFile:18) ~[ar.class:?]
	at net.minecraft.advancements.Criterion.func_192145_a(SourceFile:35) ~[n.class:?]
	at net.minecraft.advancements.Criterion.func_192144_b(SourceFile:46) ~[n.class:?]
	at net.minecraft.advancements.Advancement$Builder.func_192059_a(SourceFile:204) ~[i$a.class:?]
	at net.minecraft.advancements.AdvancementManager$1.deserialize(AdvancementManager.java:50) ~[ns$1.class:?]
	at net.minecraft.advancements.AdvancementManager$1.deserialize(AdvancementManager.java:46) ~[ns$1.class:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[TreeTypeAdapter.class:?]
	at net.minecraft.util.JsonUtils.func_188173_a(SourceFile:492) ~[rc.class:?]
	at net.minecraft.util.JsonUtils.func_193839_a(SourceFile:532) ~[rc.class:?]
	at net.minecraftforge.common.ForgeHooks.lambda$loadAdvancements$0(ForgeHooks.java:1357) ~[ForgeHooks.class:?]
	at net.minecraftforge.common.crafting.CraftingHelper.findFiles(CraftingHelper.java:821) [CraftingHelper.class:?]
	at net.minecraftforge.common.ForgeHooks.loadAdvancements(ForgeHooks.java:1339) [ForgeHooks.class:?]
	at net.minecraftforge.common.ForgeHooks.loadAdvancements(ForgeHooks.java:1313) [ForgeHooks.class:?]
	at net.minecraft.advancements.AdvancementManager.func_192779_a(AdvancementManager.java:69) [ns.class:?]
	at net.minecraft.advancements.AdvancementManager.<init>(AdvancementManager.java:60) [ns.class:?]
	at net.minecraft.world.WorldServer.func_175643_b(WorldServer.java:156) [oo.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:122) [chd.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:156) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
[09:20:05] [Server thread/INFO] [net.minecraft.advancements.AdvancementList]: Loaded 1067 advancements

Seems to me that the achievement should check if the biomes in it are present or not.

#### Affected Versions (Exact numbers, do *NOT* use "latest"):

- Biomes O' Plenty: BiomesOPlenty-1.12.2-7.0.1.2387-universal
- Minecraft: 1.12.2
- Forge: forge-1.12.2-14.23.3.2673-installer-win

**Comment by Forstride** [comment]
We can't.  The advancements use json files like vanilla, not code.  I'm not sure if Forge added extended support to create advancements with code either.

**Comment by Zygus42** [comment]
Bummer, ah well, hope the advancements are not important to the mod's progress.
