### ISSUE TITLE
Current version of the mod crashed.

### ISSUE THREAD

**Issue by LorelaiAdele** [Glitchfiend/BiomesOPlenty#1405]
## Bug Report

Mine craft crashed trying to load the mod saying it has failed to load correctly. The object Block{minecraft:air} (name biomesoplenty:mahogany_sapling is being... thats where is stops.
### How can the crash be reproduced?

Not sure. I just put the current version of Biome's O' Plenty in the mods folder and used the current version of forge, and then tried to load the game.

### Crash Report and Logs

[14:47:36] [main/INFO]: ModLauncher running: args [--username, LorelaiAdele, --version, 1.13.2-forge-25.0.219, --gameDir, /Users/tylerdantzler/Library/Application Support/minecraft, --assetsDir, /Users/tylerdantzler/Library/Application Support/minecraft/assets, --assetIndex, 1.13.1, --uuid, 9dc5ddaecee94a28950fd4195b460478, --accessToken, ❄❄❄❄❄❄❄❄, --userType, mojang, --versionType, release, --launchTarget, fmlclient, --fml.forgeVersion, 25.0.219, --fml.mcVersion, 1.13.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20190213.203750]
[14:47:36] [main/INFO]: ModLauncher starting: java version 1.8.0_74
[14:47:36] [main/INFO]: Added Lets Encrypt root certificates as additional trust
[14:47:37] [main/INFO]: Launching target 'fmlclient' with arguments [--version, 1.13.2-forge-25.0.219, --gameDir, /Users/tylerdantzler/Library/Application Support/minecraft, --assetsDir, /Users/tylerdantzler/Library/Application Support/minecraft/assets, --username, LorelaiAdele, --assetIndex, 1.13.1, --uuid, 9dc5ddaecee94a28950fd4195b460478, --accessToken, ❄❄❄❄❄❄❄❄, --userType, mojang, --versionType, release]
[14:47:38] [Client thread/INFO]: Setting user: LorelaiAdele
[14:47:44] [Client thread/WARN]: Skipping bad option: lastServer:
[14:47:44] [Client thread/INFO]: LWJGL Version: 3.1.6 build 14
[14:47:44] [Client thread/WARN]: Couldn't get pack info for: net.minecraft.resources.ResourcePackFileNotFoundException: 'pack.mcmeta' in ResourcePack '/Users/tylerdantzler/Library/Application Support/minecraft/resourcepacks/WizardingWorld 1.12.zip'
[14:47:44] [Client thread/WARN]: Couldn't get pack info for: net.minecraft.resources.ResourcePackFileNotFoundException: 'pack.mcmeta' in ResourcePack '/Users/tylerdantzler/Library/Application Support/minecraft/resourcepacks/drea-pack-1517024909.zip'
[14:47:44] [Client thread/WARN]: Couldn't get pack info for: net.minecraft.resources.ResourcePackFileNotFoundException: 'pack.mcmeta' in ResourcePack '/Users/tylerdantzler/Library/Application Support/minecraft/resourcepacks/HEYY.zip'
[14:47:44] [Client thread/INFO]: Loading Network data for FML net version: FML2
[14:47:45] [modloading-worker-3/INFO]: Forge mod loading, version 25.0.219, for MC 1.13.2 with MCP 20190213.203750
[14:47:45] [modloading-worker-3/INFO]: MinecraftForge v25.0.219 Initialized
[14:47:45] [modloading-worker-5/WARN]: No data fixer registered for entity biomesoplenty:mudball
[14:47:45] [modloading-worker-5/WARN]: No data fixer registered for entity biomesoplenty:boat_bop
[14:47:45] [Client thread/ERROR]: Encountered an exception during parallel processing
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError
	at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1006) ~[?:1.8.0_74]
	at net.minecraftforge.fml.ModList.dispatchParallelEvent(ModList.java:120) ~[?:?]
	at net.minecraftforge.fml.ModList.lambda$static$1(ModList.java:84) ~[?:?]
	at net.minecraftforge.fml.LifecycleEventProvider.dispatch(LifecycleEventProvider.java:70) ~[?:?]
	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:153) ~[?:?]
	at net.minecraftforge.fml.ModLoader.loadMods(ModLoader.java:137) ~[?:?]
	at net.minecraftforge.fml.client.ClientModLoader.begin(ClientModLoader.java:63) ~[?:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:412) ~[?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:345) ~[?:?]
	at net.minecraft.client.main.Main.main(SourceFile:144) ~[1.13.2-forge-25.0.219.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_74]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_74]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_74]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_74]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.13.2-25.0.219.jar:25.0]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:19) [modlauncher-2.1.1.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:32) [modlauncher-2.1.1.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:50) [modlauncher-2.1.1.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:59) [modlauncher-2.1.1.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:44) [modlauncher-2.1.1.jar:?]
Caused by: java.lang.NoClassDefFoundError
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_74]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_74]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_74]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_74]
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:598) ~[?:1.8.0_74]
	at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1005) ~[?:1.8.0_74]
	... 19 more
Caused by: java.lang.NoClassDefFoundError
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_74]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_74]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_74]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_74]
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:598) ~[?:1.8.0_74]
	at java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:677) ~[?:1.8.0_74]
	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:735) ~[?:1.8.0_74]
	at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:160) ~[?:1.8.0_74]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:174) ~[?:1.8.0_74]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233) ~[?:1.8.0_74]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_74]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:583) ~[?:1.8.0_74]
	at net.minecraftforge.fml.ModList.lambda$dispatchParallelEvent$10(ModList.java:120) ~[?:?]
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386) ~[?:1.8.0_74]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_74]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_74]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[?:1.8.0_74]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_74]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/item/DyeColor
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_74]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_74]
	at net.minecraftforge.fml.AutomaticEventSubscriber.lambda$inject$3(AutomaticEventSubscriber.java:70) ~[?:?]
	at java.util.ArrayList.forEach(ArrayList.java:1249) ~[?:1.8.0_74]
	at net.minecraftforge.fml.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:57) ~[?:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:139) ~[?:25.0]
	at java.util.function.Consumer.lambda$andThen$0(Consumer.java:65) ~[?:1.8.0_74]
	at java.util.function.Consumer.lambda$andThen$0(Consumer.java:65) ~[?:1.8.0_74]
	at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:111) ~[?:?]
	at net.minecraftforge.fml.ModList.lambda$null$9(ModList.java:120) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_74]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) ~[?:1.8.0_74]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_74]
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291) ~[?:1.8.0_74]
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731) ~[?:1.8.0_74]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_74]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_74]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[?:1.8.0_74]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_74]
Caused by: java.lang.ClassNotFoundException: net.minecraft.item.DyeColor
	at java.lang.ClassLoader.findClass(ClassLoader.java:530) ~[?:1.8.0_74]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_74]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:84) ~[modlauncher-2.1.1.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_74]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_74]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_74]
	at net.minecraftforge.fml.AutomaticEventSubscriber.lambda$inject$3(AutomaticEventSubscriber.java:70) ~[?:?]
	at java.util.ArrayList.forEach(ArrayList.java:1249) ~[?:1.8.0_74]
	at net.minecraftforge.fml.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:57) ~[?:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:139) ~[?:25.0]
	at java.util.function.Consumer.lambda$andThen$0(Consumer.java:65) ~[?:1.8.0_74]
	at java.util.function.Consumer.lambda$andThen$0(Consumer.java:65) ~[?:1.8.0_74]
	at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:111) ~[?:?]
	at net.minecraftforge.fml.ModList.lambda$null$9(ModList.java:120) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_74]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) ~[?:1.8.0_74]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_74]
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291) ~[?:1.8.0_74]
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731) ~[?:1.8.0_74]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_74]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_74]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[?:1.8.0_74]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_74]
[14:47:45] [modloading-worker-5/ERROR]: Failed to create mod instance. ModID: biomesoplenty, class biomesoplenty.core.BiomesOPlenty
java.lang.IllegalStateException: The object Block{minecraft:air} (name biomesoplenty:mahogany_sapling) is being added too late.
	at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:340) ~[?:?]
	at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:300) ~[?:?]
	at net.minecraftforge.registries.ForgeRegistry.register(ForgeRegistry.java:125) ~[?:?]
	at biomesoplenty.init.ModBlocks.registerBlock(ModBlocks.java:338) ~[?:?]
	at biomesoplenty.init.ModBlocks.init(ModBlocks.java:150) ~[?:?]
	at biomesoplenty.core.BiomesOPlenty.<init>(BiomesOPlenty.java:43) ~[?:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_74]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_74]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_74]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_74]
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_74]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:130) ~[?:25.0]
	at java.util.function.Consumer.lambda$andThen$0(Consumer.java:65) ~[?:1.8.0_74]
	at java.util.function.Consumer.lambda$andThen$0(Consumer.java:65) ~[?:1.8.0_74]
	at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:111) ~[?:?]
	at net.minecraftforge.fml.ModList.lambda$null$9(ModList.java:120) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) [?:1.8.0_74]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) [?:1.8.0_74]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) [?:1.8.0_74]
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291) [?:1.8.0_74]
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731) [?:1.8.0_74]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_74]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_74]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_74]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_74]
[14:47:45] [Client thread/ERROR]: Skipping lifecycle event SETUP, 1 errors found.
[14:47:45] [Client thread/FATAL]: Failed to complete lifecycle event SETUP, 1 errors found
[14:47:45] [Client thread/FATAL]: EventBus 0 shutting down - future events will not be posted.
java.lang.Exception: stacktrace
	at net.minecraftforge.eventbus.EventBus.shutdown(EventBus.java:274) ~[eventbus-0.9.2-service.jar:?]
	at net.minecraftforge.fml.client.ClientModLoader.begin(ClientModLoader.java:65) ~[?:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:412) ~[?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:345) ~[?:?]
	at net.minecraft.client.main.Main.main(SourceFile:144) ~[1.13.2-forge-25.0.219.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_74]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_74]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_74]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_74]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.13.2-25.0.219.jar:25.0]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:19) [modlauncher-2.1.1.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:32) [modlauncher-2.1.1.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:50) [modlauncher-2.1.1.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:59) [modlauncher-2.1.1.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:44) [modlauncher-2.1.1.jar:?]
[14:47:45] [Client thread/WARN]: Couldn't get pack info for: net.minecraft.resources.ResourcePackFileNotFoundException: 'pack.mcmeta' in ResourcePack '/Users/tylerdantzler/Library/Application Support/minecraft/resourcepacks/WizardingWorld 1.12.zip'
[14:47:45] [Client thread/WARN]: Couldn't get pack info for: net.minecraft.resources.ResourcePackFileNotFoundException: 'pack.mcmeta' in ResourcePack '/Users/tylerdantzler/Library/Application Support/minecraft/resourcepacks/drea-pack-1517024909.zip'
[14:47:45] [Client thread/WARN]: Couldn't get pack info for: net.minecraft.resources.ResourcePackFileNotFoundException: 'pack.mcmeta' in ResourcePack '/Users/tylerdantzler/Library/Application Support/minecraft/resourcepacks/HEYY.zip'
[14:47:45] [Client thread/INFO]: Reloading ResourceManager: BiomesOPlenty-1.13.2-8.0.0.164-universal.jar, ElevatorMod-1.14.2-1.3.10.jar, FastLeafDecay-v15.jar, forge-1.13.2-25.0.219-universal.jar, jei-1.13.2-5.0.0.28.jar, worldedit-forge-mc1.13.2-7.0.0.jar, Default, TARDIS-MCP-master, TARDIS-SoundResourcePack-master
[14:47:46] [Sound Library Loader/INFO]: Starting up SoundSystem version 201809301515...
[14:47:46] [Thread-5/INFO]: Initializing No Sound
[14:47:46] [Thread-5/INFO]: (Silent Mode)
[14:47:46] [Thread-5/INFO]: OpenAL initialized.
[14:47:47] [Sound Library Loader/INFO]: Preloading sound minecraft:sounds/ambient/underwater/underwater_ambience.ogg
[14:47:47] [Sound Library Loader/INFO]: Sound engine started
[14:47:50] [Client thread/INFO]: Max texture size: 16384
[14:47:51] [Client thread/INFO]: Created: 1024x1024 textures-atlas
[14:47:53] [Client thread/ERROR]: Skipping lifecycle event ENQUEUE_IMC, 1 errors found.
[14:47:53] [Client thread/FATAL]: Failed to complete lifecycle event ENQUEUE_IMC, 1 errors found
[14:47:53] [Client thread/FATAL]: EventBus 0 shutting down - future events will not be posted.
java.lang.Exception: stacktrace
	at net.minecraftforge.eventbus.EventBus.shutdown(EventBus.java:274) ~[eventbus-0.9.2-service.jar:?]
	at net.minecraftforge.fml.client.ClientModLoader.end(ClientModLoader.java:76) ~[?:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:479) ~[?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:345) ~[?:?]
	at net.minecraft.client.main.Main.main(SourceFile:144) ~[1.13.2-forge-25.0.219.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_74]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_74]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_74]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_74]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.13.2-25.0.219.jar:25.0]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:19) [modlauncher-2.1.1.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:32) [modlauncher-2.1.1.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:50) [modlauncher-2.1.1.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:59) [modlauncher-2.1.1.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:44) [modlauncher-2.1.1.jar:?]
[14:47:53] [Client thread/WARN]: Skipping bad option: lastServer:
[14:47:55] [Thread-1/FATAL]: Forge config just got changed on the file system!

### Mod Version

I was using the version 1.13.2-8.0.0164

**Comment by Forstride** [comment]
You either need to downgrade Forge (25.0.215 is the version the mod is compiled against), or something is wrong with your Java install.  Beyond that, we can't help, as we've already moved on to updating to 1.14.3, which has pretty much already replaced 1.13.

**Comment by LorelaiAdele** [comment]
I switched version of forge and updated java and still can't load the mod.
