### ISSUE TITLE
[1.14.3] Missing item tags for BOP boats

### ISSUE THREAD

**Issue by ProsperCraft** [Glitchfiend/BiomesOPlenty#1416]
## Bug Report

[ Stacktrace on load. ]</br>

### How can the issue be reproduced?

[ Load BoP with forge .60 ]</br>

### Logs

[ [19Jul2019 13:23:04.214] [Server-Worker-9/ERROR] [net.minecraft.tags.TagCollection/]: Couldn't read item tag list minecraft:boats from minecraft:tags/items/boats.json in data pack BiomesOPlenty-1.14.3-9.0.0.173-universal.jar
com.google.gson.JsonParseException: Unknown value 'biomesoplenty:fir_boat'
	at net.minecraft.tags.Tag$Builder.lambda$fromJson$0(Tag.java:156) ~[?:?]
	at java.util.Optional.orElseThrow(Optional.java:290) ~[?:1.8.0_212]
	at net.minecraft.tags.Tag$Builder.func_219783_a(Tag.java:155) ~[?:?]
	at net.minecraft.tags.TagCollection.lambda$reload$3(TagCollection.java:101) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590) [?:1.8.0_212]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1582) [?:1.8.0_212]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_212]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_212]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_212]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_212] ]</br>

### Mod Version
[BiomesOPlenty-1.14.3-9.0.0.173-universal]</br>

**Comment by Forstride** [comment]
The boats don't exist yet because they were broken as fuck (Which we already have an issue for), and this doesn't even affect anything as it is

**Comment by ProsperCraft** [comment]
Yea, we are still suffering from the boat apocalypse of 1.12.2 players getting kicked when near one of them.
