### ISSUE TITLE
Random startup crash

### ISSUE THREAD

**Issue by bobsoverad** [Glitchfiend/BiomesOPlenty#1463]
Me and my friend have the exact same mods and everything on minecraft his game was working with this version of BOP but one day it crashed and it just kept crashing the only different thing that he has is he uses Titan launcher. The Bop version is  Biomes O' Plenty 1.14.4-9.0.0.231 and the forge is 28.0.49
  

crash report:

---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 8/23/19 6:15 PM
Description: Rendering overlay

com.electronwill.nightconfig.core.io.ParsingException: Not enough data available
	at com.electronwill.nightconfig.core.io.ParsingException.notEnoughData(ParsingException.java:22) ~[core-3.6.0.jar:?] {}
	at com.electronwill.nightconfig.core.io.ReaderInput.directReadChar(ReaderInput.java:36) ~[core-3.6.0.jar:?] {}
	at com.electronwill.nightconfig.core.io.AbstractInput.readChar(AbstractInput.java:49) ~[core-3.6.0.jar:?] {}
	at com.electronwill.nightconfig.core.io.AbstractInput.readCharsUntil(AbstractInput.java:123) ~[core-3.6.0.jar:?] {}
	at com.electronwill.nightconfig.toml.TableParser.parseKey(TableParser.java:166) ~[toml-3.6.0.jar:?] {}
	at com.electronwill.nightconfig.toml.TableParser.parseDottedKey(TableParser.java:145) ~[toml-3.6.0.jar:?] {}
	at com.electronwill.nightconfig.toml.TableParser.parseNormal(TableParser.java:55) ~[toml-3.6.0.jar:?] {}
	at com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:44) ~[toml-3.6.0.jar:?] {}
	at com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:37) ~[toml-3.6.0.jar:?] {}
	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:113) ~[core-3.6.0.jar:?] {}
	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:219) ~[core-3.6.0.jar:?] {}
	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:202) ~[core-3.6.0.jar:?] {}
	at com.electronwill.nightconfig.core.file.WriteSyncFileConfig.load(WriteSyncFileConfig.java:73) ~[core-3.6.0.jar:?] {}
	at com.electronwill.nightconfig.core.file.AutosaveCommentedFileConfig.load(AutosaveCommentedFileConfig.java:85) ~[core-3.6.0.jar:?] {}
	at net.minecraftforge.fml.config.ConfigFileTypeHandler.lambda$reader$1(ConfigFileTypeHandler.java:54) ~[?:?] {}
	at net.minecraftforge.fml.config.ConfigTracker.openConfig(ConfigTracker.java:99) ~[?:?] {}
	at net.minecraftforge.fml.config.ConfigTracker.lambda$loadConfigs$1(ConfigTracker.java:83) ~[?:?] {}
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_181] {}
	at java.util.Collections$SynchronizedCollection.forEach(Collections.java:2062) ~[?:1.8.0_181] {}
	at net.minecraftforge.fml.config.ConfigTracker.loadConfigs(ConfigTracker.java:83) ~[?:?] {}
	at net.minecraftforge.fml.ModLoader.loadMods(ModLoader.java:149) ~[?:?] {}
	at net.minecraftforge.fml.client.ClientModLoader.lambda$startModLoading$6(ClientModLoader.java:105) ~[?:?] {pl:runtimedistcleaner:A}
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:95) ~[?:?] {pl:runtimedistcleaner:A}
	at net.minecraftforge.fml.client.ClientModLoader.startModLoading(ClientModLoader.java:105) ~[?:?] {pl:runtimedistcleaner:A}
	at net.minecraftforge.fml.client.ClientModLoader.lambda$onreload$3(ClientModLoader.java:87) ~[?:?] {pl:runtimedistcleaner:A}
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:95) ~[?:?] {pl:runtimedistcleaner:A}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626) ~[?:1.8.0_181] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1618) ~[?:1.8.0_181] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_181] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_181] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[?:1.8.0_181] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_181] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.electronwill.nightconfig.core.io.ParsingException.notEnoughData(ParsingException.java:22)
	at com.electronwill.nightconfig.core.io.ReaderInput.directReadChar(ReaderInput.java:36)
	at com.electronwill.nightconfig.core.io.AbstractInput.readChar(AbstractInput.java:49)
	at com.electronwill.nightconfig.core.io.AbstractInput.readCharsUntil(AbstractInput.java:123)
	at com.electronwill.nightconfig.toml.TableParser.parseKey(TableParser.java:166)
	at com.electronwill.nightconfig.toml.TableParser.parseDottedKey(TableParser.java:145)
	at com.electronwill.nightconfig.toml.TableParser.parseNormal(TableParser.java:55)
	at com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:44)
	at com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:37)
	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:113)
	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:219)
	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:202)
	at com.electronwill.nightconfig.core.file.WriteSyncFileConfig.load(WriteSyncFileConfig.java:73)
	at com.electronwill.nightconfig.core.file.AutosaveCommentedFileConfig.load(AutosaveCommentedFileConfig.java:85)
	at net.minecraftforge.fml.config.ConfigFileTypeHandler.lambda$reader$1(ConfigFileTypeHandler.java:54)
	at net.minecraftforge.fml.config.ConfigTracker.openConfig(ConfigTracker.java:99)
	at net.minecraftforge.fml.config.ConfigTracker.lambda$loadConfigs$1(ConfigTracker.java:83)
	at java.lang.Iterable.forEach(Iterable.java:75)

-- Overlay render details --
Details:
	Overlay name: net.minecraft.client.gui.ResourceLoadProgressGui
Stacktrace:
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:544)
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:886)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:384)
	at net.minecraft.client.main.Main.main(SourceFile:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:50)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:68)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:80)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_181, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 114155984 bytes (108 MB) / 411279360 bytes (392 MB) up to 15608315904 bytes (14885 MB)
	CPUs: 4
	JVM Flags: 5 total; -Xmn128M -Xmx14898M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -XX:+UseConcMarkSweepGC
	ModLauncher: 3.2.0+60+b86c1d4
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-0.10.6-service.jar eventbus PLUGINSERVICE 
		/forge-1.14.4-28.0.49.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.14.4-28.0.49.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-0.16.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.14.4-28.0.49.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.14.4-28.0.49.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.14.4-28.0.49.jar fml TRANSFORMATIONSERVICE 
	FML: 28.0
	Forge: net.minecraftforge:28.0.49
	FML Language Providers: 
		javafml@28.0
		minecraft@1
	Mod List: 
		betteranimalsplus-1.14.4-7.0.2.1 (2).jar Better Animals Plus {betteranimalsplus@7.0.2.1 COMMON_SETUP}
		BiomesOPlenty-1.14.4-9.0.0.231-universal.jar Biomes O' Plenty {biomesoplenty@1.14.4-9.0.0.229 COMMON_SETUP}
		extragolems-9.0.0-beta.jar Extra Golems {golems@TODO-golems_version COMMON_SETUP}
		inventorysorter-1.14.4-15.2.0.jar Simple Inventory Sorter {inventorysorter@15.2.0 COMMON_SETUP}
		jei-1.14.4-6.0.0.10 (2).jar Just Enough Items {jei@6.0.0.10 COMMON_SETUP}
		QuickLeafDecay-MC1.14.4-1.2.5.jar Quick Leaf Decay {quickleafdecay@1.2.5 COMMON_SETUP}
		SuperTools-1.14.4_1.4.jar Super Tools {supertools@1.14.4_1.4 COMMON_SETUP}
		u_team_core-1.14.4-2.7.1.130.jar U Team Core {uteamcore@2.7.1.130 COMMON_SETUP}
		useful_backpacks-1.14.4-1.7.0.34.jar Useful Backpacks {usefulbackpacks@1.7.0.34 COMMON_SETUP}
		XaerosWorldMap_1.4.7.1_Forge_1.14.4.jar Xaero's World Map {xaeroworldmap@1.4.7 COMMON_SETUP}
		XL-Food-Mod-1.14.4-2.0.3.jar XL Food Mod {xlfoodmod@2.0.3 COMMON_SETUP}
		forge-1.14.4-28.0.49-universal.jar Forge {forge@28.0.49 COMMON_SETUP}
		forge-1.14.4-28.0.49-client.jar Minecraft {minecraft@1.14.4 COMMON_SETUP}
	Launched Version: 1.14.4-forge-28.0.49
	LWJGL: 3.2.2 build 10
	OpenGL: GeForce GTX 1050 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 399.07, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: vanilla
	Current Language: English (US)
	CPU: 4x AMD A10-7860K Radeon R7, 12 Compute Cores 4C+8G

**Comment by Adubbz** [comment]
We have no way of knowing what the issue is without a log file.

**Comment by bobsoverad** [comment]
i will poste it later today or tommorow

**Comment by bobsoverad** [comment]
i posted the crash report

**Comment by Adubbz** [comment]
Delete your Forge config files.

**Comment by bobsoverad** [comment]
How does that file look like

**Comment by Forstride** [comment]
fml.toml and forge-client.toml in the /config/ folder

**Comment by bobsoverad** [comment]
I didn't work thanks tho

**Comment by Forstride** [comment]
Update Forge to 28.0.55

**Comment by bobsoverad** [comment]
Do i still use the same bop version

**Comment by Forstride** [comment]
The error has nothing to do with BOP.  It's a Forge error that was fixed after the version you were using.

**Comment by bobsoverad** [comment]
It still doesn't work even with 28.0.55
