### ISSUE TITLE
com.electronwill.nightconfig.core.io.ParsingException.notEnoughData

### ISSUE THREAD

**Issue by nonplussedflame** [Glitchfiend/BiomesOPlenty#1469]
### How can the crash be reproduced?

[ when the game just starts loading mods with the mod only installed. ]</br>

### Crash Report and Logs

[ ---- Minecraft Crash Report ----
// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 9/17/19 3:29 PM
Description: Rendering overlay

com.electronwill.nightconfig.core.io.ParsingException: Not enough data available
	at com.electronwill.nightconfig.core.io.ParsingException.notEnoughData(ParsingException.java:22) ~[core-3.6.0.jar:?] {}
	at com.electronwill.nightconfig.core.io.ReaderInput.directReadChar(ReaderInput.java:36) ~[core-3.6.0.jar:?] {}
	at com.electronwill.nightconfig.core.io.AbstractInput.readChar(AbstractInput.java:49) ~[core-3.6.0.jar:?] {}
	at com.electronwill.nightconfig.core.io.AbstractInput.readCharsUntil(AbstractInput.java:123) ~[core-3.6.0.jar:?] {}
	at com.electronwill.nightconfig.toml.TableParser.parseKey(TableParser.java:166) ~[toml-3.6.0.jar:?] {}
	at com.electronwill.nightconfig.toml.TableParser.parseDottedKey(TableParser.java:145) ~[toml-3.6.0.jar:?] {}
	at com.electronwill.nightconfig.toml.TableParser.parseNormal(TableParser.java:55) ~[toml-3.6.0.jar:?] {}
	at com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:44) ~[toml-3.6.0.jar:?] {}
	at com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:37) ~[toml-3.6.0.jar:?] {}
	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:113) ~[core-3.6.0.jar:?] {}
	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:219) ~[core-3.6.0.jar:?] {}
	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:202) ~[core-3.6.0.jar:?] {}
	at com.electronwill.nightconfig.core.file.WriteSyncFileConfig.load(WriteSyncFileConfig.java:73) ~[core-3.6.0.jar:?] {}
	at com.electronwill.nightconfig.core.file.AutosaveCommentedFileConfig.load(AutosaveCommentedFileConfig.java:85) ~[core-3.6.0.jar:?] {}
	at net.minecraftforge.fml.config.ConfigFileTypeHandler.lambda$reader$1(ConfigFileTypeHandler.java:53) ~[?:?] {}
	at net.minecraftforge.fml.config.ConfigFileTypeHandler$$Lambda$2495/1356638883.apply(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.config.ConfigTracker.openConfig(ConfigTracker.java:99) ~[?:?] {}
	at net.minecraftforge.fml.config.ConfigTracker.lambda$loadConfigs$1(ConfigTracker.java:83) ~[?:?] {}
	at net.minecraftforge.fml.config.ConfigTracker$$Lambda$2494/473602903.accept(Unknown Source) ~[?:?] {}
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_51] {}
	at java.util.Collections$SynchronizedCollection.forEach(Collections.java:2062) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.config.ConfigTracker.loadConfigs(ConfigTracker.java:83) ~[?:?] {}
	at net.minecraftforge.fml.ModLoader.loadMods(ModLoader.java:149) ~[?:?] {}
	at net.minecraftforge.fml.client.ClientModLoader.lambda$startModLoading$6(ClientModLoader.java:105) ~[?:?] {pl:runtimedistcleaner:A}
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2488/871335470.run(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:95) ~[?:?] {pl:runtimedistcleaner:A}
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$1925/161020884.run(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.client.ClientModLoader.startModLoading(ClientModLoader.java:105) ~[?:?] {pl:runtimedistcleaner:A}
	at net.minecraftforge.fml.client.ClientModLoader.lambda$onreload$3(ClientModLoader.java:87) ~[?:?] {pl:runtimedistcleaner:A}
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2486/645018917.run(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:95) ~[?:?] {pl:runtimedistcleaner:A}
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$1925/161020884.run(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.electronwill.nightconfig.core.io.ParsingException.notEnoughData(ParsingException.java:22)
	at com.electronwill.nightconfig.core.io.ReaderInput.directReadChar(ReaderInput.java:36)
	at com.electronwill.nightconfig.core.io.AbstractInput.readChar(AbstractInput.java:49)
	at com.electronwill.nightconfig.core.io.AbstractInput.readCharsUntil(AbstractInput.java:123)
	at com.electronwill.nightconfig.toml.TableParser.parseKey(TableParser.java:166)
	at com.electronwill.nightconfig.toml.TableParser.parseDottedKey(TableParser.java:145)
	at com.electronwill.nightconfig.toml.TableParser.parseNormal(TableParser.java:55)
	at com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:44)
	at com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:37)
	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:113)
	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:219)
	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:202)
	at com.electronwill.nightconfig.core.file.WriteSyncFileConfig.load(WriteSyncFileConfig.java:73)
	at com.electronwill.nightconfig.core.file.AutosaveCommentedFileConfig.load(AutosaveCommentedFileConfig.java:85)
	at net.minecraftforge.fml.config.ConfigFileTypeHandler.lambda$reader$1(ConfigFileTypeHandler.java:53)
	at net.minecraftforge.fml.config.ConfigFileTypeHandler$$Lambda$2495/1356638883.apply(Unknown Source)
	at net.minecraftforge.fml.config.ConfigTracker.openConfig(ConfigTracker.java:99)
	at net.minecraftforge.fml.config.ConfigTracker.lambda$loadConfigs$1(ConfigTracker.java:83)
	at net.minecraftforge.fml.config.ConfigTracker$$Lambda$2494/473602903.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at java.util.Collections$SynchronizedCollection.forEach(Collections.java:2062)
	at net.minecraftforge.fml.config.ConfigTracker.loadConfigs(ConfigTracker.java:83)
	at net.minecraftforge.fml.ModLoader.loadMods(ModLoader.java:149)

-- Overlay render details --
Details:
	Overlay name: net.minecraft.client.gui.ResourceLoadProgressGui
Stacktrace:
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:544)
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:887)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:384)
	at net.minecraft.client.main.Main.main(SourceFile:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$347/1419125235.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:50)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:68)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:80)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1508243280 bytes (1438 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 3.2.0+60+b86c1d4
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-1.0.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.14.4-28.1.6.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.14.4-28.1.6.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-1.0.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.14.4-28.1.6.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.14.4-28.1.6.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.14.4-28.1.6.jar fml TRANSFORMATIONSERVICE 
	FML: 28.1
	Forge: net.minecraftforge:28.1.6
	FML Language Providers: 
		javafml@28.1
		minecraft@1
	Mod List: 
		BiomesOPlenty-1.14.4-9.0.0.253-universal.jar Biomes O' Plenty {biomesoplenty@1.14.4-9.0.0.253 COMMON_SETUP}
		forge-1.14.4-28.1.6-universal.jar Forge {forge@28.1.6 COMMON_SETUP}
		forge-1.14.4-28.1.6-client.jar Minecraft {minecraft@1.14.4 COMMON_SETUP}
	Launched Version: 1.14.4-forge-28.1.6
	LWJGL: 3.2.2 build 10
	OpenGL: GeForce GT 630M/PCIe/SSE2 GL version 4.6.0 NVIDIA 389.12, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: vanilla, file/ModernArch v39 [1.13 - 1.14] [512x512].zip
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i3-3217U CPU @ 1.80GHz. ]</br>

### Mod Version
[ 9.0.0.253 ]</br>

**Comment by ProsperCraft** [comment]
Try updating Forge, you are 38 versions behind.  There have been breaking changes after release.

**Comment by Forstride** [comment]
Closing since it's not relevant to 1.15 and/or has been fixed already.

**Comment by Bullmilk** [comment]
update-still aproblem
