### ISSUE TITLE
Crash on world load

### ISSUE THREAD

**Issue by Zulea7** [Glitchfiend/BiomesOPlenty#1557]
Crash on world load with biomes o plenty world type. Happens with every update after 10.0.0.313
Tried with no other mods but biomes o plenty with same results, forge is updated to latest version. Can't load any previous saves either. 

---- Minecraft Crash Report ----
// My bad.

Time: 2/17/20 10:42 PM
Description: Exception in server tick loop

java.lang.ExceptionInInitializerError: null
	at biomesoplenty.common.world.BOPLayerUtil.createBiomeFactory(BOPLayerUtil.java:109) ~[?:?] {re:classloading}
	at biomesoplenty.common.world.BOPLayerUtil.createAreaFactories(BOPLayerUtil.java:141) ~[?:?] {re:classloading}
	at biomesoplenty.common.world.BOPLayerUtil.createGenLayers(BOPLayerUtil.java:180) ~[?:?] {re:classloading}
	at biomesoplenty.common.world.BOPBiomeProvider.<init>(BOPBiomeProvider.java:42) ~[?:?] {re:classloading}
	at biomesoplenty.common.world.WorldTypeBOP.createChunkGenerator(WorldTypeBOP.java:36) ~[?:?] {re:classloading}
	at net.minecraft.world.server.ServerWorld.lambda$new$3(ServerWorld.java:172) ~[?:?] {re:classloading}
	at net.minecraft.world.server.ServerWorld$$Lambda$3963/1784081854.apply(Unknown Source) ~[?:?] {}
	at net.minecraft.world.World.<init>(World.java:98) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld.<init>(ServerWorld.java:171) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_213194_a(MinecraftServer.java:373) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:78) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:96) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:611) [?:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}
Caused by: java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:135) ~[?:1.8.0_51] {}
	at biomesoplenty.common.world.layer.BOPBiomeEdgeLayer.<clinit>(BOPBiomeEdgeLayer.java:47) ~[?:?] {re:classloading}
	... 14 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 11208905216 bytes (10689 MB) / 12683575296 bytes (12096 MB) up to 12884901888 bytes (12288 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx12G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 5.0.0-milestone.4+67+b1a340b
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.0.0-milestone.1-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.1.14.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.14.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.0.0-milestone.1-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.1.14.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.14.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.15.2-31.1.14.jar fml TRANSFORMATIONSERVICE 
	FML: 31.1
	Forge: net.minecraftforge:31.1.14
	FML Language Providers: 
		javafml@31.1
		minecraft@1
	Mod List: 
		forge-1.15.2-31.1.14-client.jar Minecraft {minecraft@1.15.2 DONE}
		forge-1.15.2-31.1.14-universal.jar Forge {forge@31.1.14 DONE}
		BiomesOPlenty-1.15.2-10.0.0.329-universal.jar Biomes O' Plenty {biomesoplenty@1.15.2-10.0.0.327 DONE}
	Player Count: 0 / 8; []
	Data Packs: vanilla, mod:biomesoplenty, mod:forge (incompatible)
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'

**Comment by Zulea7** [comment]
Solved: Deleting config solved this issue.
