### ISSUE TITLE
java.lang.IllegalStateException: No renderer registered for biomesoplenty:boat_bop

### ISSUE THREAD

**Issue by Ellioooot** [Glitchfiend/BiomesOPlenty#1566]
## Bug Report

[--- ]</br>

### How can the crash be reproduced?

[ I installed optifine by placing it in the mods folder. ]</br>

### Crash Report and Logs

[ ---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 3/16/20 10:13 AM
Description: Initializing game

java.lang.IllegalStateException: No renderer registered for biomesoplenty:boat_bop
	at net.minecraft.client.renderer.entity.EntityRendererManager.<init>(EntityRendererManager.java:222) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:425) [?:?] {re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:166) [?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.15.2-31.1.0.jar:31.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$414/2025928493.call(Unknown Source) [forge-1.15.2-31.1.0.jar:31.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.0.0-milestone.4.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.client.renderer.entity.EntityRendererManager.<init>(EntityRendererManager.java:222)
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:425)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(SourceFile:166)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$414/2025928493.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 799219568 bytes (762 MB) / 1963982848 bytes (1873 MB) up to 6203899904 bytes (5916 MB)
	CPUs: 4
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6656m -Xms256m -XX:PermSize=256m
	ModLauncher: 5.0.0-milestone.4+67+b1a340b
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.0.0-milestone.1-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.1.0.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.0.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.0.0-milestone.1-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.1.0.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.0.jar runtimedistcleaner PLUGINSERVICE 
		/preview_OptiFine_1.15.2_HD_U_G1_pre9.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.15.2-31.1.0.jar fml TRANSFORMATIONSERVICE 
	FML: 31.1
	Forge: net.minecraftforge:31.1.0
	FML Language Providers: 
		javafml@31.1
		minecraft@1
	Mod List: 
		forge-1.15.2-31.1.0-client.jar Minecraft {minecraft@1.15.2 COMMON_SETUP}
		inventorysorter-1.15.2-17.0.0.jar Simple Inventory Sorter {inventorysorter@17.0.0 COMMON_SETUP}
		EnchantmentDescriptions-1.15.2-2.0.3.jar EnchantmentDescriptions {enchdesc@2.0.3 COMMON_SETUP}
		swingthroughgrass-1.15.2-1.4.0.jar SwingThroughGrass {swingthroughgrass@1.15.2-1.4.0 COMMON_SETUP}
		AmbientSounds_v3.0.17_mc1.15.2.jar Ambient Sounds {ambientsounds@3.0.3 COMMON_SETUP}
		MouseTweaks-2.13-mc1.15.1.jar Mouse Tweaks {mousetweaks@2.13 COMMON_SETUP}
		damage_indicator-0.0.9.jar Ama's Damage Indicator {damage_indicator@0.0.9 COMMON_SETUP}
		BiomesOPlenty-1.15.2-10.0.0.345-universal.jar Biomes O' Plenty {biomesoplenty@1.15.2-10.0.0.342 COMMON_SETUP}
		valhelsia_structures-15.0.2.jar Valhelsia Structures {valhelsia_structures@15.0.2 COMMON_SETUP}
		jei-1.15.2-6.0.0.2.jar Just Enough Items {jei@6.0.0.2 COMMON_SETUP}
		reap-1.12.2.jar Reap Mod {reap@1.12.2 COMMON_SETUP}
		essentials-1.15.2-2.7.0.jar Essentials {essentials@1.15.2-2.7.0 COMMON_SETUP}
		Xaeros_Minimap_FP20.1.0_Forge_1.15.2.jar Xaero's Minimap Fair-Play {xaerominimap@20.1.0 COMMON_SETUP}
		PeacefulSurface-1.15.2-v2b.jar PeacefulSurface {peacefulsurface@1.15.2-v2b COMMON_SETUP}
		ShulkerTooltip-1.9.2.jar Shulker Tooltip {shulkertooltip@1.9.2 COMMON_SETUP}
		XaerosWorldMap_1.5.4_Forge_1.15.2.jar Xaero's World Map {xaeroworldmap@1.5.4 COMMON_SETUP}
		LightOverlay-4.2.jar Light Overlay Forge {lightoverlay-forge@4.2 COMMON_SETUP}
		Controlling-6.1.1.jar Controlling {controlling@6.1.1 COMMON_SETUP}
		ClothConfig2-2.0.jar Cloth Config Forge v2 API {cloth-config2@2.0 COMMON_SETUP}
		ReAuth-1.14-3.8.0.jar ReAuth {reauth@3.8.0 COMMON_SETUP}
		OreExcavation-1.7.151.jar Ore Excavation {oreexcavation@NONE COMMON_SETUP}
		snowundertrees-1.15.1-v1.0.jar Snow Under Trees {snowundertrees@v1.0 COMMON_SETUP}
		randompatches-1.15.2-1.21.1.0.jar RandomPatches {randompatches@1.15.2-1.21.1.0 COMMON_SETUP}
		vanilladeathchest-1.15.2-1.10.3.5.jar VanillaDeathChest {vanilladeathchest@1.15.2-1.10.3.5 COMMON_SETUP}
		noRecipeBook_v1.5.2formc1.15.2.jar No Recipe Book {norecipebook@1.5.2 COMMON_SETUP}
		Hwyla-forge-1.10.8-B72_1.15.2.jar Waila {waila@version COMMON_SETUP}
		SnowRealMagic-1.15.2-1.7.2.jar Snow! Real Magic! {snowrealmagic@1.7.2 COMMON_SETUP}
		Kiwi-1.15.2-2.6.5.jar Kiwi {kiwi@2.6.5 COMMON_SETUP}
		strongfarmland-1.15.2-1.0.0.jar Stronger Farmland Mod {strongfarmland@1.15.2-1.0.0 COMMON_SETUP}
		forge-1.15.2-31.1.0-universal.jar Forge {forge@31.1.0 COMMON_SETUP}
		FastLeafDecay-v20.jar FastLeafDecay {fastleafdecay@v20 COMMON_SETUP}
		SoundFilters-0.13_for_1.15.2.jar Sound Filters {soundfilters@0.13_for_1.15.2 COMMON_SETUP}
		ServerTabInfo-1.15.2-1.2.6.jar Server Tab Info {servertabinfo@1.2.6 COMMON_SETUP}
		CraftingTweaks_1.15.1-11.0.0.jar Crafting Tweaks {craftingtweaks@11.0.0 COMMON_SETUP}
		BetterAdvancements-1.15.2-0.1.0.96.jar Better Advancements {betteradvancements@0.1.0.96 COMMON_SETUP}
	Kiwi Modules: 
		kiwi:contributors
		snowrealmagic:snowrealmagic
	Launched Version: forge-31.1.0
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1050 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 442.59, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	CPU: 4x Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz
	OptiFine Version: OptiFine_1.15.2_HD_U_G1_pre9
	OptiFine Build: 20200223-095745
	Render Distance Chunks: 13
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 442.59
	OpenGlRenderer: GeForce GTX 1050 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4 ]</br>

### Mod Version
[ BiomesOPlenty-1.15.2-10.0.0.345-universal ]</br>
![Cattura](https://user-images.githubusercontent.com/38371792/76741802-6feca800-6770-11ea-9ca6-cd09ac60d5e5.PNG)

**Comment by Adubbz** [comment]
Optifine does not support Forge for 1.15.
