### ISSUE TITLE
Server Unable to Start

### ISSUE THREAD

**Issue by SilverKytten** [Glitchfiend/BiomesOPlenty#1609]
## Bug Report

[When starting the server, it crashes with 
[23:04:11] [Server thread/INFO] [minecraft/MinecraftServer]: Stopping server
[23:04:11] [Server thread/INFO] [minecraft/MinecraftServer]: Saving worlds
[23:04:11] [Server thread/ERROR] [minecraft/MinecraftServer]: Exception stopping the server
java.lang.RuntimeException: The server has failed to initialize correctly due to mod loading errors. Examine the crash report for more details.
        at net.minecraftforge.common.DimensionManager.getWorld(DimensionManager.java:185) ~[?:?] {re:classloading}
        at net.minecraft.server.MinecraftServer.func_71218_a(MinecraftServer.java:1004) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_213211_a(MinecraftServer.java:536) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:568) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.dedicated.DedicatedServer.func_71260_j(DedicatedServer.java:550) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:676) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252] {}
]</br>

### How can the crash be reproduced?

[Run Forge 31.1.63 Server + Biomes O' Plenty

### Crash Report and Logs

[crash-2020-05-17_23.01.59-server.txt](https://github.com/Glitchfiend/BiomesOPlenty/files/4641229/crash-2020-05-17_23.01.59-server.txt)

### Mod Version
[BiomesOPlenty-1.15.2-10.0.0.361-universal]</br>

**Comment by Forstride** [comment]
Update Forge to the recommended version
