### ISSUE TITLE
1.15.2 . Just travelling around the world and crash happened :\ (this is the place where crash comes up https://drive.google.com/file/d/15YuBGbwp75c9umpL1_ZLBRhuOa10fIj-/view?usp=sharing)

### ISSUE THREAD

**Issue by BardinTheDwarf** [Glitchfiend/BiomesOPlenty#1632]
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 29.06.20 22:10
Description: Feature placement

java.lang.NullPointerException: Feature placement
	at net.minecraft.world.gen.feature.TreeFeature.func_225557_a_(TreeFeature.java:18) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.feature.TreeFeature.func_225557_a_(TreeFeature.java:12) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.feature.AbstractTreeFeature.func_212245_a(AbstractTreeFeature.java:165) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.feature.AbstractTreeFeature.func_212245_a(AbstractTreeFeature.java:31) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.feature.ConfiguredFeature.func_222734_a(SourceFile:53) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.feature.MultipleWithChanceRandomFeature.func_212245_a(SourceFile:25) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.feature.MultipleWithChanceRandomFeature.func_212245_a(SourceFile:13) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.feature.ConfiguredFeature.func_222734_a(SourceFile:53) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.placement.Placement.lambda$place$0(Placement.java:77) ~[?:?] {re:classloading}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:?] {}
	at java.util.stream.IntPipeline$4$1.accept(IntPipeline.java:250) ~[?:?] {}
	at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:110) ~[?:?] {}
	at java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:693) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:?] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:?] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] {}
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:?] {}
	at net.minecraft.world.gen.placement.Placement.func_214998_a(Placement.java:76) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.placement.ConfiguredPlacement.func_215093_a(SourceFile:36) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.feature.DecoratedFeature.func_212245_a(SourceFile:21) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.feature.DecoratedFeature.func_212245_a(SourceFile:14) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.feature.ConfiguredFeature.func_222734_a(SourceFile:53) ~[?:?] {re:classloading}
	at net.minecraft.world.biome.Biome.func_203608_a(Biome.java:281) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.gen.ChunkGenerator.func_202092_b(ChunkGenerator.java:103) ~[?:?] {re:classloading}
	at net.minecraft.world.chunk.ChunkStatus.lambda$static$9(ChunkStatus.java:74) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.chunk.ChunkStatus.func_223198_a(ChunkStatus.java:195) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ChunkManager.lambda$null$18(ChunkManager.java:518) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-2.0.24.jar:?] {re:classloading,re:classloading}
	at net.minecraft.world.server.ChunkManager.lambda$func_223156_b$20(ChunkManager.java:516) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:966) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:940) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456) ~[?:?] {}
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter.func_219083_b(SourceFile:58) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213148_e(SourceFile:83) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213145_a(SourceFile:123) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.run(SourceFile:91) ~[?:?] {re:classloading}
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.world.gen.feature.TreeFeature.func_225557_a_(TreeFeature.java:18)
	at net.minecraft.world.gen.feature.TreeFeature.func_225557_a_(TreeFeature.java:12)
	at net.minecraft.world.gen.feature.AbstractTreeFeature.func_212245_a(AbstractTreeFeature.java:165)
	at net.minecraft.world.gen.feature.AbstractTreeFeature.func_212245_a(AbstractTreeFeature.java:31)
	at net.minecraft.world.gen.feature.ConfiguredFeature.func_222734_a(SourceFile:53)
	at net.minecraft.world.gen.feature.MultipleWithChanceRandomFeature.func_212245_a(SourceFile:25)
	at net.minecraft.world.gen.feature.MultipleWithChanceRandomFeature.func_212245_a(SourceFile:13)
	at net.minecraft.world.gen.feature.ConfiguredFeature.func_222734_a(SourceFile:53)
	at net.minecraft.world.gen.placement.Placement.lambda$place$0(Placement.java:77)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.IntPipeline$4$1.accept(IntPipeline.java:250)
	at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:110)
	at java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:693)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at net.minecraft.world.gen.placement.Placement.func_214998_a(Placement.java:76)
	at net.minecraft.world.gen.placement.ConfiguredPlacement.func_215093_a(SourceFile:36)
	at net.minecraft.world.gen.feature.DecoratedFeature.func_212245_a(SourceFile:21)
	at net.minecraft.world.gen.feature.DecoratedFeature.func_212245_a(SourceFile:14)
	at net.minecraft.world.gen.feature.ConfiguredFeature.func_222734_a(SourceFile:53)

-- Feature --
Details:
	Id: minecraft:decorated
	Description: < DecoratedFeature [minecraft:decorated] >
Stacktrace:
	at net.minecraft.world.biome.Biome.func_203608_a(Biome.java:281)

-- Generation --
Details:
	CenterX: 30
	CenterZ: -69
	Step: VEGETAL_DECORATION
	Seed: 1109694564253586039
	Biome: druidcraft:darkwood_forest
Stacktrace:
	at net.minecraft.world.gen.ChunkGenerator.func_202092_b(ChunkGenerator.java:103)
	at net.minecraft.world.chunk.ChunkStatus.lambda$static$9(ChunkStatus.java:74)
	at net.minecraft.world.chunk.ChunkStatus.func_223198_a(ChunkStatus.java:195)

-- Chunk to be generated --
Details:
	Location: 30,-69
	Position hash: -296352743394
	Generator: biomesoplenty.common.world.ChunkGeneratorOverworldBOP@729f18ed
Stacktrace:
	at net.minecraft.world.server.ChunkManager.lambda$null$18(ChunkManager.java:518)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.world.server.ChunkManager.lambda$func_223156_b$20(ChunkManager.java:516)
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:966)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:940)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456)
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter.func_219083_b(SourceFile:58)
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213148_e(SourceFile:83)
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213145_a(SourceFile:123)
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.run(SourceFile:91)

-- Affected level --
Details:
	All players: 1 total; [ServerPlayerEntity['RENDOCH'/60, l='Lands of Chugs', x=664.87, y=68.00, z=-881.58]]
	Chunk stats: ServerChunkCache: 4302
	Level dimension: DimensionType{minecraft:overworld}
	Level name: Lands of Chugs
	Level seed: -1895249916586302937
	Level generator: ID 07 - biomesoplenty, ver 0. Features enabled: true
	Level generator options: {}
	Level spawn location: World: (112,73,224), Chunk: (at 0,4,0 in 7,14; contains blocks 112,0,224 to 127,255,239), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 981598 game time, 1251313 day time
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 16209 (now: false), thunder time: 62181 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:852)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:114)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:637)
	at java.lang.Thread.run(Thread.java:748)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_251, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 10535108448 bytes (10047 MB) / 14797504512 bytes (14112 MB) up to 15032385536 bytes (14336 MB)
	CPUs: 8
	JVM Flags: 12 total; -Xmx16G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -XX:ConcGCThreads=2 -XX:ParallelGCThreads=8 -Xmx14336M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M
	ModLauncher: 5.1.0+69+master.79f13f7
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.2.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.2.9.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.9.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.1.1-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.2.9.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.9.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.15.2-31.2.9.jar fml TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.3.jar mixinbootstrap TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.3.jar mixin PLUGINSERVICE 
		/MixinBootstrap-1.0.3.jar mixinbootstrap PLUGINSERVICE 
	FML: 31.2
	Forge: net.minecraftforge:31.2.9
	FML Language Providers: 
		javafml@31.2
		minecraft@1
	Mod List: 
		glasscutter-1.0.1-1.15.2.jar Glasscutter {glasscutter@1.0.1 DONE}
		doubledoors_1.15-2.0.jar Double Doors {doubledoors@2.0 DONE}
		torchslabmod-1.15.2_v1.6.13.jar Torch Slab Mod {torchslabmod@1.6.13 DONE}
		NetherPortalFix_1.15.2-6.0.2.jar NetherPortalFix {netherportalfix@6.0.2 DONE}
		flamboyant-2.0.1.jar Flamboyant {flamboyant@2.0.1 DONE}
		XPFromHarvest-1.15.2-1.2.0.jar XP From Harvest {xpfromharvest@1.2.0 DONE}
		mining-helmet-1.15.2-1.0.8.jar Mining Helmet {mining_helmet@1.0.8 DONE}
		berry_good-2.0.0.jar Berry Good {berry_good@2.0 DONE}
		jei-1.15.2-6.0.0.4.jar Just Enough Items {jei@6.0.0.4 DONE}
		enchantable-1.3.0-1.15.2.jar Enchantable {enchantable@1.3.0 DONE}
		Druidcraft-1.15-0.4.2.jar Druidcraft {druidcraft@0.4.2 DONE}
		SwordBlockingCombat-v1.4-1.15.2.jar Sword Blocking Combat {swordblockingcombat@1.4 DONE}
		AttributeFix-1.15.2-7.0.2.jar AttributeFix {attributefix@7.0.2 DONE}
		the-conjurer-1.15.2-1.0.4.jar The Conjurer {conjurer_illager@1.0.4 DONE}
		Abnormals-Core-1.15.2-1.0.6.jar Abnormals Core {abnormals_core@1.0.6 DONE}
		KiwiBirds-1.1.jar Kiwi Birds {kiwibirds@1.1 DONE}
		Upgrade-Aquatic-1.15.2-v1.6.1.jar Upgrade Aquatic {upgrade_aquatic@1.6.1 DONE}
		Bloomful-1.15.2-1.4.1.jar Bloomful {bloomful@NONE DONE}
		extraboats-1.3.5-1.15.2.jar Extra Boats {extraboats@1.3.5 DONE}
		BowInfinityFix-1.15.2-rv8.jar Bow Infinity Fix {bowinfinityfix@rv8 DONE}
		Waystones_1.15.2-6.0.2.jar Waystones {waystones@6.0.2 DONE}
		Clumps-5.0.2.jar Clumps {clumps@5.0.2 DONE}
		Placebo-1.15.2-3.0.2.jar Placebo {placebo@3.0.2 DONE}
		decorative_blocks-6d.jar Decorative Blocks {decorative_blocks@1.6 DONE}
		Bookshelf-1.15.2-5.6.40.jar Bookshelf {bookshelf@5.6.40 DONE}
		Nimble-1.15.2-0.2.0.jar Nimble {nimble@NONE DONE}
		The-Endergetic-Expansion-1.15.2-v1.3.1.jar The Endergetic Expansion {endergetic@1.3.1 DONE}
		snowundertrees-1.15.2-v1.1.1.jar Snow Under Trees {snowundertrees@v1.1.1 DONE}
		randompatches-1.15.2-1.21.1.2.jar RandomPatches {randompatches@1.15.2-1.21.1.2 DONE}
		grassseeds_1.15-1.2.jar Grass Seeds {grassseeds@1.2 DONE}
		permasomnia_v1.1.1_formc1.15.2.jar Permasomnia {permasomnia@1.1.1 DONE}
		venture-1.0.0-1.15.2.jar Venture {venture@1.0.0 DONE}
		Hwyla-forge-1.10.8-B72_1.15.2.jar Waila {waila@version DONE}
		SnowRealMagic-1.15.2-1.7.5.jar Snow! Real Magic! {snowrealmagic@1.7.5 DONE}
		Kiwi-1.15.2-2.7.1.jar Kiwi {kiwi@2.7.1 DONE}
		potionbundles-1.1.jar PotionBundles {potionbundles@NONE DONE}
		kelpfertilizer_1.15-1.1.jar Kelp Fertilizer {kelpfertilizer@1.1 DONE}
		dismounte_1.15-1.1.jar Dismount Entity {dismountentity@1.1 DONE}
		Swamp-Expansion-1.15.2-v1.7.1.jar Swamp Expansion {swampexpansion@NONE DONE}
		forge-1.15.2-31.2.9-universal.jar Forge {forge@31.2.9 DONE}
		Waddles-1.15.2-0.8.6.jar Waddles {waddles@1.15.2-0.8.6 DONE}
		conduitsprdrowned_1.15-1.1.jar Conduits Prevent Drowned {conduitsprdrowned@1.1 DONE}
		dash-1.15.2-1.0.1.jar Dash {dash@1.0.1 DONE}
		structure-gel-api-1.15.2-1.0.0.jar Structure Gel API {structure_gel@1.0.0 DONE}
		RottenCreatures-1.15.2-0.9.7.jar Rotten Creatures {rotten_creatures@0.9.7 DONE}
		forge-1.15.2-31.2.9-client.jar Minecraft {minecraft@1.15.2 DONE}
		wt_improvements-1.15.2-1.0.0.0.jar Wandering Trader Improvements {wt_improvements@1.15.2-1.0.0.0 DONE}
		repurposedstructures-1.15.2-1.6.0.jar Repurposed Structures {repurposed_structures@1.15.2-1.6.0 DONE}
		EnchantmentDescriptions-1.15.2-2.0.8.jar EnchantmentDescriptions {enchdesc@2.0.8 DONE}
		swingthroughgrass-1.15.2-1.4.0.jar SwingThroughGrass {swingthroughgrass@1.15.2-1.4.0 DONE}
		bspawncontrol_1.15-1.1.jar Better Spawner Control {bspawncontrol@1.1 DONE}
		MouseTweaks-2.13-mc1.15.1.jar Mouse Tweaks {mousetweaks@2.13 DONE}
		BiomesOPlenty-1.15.2-10.0.0.363-universal.jar Biomes O' Plenty {biomesoplenty@1.15.2-10.0.0.363 DONE}
		phosphor-forge-mc1.15.2-0.5.2+build.4.jar Phosphor {phosphor@0.5.2+build.4 DONE}
		edibsgr_1.15.2-2.0.jar Edible Sugar {edibsgr@2.0 DONE}
		Blur-1.1.0-1.jar Blur {blur@1.1.0-1 DONE}
		ShoulderSurfing-1.15.2-1.22.8.jar Shoulder Surfing {shouldersurfing@1.15.2-1.22.8 DONE}
		dungeons-plus-1.15.2-1.0.1.jar Dungeons Plus {dungeons_plus@1.0.1 DONE}
		HerdMentality-1.15.2-1.0.1.jar HerdMentality {herdmentality@1.0.1 DONE}
		forbidden_arcanus-1.15.2-1.4.jar Forbidden & Arcanus {forbidden_arcanus@1.15.2-1.4 DONE}
		rare-ice-0.1.6.jar Rare Ice {rare-ice@0.1.6 DONE}
		Ding-1.15.2-1.1.0.jar Ding {ding@1.1.0 DONE}
		Seeker-Compass-1.15.2.v1.0.0.jar Seeker Compass {seeker_compass@1.0 DONE}
		Atmospheric-1.15.2-1.4.1.jar Atmospheric {atmospheric@1.4.1 DONE}
		curios-FORGE-1.15.2-2.0.2.4.jar Curios API {curios@FORGE-1.15.2-2.0.2.4 DONE}
		Savage-and-Ravage-1.15.2-1.1.3.jar Savage & Ravage {savageandravage@1.1.3 DONE}
		Patchouli-1.15.2-1.2-33.jar Patchouli {patchouli@1.15.2-1.2-33 DONE}
		corail_woodcutter-1.1.3-1.15.2.jar Corail Woodcutter {corail_woodcutter@1.1.3 DONE}
		MaterialMaster-v1.2-1.15.2.jar Material Master {materialmaster@1.2 DONE}
		collective-1.15.2-1.27.jar Collective {collective@1.27 DONE}
		OverpoweredMending-1.15.2-2.0.0+11.jar Overpowered Mending {overpowered_mending@2.0.0+11 DONE}
		cyclepaintings_1.15-1.3.jar Cycle Paintings {cyclepaintings@1.3 DONE}
		recycler-1.15.2-1.1.1.jar Recycler {recycler@1.15.2-1.1.1 DONE}
		FastWorkbench-1.15.1-3.0.0.jar FastWorkbench {fastbench@3.0.0 DONE}
		bunnyboots-1.0.jar BunnyBoots {bunnyboots@1.0 DONE}
		autumnity-1.3.2-1.15.2.jar Autumnity {autumnity@1.3.2 DONE}
		horse_colors-1.15.2-1.2.5.jar Realistic Horse Genetics {horse_colors@1.15.2-1.2.5 DONE}
		AutoRegLib-1.5-40.jar AutoRegLib {autoreglib@1.5-40 DONE}
		Quark-r2.1-243.jar Quark {quark@r2.1-243 DONE}
		StorageDrawers-1.15.2-7.0.2.jar Storage Drawers {storagedrawers@1.15.2-7.0.1 DONE}
		smooth-scrolling-everywhere-1.2.jar Smooth Scrolling Everywhere {smooth-scrolling-everywhere@1.2 DONE}
		DoubleSlabs-1.15-2.4.3.jar Double Slabs {doubleslabs@2.4.3 DONE}
		TaigaAdditions+[0.1.2].jar Taiga Additions {taigaexpansion@0.1.2 DONE}
		FastFurnace-1.15.1-3.0.0.jar FastFurnace {fastfurnace@3.0.0 DONE}
		hunterillager-1.15.2-0.7.1-bugfix.jar HunterIllager {hunterillager@0.7.1 DONE}
		wandering_trapper-1.15.2-0.1.1.jar Wandering Trapper {wandering_trapper@1.15.2-0.1.1 DONE}
		AppleSkin-mc1.15.2-forge-1.0.14.jar AppleSkin {appleskin@1.0.14 DONE}
		cherishedworlds-FORGE-1.15.2-3.0.jar Cherished Worlds {cherishedworlds@FORGE-1.15.2-3.0 DONE}
		simplesweep_MC1.15.2_1.1.jar Simple Sweep {simplesweep@1.15.2_1.1 DONE}
		Charm-1.15.2-1.5.9.jar Charm {charm@1.15.2-1.5.9 DONE}
		incubation-1.0.4-1.15.2.jar Incubation {incubation@1.0.4 DONE}
		FastLeafDecay-v22.jar FastLeafDecay {fastleafdecay@v22 DONE}
		CosmeticArmorReworked-1.15.2-v3a.jar CosmeticArmorReworked {cosmeticarmorreworked@1.15.2-v3a DONE}
		CleanView-1.15.2-v1a.jar CleanView {cleanview@1.15.2-v1a DONE}
		SoundFilters-0.13_for_1.15.2.jar Sound Filters {soundfilters@0.13_for_1.15.2 DONE}
		bambootiful-1.15.2-1.1.3.jar Bambootiful {bambootiful@1.1.3 DONE}
		BetterAdvancements-1.15.2-0.1.0.99.jar Better Advancements {betteradvancements@0.1.0.99 DONE}
	Kiwi Modules: 
		kiwi:contributors
		kiwi:data
		snowrealmagic:snowrealmagic
	Player Count: 1 / 8; [ServerPlayerEntity['RENDOCH'/60, l='Lands of Chugs', x=664.87, y=68.00, z=-881.58]]
	Data Packs: mod:recycler (incompatible), mod:horse_colors, mod:betteradvancements (incompatible), mod:forbidden_arcanus, mod:waystones (incompatible), mod:storagedrawers (incompatible), mod:taigaexpansion, mod:decorative_blocks, vanilla, mod:glasscutter, mod:doubledoors (incompatible), mod:torchslabmod, mod:netherportalfix (incompatible), mod:flamboyant (incompatible), mod:xpfromharvest, mod:mining_helmet (incompatible), mod:berry_good (incompatible), mod:jei (incompatible), mod:enchantable (incompatible), mod:druidcraft, mod:swordblockingcombat, mod:attributefix (incompatible), mod:conjurer_illager, mod:abnormals_core, mod:kiwibirds, mod:upgrade_aquatic (incompatible), mod:bloomful (incompatible), mod:extraboats, mod:bowinfinityfix (incompatible), mod:clumps (incompatible), mod:placebo (incompatible), mod:bookshelf (incompatible), mod:nimble, mod:endergetic (incompatible), mod:snowundertrees (incompatible), mod:randompatches (incompatible), mod:grassseeds (incompatible), mod:permasomnia, mod:venture, mod:waila (incompatible), mod:snowrealmagic, mod:kiwi, mod:potionbundles (incompatible), mod:kelpfertilizer (incompatible), mod:dismountentity (incompatible), mod:swampexpansion (incompatible), mod:forge (incompatible), mod:waddles (incompatible), mod:conduitsprdrowned (incompatible), mod:dash (incompatible), mod:structure_gel, mod:rotten_creatures, mod:wt_improvements, mod:repurposed_structures, mod:enchdesc (incompatible), mod:swingthroughgrass (incompatible), mod:bspawncontrol (incompatible), mod:mousetweaks (incompatible), mod:biomesoplenty, mod:phosphor, mod:edibsgr (incompatible), mod:blur (incompatible), mod:shouldersurfing (incompatible), mod:dungeons_plus, mod:herdmentality (incompatible), mod:rare-ice (incompatible), mod:ding (incompatible), mod:seeker_compass (incompatible), mod:atmospheric, mod:curios (incompatible), mod:savageandravage, mod:patchouli (incompatible), mod:corail_woodcutter, mod:materialmaster, mod:collective (incompatible), mod:overpowered_mending (incompatible), mod:cyclepaintings (incompatible), mod:fastbench (incompatible), mod:bunnyboots (incompatible), mod:autumnity, mod:autoreglib (incompatible), mod:quark, mod:smooth-scrolling-everywhere (incompatible), mod:doubleslabs, mod:fastfurnace (incompatible), mod:hunterillager, mod:wandering_trapper, mod:appleskin (incompatible), mod:cherishedworlds (incompatible), mod:simplesweep (incompatible), mod:charm (incompatible), mod:incubation, mod:fastleafdecay, mod:cosmeticarmorreworked (incompatible), mod:cleanview (incompatible), mod:soundfilters (incompatible), mod:bambootiful (incompatible)
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'

**Comment by Forstride** [comment]
This has nothing to do with BOP.

> Step: VEGETAL_DECORATION
> Seed: 1109694564253586039
> Biome: druidcraft:darkwood_forest

**Comment by BardinTheDwarf** [comment]
That's strange, after i delete mod, and come to this place evreything is fine
