### ISSUE TITLE
(1.7.2) Crash Report

### ISSUE THREAD

**Issue by McKiller5252** [Glitchfiend/BiomesOPlenty#167]
http://pastebin.com/CJyMhm89

Seeing @biomesoplenty.common.eventhandler.entity.TemptEventHandler.onEntitySpawn(TemptEventHandler.java:28) this is the problem

**Comment by alpharulesirulee** [comment]
---- Minecraft Crash Report ----
// Ooh. Shiny.

Time: 1/10/15 12:01 PM
Description: Exception preparing structure feature

java.lang.RuntimeException: StructureComponent "bettervillages.ComponentBetterVillageTorch" missing ID Mapping, Modder see MapGenStructureIO
	at net.minecraft.world.gen.structure.StructureComponent.func_143010_b(StructureComponent.java:39)
	at net.minecraft.world.gen.structure.StructureStart.func_143021_a(StructureStart.java:80)
	at net.minecraft.world.gen.structure.MapGenStructure.func_143026_a(MapGenStructure.java:278)
	at net.minecraft.world.gen.structure.MapGenStructure.func_151538_a(MapGenStructure.java:42)
	at net.minecraft.world.gen.MapGenBase.func_151539_a(SourceFile:30)
	at net.minecraft.world.gen.ChunkProviderGenerate.func_73154_d(ChunkProviderGenerate.java:221)
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:166)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:125)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:95)
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:193)
	at net.minecraft.world.World.func_72964_e(World.java:417)
	at net.minecraft.world.World.func_147439_a(World.java:343)
	at net.minecraft.world.World.func_147437_c(World.java:363)
	at biomesoplenty.common.world.WorldProviderSurfaceBOP.getTopBlockCoord(WorldProviderSurfaceBOP.java:42)
	at biomesoplenty.common.world.WorldProviderSurfaceBOP.func_76566_a(WorldProviderSurfaceBOP.java:14)
	at net.minecraft.world.WorldServer.func_73052_b(WorldServer.java:759)
	at net.minecraft.world.WorldServer.func_72963_a(WorldServer.java:726)
	at WorldServerOF.func_72963_a(WorldServerOF.java:69)
	at net.minecraft.world.World.<init>(World.java:258)
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:96)
	at WorldServerOF.<init>(WorldServerOF.java:58)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:64)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:152)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:374)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:670)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.world.gen.structure.StructureComponent.func_143010_b(StructureComponent.java:39)
	at net.minecraft.world.gen.structure.StructureStart.func_143021_a(StructureStart.java:80)
	at net.minecraft.world.gen.structure.MapGenStructure.func_143026_a(MapGenStructure.java:278)

-- Feature being prepared --
Details:
	Is feature chunk: True
	Chunk location: 11,16
	Chunk pos hash: 68719476747
	Structure type: biomesoplenty.common.eventhandler.world.BOPMapGenVillageEventHandler
Stacktrace:
	at net.minecraft.world.gen.structure.MapGenStructure.func_151538_a(MapGenStructure.java:42)
	at net.minecraft.world.gen.MapGenBase.func_151539_a(SourceFile:30)
	at net.minecraft.world.gen.ChunkProviderGenerate.func_73154_d(ChunkProviderGenerate.java:221)

-- Chunk to be generated --
Details:
	Location: 3,11
	Position hash: 47244640259
	Generator: RandomLevelSource
Stacktrace:
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:166)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:125)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:95)
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:193)
	at net.minecraft.world.World.func_72964_e(World.java:417)

-- Requested block coordinates --
Details:
	Found chunk: true
	Location: World: (60,64,190), Chunk: (at 12,4,14 in 3,11; contains blocks 48,0,176 to 63,255,191), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
Stacktrace:
	at net.minecraft.world.World.func_147439_a(World.java:343)
	at net.minecraft.world.World.func_147437_c(World.java:363)
	at biomesoplenty.common.world.WorldProviderSurfaceBOP.getTopBlockCoord(WorldProviderSurfaceBOP.java:42)
	at biomesoplenty.common.world.WorldProviderSurfaceBOP.func_76566_a(WorldProviderSurfaceBOP.java:14)
	at net.minecraft.world.WorldServer.func_73052_b(WorldServer.java:759)
	at net.minecraft.world.WorldServer.func_72963_a(WorldServer.java:726)
	at WorldServerOF.func_72963_a(WorldServerOF.java:69)

-- Affected level --
Details:
	Level name: New World
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 3 Drop: 0
	Level seed: -8264194260996663804
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.world.World.<init>(World.java:258)
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:96)
	at WorldServerOF.<init>(WorldServerOF.java:58)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:64)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:152)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:374)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:670)

-- System Details --
Details:
	Minecraft Version: 1.7.2
	Operating System: Windows 8 (x86) version 6.2
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 197902664 bytes (188 MB) / 341590016 bytes (325 MB) up to 523501568 bytes (499 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx512M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP v9.03 FML v7.2.217.1147 Minecraft Forge 10.12.2.1147 Optifine OptiFine_1.7.2_HD_U_B7 11 mods loaded, 11 mods active
	mcp{9.03} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	FML{7.2.217.1147} [Forge Mod Loader] (forge-1.7.2-10.12.2.1147.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	Forge{10.12.2.1147} [Minecraft Forge] (forge-1.7.2-10.12.2.1147.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	TooManyItems{1.7.2} [TooManyItems] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	BattleTowers{1.4.8} [Battle Towers] (BattleTowers-1.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	bettervillages{0.2} [Better Villages Mod] (Better-Villages-Mod-1.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	BiomesOPlenty{2.0.2} [Biomes O' Plenty] (BiomesOPlenty-1.7.2-2.0.2.932-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	customnpcs{1.7.2-2} [CustomNpcs] (CustomNPCs_1.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	examplemod{1.0} [examplemod] (herobrinemod-3.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	herobrinemod{3.6} [The Herobrine Mod] (herobrinemod-3.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	voxelmap{1.7.2} [VoxelMap] (voxelmap-1.7.2-1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

plz help

**Comment by Yijare** [comment]
Get to Better VillageMods and tell them thier mod is broken.

**Comment by alpharulesirulee** [comment]
btw i removed it but it crashed out of nowhere at world load

---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 1/10/15 12:56 PM
Description: Exception preparing structure feature

java.lang.RuntimeException: StructureComponent "bettervillages.ComponentBetterVillageTorch" missing ID Mapping, Modder see MapGenStructureIO
	at net.minecraft.world.gen.structure.StructureComponent.func_143010_b(StructureComponent.java:39)
	at net.minecraft.world.gen.structure.StructureStart.func_143021_a(StructureStart.java:80)
	at net.minecraft.world.gen.structure.MapGenStructure.func_143026_a(MapGenStructure.java:278)
	at net.minecraft.world.gen.structure.MapGenStructure.func_151538_a(MapGenStructure.java:42)
	at net.minecraft.world.gen.MapGenBase.func_151539_a(SourceFile:30)
	at net.minecraft.world.gen.ChunkProviderGenerate.func_73154_d(ChunkProviderGenerate.java:221)
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:166)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:125)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:95)
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:257)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:129)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:152)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:374)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:670)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.world.gen.structure.StructureComponent.func_143010_b(StructureComponent.java:39)
	at net.minecraft.world.gen.structure.StructureStart.func_143021_a(StructureStart.java:80)
	at net.minecraft.world.gen.structure.MapGenStructure.func_143026_a(MapGenStructure.java:278)

-- Feature being prepared --
Details:
	Is feature chunk: True
	Chunk location: -31,-6
	Chunk pos hash: -21474836511
	Structure type: com.piggywiggy3.movillages.handlers.MapGenVillageEventHandler
Stacktrace:
	at net.minecraft.world.gen.structure.MapGenStructure.func_151538_a(MapGenStructure.java:42)
	at net.minecraft.world.gen.MapGenBase.func_151539_a(SourceFile:30)
	at net.minecraft.world.gen.ChunkProviderGenerate.func_73154_d(ChunkProviderGenerate.java:221)

-- Chunk to be generated --
Details:
	Location: -28,1
	Position hash: 8589934564
	Generator: RandomLevelSource
Stacktrace:
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:166)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:125)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:95)
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:257)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:129)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:152)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:374)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:670)

-- System Details --
Details:
	Minecraft Version: 1.7.2
	Operating System: Windows 8 (x86) version 6.2
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 169277424 bytes (161 MB) / 323989504 bytes (308 MB) up to 523501568 bytes (499 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx512M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP v9.03 FML v7.2.217.1147 Minecraft Forge 10.12.2.1147 Optifine OptiFine_1.7.2_HD_U_B7 9 mods loaded, 9 mods active
	mcp{9.03} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	FML{7.2.217.1147} [Forge Mod Loader] (forge-1.7.2-10.12.2.1147.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	Forge{10.12.2.1147} [Minecraft Forge] (forge-1.7.2-10.12.2.1147.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	TooManyItems{1.7.2} [TooManyItems] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	BattleTowers{1.4.8} [Battle Towers] (BattleTowers-1.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	bettervillages{0.2} [Better Villages Mod] (Better-Villages-Mod-1.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	customnpcs{1.7.2-2} [CustomNpcs] (CustomNPCs_1.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	movillages{1.1.0} [Mo' Villages] (MoVillages-1.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	voxelmap{1.7.2} [VoxelMap] (voxelmap-1.7.2-1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by alpharulesirulee** [comment]
(BiomesOPlenty caused the problem but i removed it it still crashes)

**Comment by Yulife** [comment]
Holy necropost.

**Comment by alpharulesirulee** [comment]
sorry about necropost i fixed it they were all caused by biomesoplenty and mo villages mod
i removed them and that fixed it
