### ISSUE TITLE
NoSuchElementException while Tesselating block model

### ISSUE THREAD

**Issue by 0xfeeddeadbeef** [Glitchfiend/BiomesOPlenty#1692]
## Bug Report

The game crashes with `java.util.NoSuchElementException: No value present` when spawning in a snowy biome (I'm guessing snow is to blame?)

~~OptiFine+OptiForge is involved.~~ Update: occurs without OptiFine.

### How can the crash be reproduced?

Can't be reproduced reliably.

1. Create a new world with Biones O' Plenty world generator and this seed: `-5029890764784010342`
2. Wait for the world to generate
3. Look to the right (That's where snowy mountain is located)
4. There is a ~~high~~ probability that the game will crash.

### Crash Report and Logs

<details>
  <summary>Click to expand: crash-2020-10-06_13.24.59-client.txt</summary>

```
---- Minecraft Crash Report ----
// My bad.

Time: 10/6/20 1:24 PM
Description: Tesselating block model

java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:135) ~[?:1.8.0_51] {}
	at biomesoplenty.common.util.biome.BiomeUtil.getClientKey(BiomeUtil.java:91) ~[?:?] {re:classloading}
	at biomesoplenty.init.ModBiomes.lambda$setup$1(ModBiomes.java:81) ~[?:?] {re:classloading}
	at biomesoplenty.init.ModBiomes$$Lambda$3199/1736887759.getColor(Unknown Source) ~[?:?] {}
	at net.minecraft.client.world.ClientWorld.func_228321_b_(ClientWorld.java:1082) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.world.ClientWorld.lambda$getBlockColor$7(ClientWorld.java:1058) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.world.ClientWorld$$Lambda$6384/1551759190.getAsInt(Unknown Source) ~[?:?] {}
	at net.minecraft.client.renderer.color.ColorCache.func_228071_a_(SourceFile:43) ~[?:?] {re:classloading}
	at net.minecraft.client.world.ClientWorld.func_225525_a_(ClientWorld.java:1056) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.chunk.ChunkRenderCache.func_225525_a_(ChunkRenderCache.java:160) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.optifine.override.ChunkCacheOF.func_225525_a_(ChunkCacheOF.java:267) ~[?:?] {re:classloading}
	at net.minecraft.world.biome.BiomeColors.func_228359_a_(SourceFile:14) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.biome.BiomeColors.func_228361_b_(SourceFile:22) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.renderer.color.BlockColors.lambda$init$4(BlockColors.java:50) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.color.BlockColors$$Lambda$3646/426014054.getColor(Unknown Source) ~[?:?] {}
	at net.minecraft.client.renderer.color.BlockColors.func_228054_a_(BlockColors.java:92) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.BlockModelRenderer.renderQuadSmooth(BlockModelRenderer.java:253) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.BlockModelRenderer.renderQuadsSmooth(BlockModelRenderer.java:236) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.BlockModelRenderer.renderModelSmooth(BlockModelRenderer.java:147) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.renderModelSmooth(ForgeBlockModelRenderer.java:89) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.BlockModelRenderer.renderModel(BlockModelRenderer.java:101) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.BlockRendererDispatcher.renderModel(BlockRendererDispatcher.java:83) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$ChunkRender$RebuildTask.func_228940_a_(ChunkRenderDispatcher.java:894) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$ChunkRender$RebuildTask.func_225618_a_(ChunkRenderDispatcher.java:721) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.lambda$runTask$1(ChunkRenderDispatcher.java:180) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$$Lambda$6361/601978342.apply(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1624) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.util.Optional.get(Optional.java:135) ~[?:1.8.0_51] {}
	at biomesoplenty.common.util.biome.BiomeUtil.getClientKey(BiomeUtil.java:91) ~[?:?] {re:classloading}
	at biomesoplenty.init.ModBiomes.lambda$setup$1(ModBiomes.java:81) ~[?:?] {re:classloading}
	at biomesoplenty.init.ModBiomes$$Lambda$3199/1736887759.getColor(Unknown Source) ~[?:?] {}
	at net.minecraft.client.world.ClientWorld.func_228321_b_(ClientWorld.java:1082) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.world.ClientWorld.lambda$getBlockColor$7(ClientWorld.java:1058) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.world.ClientWorld$$Lambda$6384/1551759190.getAsInt(Unknown Source) ~[?:?] {}
	at net.minecraft.client.renderer.color.ColorCache.func_228071_a_(SourceFile:43) ~[?:?] {re:classloading}
	at net.minecraft.client.world.ClientWorld.func_225525_a_(ClientWorld.java:1056) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.chunk.ChunkRenderCache.func_225525_a_(ChunkRenderCache.java:160) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.optifine.override.ChunkCacheOF.func_225525_a_(ChunkCacheOF.java:267) ~[?:?] {re:classloading}
	at net.minecraft.world.biome.BiomeColors.func_228359_a_(SourceFile:14) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.biome.BiomeColors.func_228361_b_(SourceFile:22) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.renderer.color.BlockColors.lambda$init$4(BlockColors.java:50) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.color.BlockColors$$Lambda$3646/426014054.getColor(Unknown Source) ~[?:?] {}
	at net.minecraft.client.renderer.color.BlockColors.func_228054_a_(BlockColors.java:92) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.BlockModelRenderer.renderQuadSmooth(BlockModelRenderer.java:253) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.BlockModelRenderer.renderQuadsSmooth(BlockModelRenderer.java:236) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.BlockModelRenderer.renderModelSmooth(BlockModelRenderer.java:147) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.renderModelSmooth(ForgeBlockModelRenderer.java:89) ~[?:?] {re:classloading}
-- Block model being tesselated --
Details:
	Block: Block{minecraft:oak_leaves}[distance=7,persistent=true]
	Block location: World: (51,64,135), Chunk: (at 3,4,7 in 3,8; contains blocks 48,0,128 to 63,255,143), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Using AO: true
Stacktrace:
	at net.minecraft.client.renderer.BlockModelRenderer.renderModel(BlockModelRenderer.java:101) ~[?:?] {re:classloading,xf:OptiFine:default}


-- Block being tesselated --
Details:
	Block: Block{minecraft:oak_leaves}[distance=7,persistent=true]
	Block location: World: (51,64,135), Chunk: (at 3,4,7 in 3,8; contains blocks 48,0,128 to 63,255,143), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
Stacktrace:
	at net.minecraft.client.renderer.BlockRendererDispatcher.renderModel(BlockRendererDispatcher.java:83) ~[?:?] {re:classloading,xf:OptiFine:default}


-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['Murtaz'/119, l='ClientLevel', x=70.50, y=64.00, z=162.50]]
	Chunk stats: Client Chunk Cache: 841, 529
	Level dimension: minecraft:overworld
	Level spawn location: World: (65,64,153), Chunk: (at 1,4,9 in 4,9; contains blocks 64,0,144 to 79,255,159), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 282 game time, 282 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:617) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1974) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.lambda$runTask$3(ChunkRenderDispatcher.java:186) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$$Lambda$6415/658232800.accept(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1624) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}


-- System Details --
Details:
	Minecraft Version: 1.16.3
	Minecraft Version ID: 1.16.3
	Operating System: Windows 8.1 Pro (amd64) version 6.3
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3529706176 bytes (3366 MB) / 5368709120 bytes (5120 MB) up to 5368709120 bytes (5120 MB)
	CPUs: 8
	JVM Flags: 11 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xms5120m -Xmx5120m -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:G1HeapRegionSize=32M -XX:MaxGCPauseMillis=50 -XX:+ParallelRefProcEnabled
	ModLauncher: 7.0.1+78+master.e9771d8
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-3.0.3-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.3-34.1.10.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.3-34.1.10.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.3-34.1.10.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.3-34.1.10.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/preview_OptiFine_1.16.3_HD_U_G4_pre1.jar OptiFine TRANSFORMATIONSERVICE 
		/OptiForge-MC1.16.3-0.3.3.jar optiforge TRANSFORMATIONSERVICE 
		/forge-1.16.3-34.1.10.jar fml TRANSFORMATIONSERVICE 
		/OptiForge-MC1.16.3-0.3.3.jar FakeOptiFine TRANSFORMATIONSERVICE 
		/OptiForge-MC1.16.3-0.3.3.jar optiforgewrapper TRANSFORMATIONSERVICE 
	FML: 34.1
	Forge: net.minecraftforge:34.1.10
	FML Language Providers: 
		javafml@34.1
		minecraft@1
	Mod List: 
		forge-1.16.3-34.1.10-client.jar Minecraft {minecraft@1.16.3 DONE}
		OptiForge-MC1.16.3-0.3.3.jar OptiForge {optiforge@0.3.3 DONE}
		repurposed_structures-1.16.3-2.2.3.jar Repurposed Structures {repurposed_structures@1.16.3-2.2.3 DONE}
		forgemod_VoxelMap-1.10.11_for_1.16.3.jar VoxelMap {voxelmap@1.10.11 DONE}
		forge-1.16.3-34.1.10-universal.jar Forge {forge@34.1.10 DONE}
		Aquaculture-1.16.3-2.1.1.jar Aquaculture 2 {aquaculture@1.16.3-2.1.1 DONE}
		BiomesOPlenty-1.16.3-12.0.0.404-universal.jar Biomes O' Plenty {biomesoplenty@1.16.3-12.0.0.404 DONE}
	Crash Report UUID: fc01f40d-6142-4fda-966b-7b7601762087
	Launched Version: 1.16.3-forge-34.1.10
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: ~~ERROR~~ IllegalStateException: Rendersystem called from wrong thread
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, mod_resources, file/VanillaTweaks_r285058.zip, file/VoxelMap-ThinFrame.zip (incompatible)
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-4771 CPU @ 3.50GHz
	OptiFine Version: OptiFine_1.16.3_HD_U_G4_pre1
	OptiFine Build: 20200924-111308
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: (internal)
	OpenGlVersion: 4.6.0 NVIDIA 456.55
	OpenGlRenderer: GeForce GTX 1050 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8
```
</details>

### Mod Version

1.16.3-12.0.0.404

~~OptiFine: preview_OptiFine_1.16.3_HD_U_G4_pre1.jar~~
~~OptiForge: OptiForge-MC1.16.3-0.3.3.jar~~

**Comment by Forstride** [comment]
I'm not sure why you're using OptiForge when OptiFine 1.16.3 is compatible with Forge.  Anyway, this is an OptiFine issue and there's almost certainly nothing we can do about it.

**Comment by 0xfeeddeadbeef** [comment]
@Forstride Sorry for misleading you. Re-open the issue, please; I've just tested it **without** OptiFine+OptiForge, and it still crashes:

<details>
  <summary>Click to expand: crash-2020-10-06_15.10.27-client.txt</summary>

```
---- Minecraft Crash Report ----
// I feel sad now :(

Time: 10/6/20 3:10 PM
Description: Tesselating liquid in world

java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:135) ~[?:1.8.0_51] {}
	at biomesoplenty.common.util.biome.BiomeUtil.getClientKey(BiomeUtil.java:91) ~[?:?] {re:classloading}
	at biomesoplenty.init.ModBiomes.lambda$setup$2(ModBiomes.java:94) ~[?:?] {re:classloading}
	at biomesoplenty.init.ModBiomes$$Lambda$3128/986309258.getColor(Unknown Source) ~[?:?] {}
	at net.minecraft.client.world.ClientWorld.func_228321_b_(ClientWorld.java:752) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.world.ClientWorld.lambda$getBlockColor$7(ClientWorld.java:734) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.world.ClientWorld$$Lambda$5977/169475719.getAsInt(Unknown Source) ~[?:?] {}
	at net.minecraft.client.renderer.color.ColorCache.func_228071_a_(SourceFile:43) ~[?:?] {re:classloading}
	at net.minecraft.client.world.ClientWorld.func_225525_a_(ClientWorld.java:733) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.chunk.ChunkRenderCache.func_225525_a_(SourceFile:137) ~[?:?] {re:classloading}
	at net.minecraft.world.biome.BiomeColors.func_228359_a_(SourceFile:14) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.biome.BiomeColors.func_228363_c_(SourceFile:26) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraftforge.fluids.FluidAttributes$Water.getColor(FluidAttributes.java:446) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.FluidBlockRenderer.func_228796_a_(FluidBlockRenderer.java:75) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_228794_a_(BlockRendererDispatcher.java:74) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$ChunkRender$RebuildTask.func_228940_a_(ChunkRenderDispatcher.java:512) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$ChunkRender$RebuildTask.func_225618_a_(ChunkRenderDispatcher.java:449) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.lambda$runTask$1(ChunkRenderDispatcher.java:118) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$$Lambda$5994/1511931954.apply(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1624) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.util.Optional.get(Optional.java:135) ~[?:1.8.0_51] {}
	at biomesoplenty.common.util.biome.BiomeUtil.getClientKey(BiomeUtil.java:91) ~[?:?] {re:classloading}
	at biomesoplenty.init.ModBiomes.lambda$setup$2(ModBiomes.java:94) ~[?:?] {re:classloading}
	at biomesoplenty.init.ModBiomes$$Lambda$3128/986309258.getColor(Unknown Source) ~[?:?] {}
	at net.minecraft.client.world.ClientWorld.func_228321_b_(ClientWorld.java:752) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.world.ClientWorld.lambda$getBlockColor$7(ClientWorld.java:734) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.world.ClientWorld$$Lambda$5977/169475719.getAsInt(Unknown Source) ~[?:?] {}
	at net.minecraft.client.renderer.color.ColorCache.func_228071_a_(SourceFile:43) ~[?:?] {re:classloading}
	at net.minecraft.client.world.ClientWorld.func_225525_a_(ClientWorld.java:733) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.chunk.ChunkRenderCache.func_225525_a_(SourceFile:137) ~[?:?] {re:classloading}
	at net.minecraft.world.biome.BiomeColors.func_228359_a_(SourceFile:14) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.biome.BiomeColors.func_228363_c_(SourceFile:26) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraftforge.fluids.FluidAttributes$Water.getColor(FluidAttributes.java:446) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.FluidBlockRenderer.func_228796_a_(FluidBlockRenderer.java:75) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
-- Block being tesselated --
Details:
	Block location: World: (-78,44,160), Chunk: (at 2,2,0 in -5,10; contains blocks -80,0,160 to -65,255,175), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
Stacktrace:
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_228794_a_(BlockRendererDispatcher.java:74) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}


-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['Murtaz'/192, l='ClientLevel', x=21.44, y=82.00, z=114.06]]
	Chunk stats: Client Chunk Cache: 841, 616
	Level dimension: minecraft:overworld
	Level spawn location: World: (65,64,153), Chunk: (at 1,4,9 in 4,9; contains blocks 64,0,144 to 79,255,159), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 6346 game time, 6346 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:447) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1974) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.lambda$runTask$3(ChunkRenderDispatcher.java:122) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$$Lambda$5997/1161854543.accept(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1624) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}


-- System Details --
Details:
	Minecraft Version: 1.16.3
	Minecraft Version ID: 1.16.3
	Operating System: Windows 8.1 Pro (amd64) version 6.3
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2510934240 bytes (2394 MB) / 5368709120 bytes (5120 MB) up to 5368709120 bytes (5120 MB)
	CPUs: 8
	JVM Flags: 11 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xms5120m -Xmx5120m -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:G1HeapRegionSize=32M -XX:MaxGCPauseMillis=50 -XX:+ParallelRefProcEnabled
	ModLauncher: 7.0.1+78+master.e9771d8
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-3.0.3-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.3-34.1.10.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.3-34.1.10.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.3-34.1.10.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.3-34.1.10.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.3-34.1.10.jar fml TRANSFORMATIONSERVICE 
	FML: 34.1
	Forge: net.minecraftforge:34.1.10
	FML Language Providers: 
		javafml@34.1
		minecraft@1
	Mod List: 
		forge-1.16.3-34.1.10-client.jar Minecraft {minecraft@1.16.3 DONE}
		forge-1.16.3-34.1.10-universal.jar Forge {forge@34.1.10 DONE}
		BiomesOPlenty-1.16.3-12.0.0.404-universal.jar Biomes O' Plenty {biomesoplenty@1.16.3-12.0.0.404 DONE}
	Crash Report UUID: cec5da67-7f8a-43b6-a328-16bb0240b95b
	Launched Version: 1.16.3-forge-34.1.10
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: ~~ERROR~~ IllegalStateException: Rendersystem called from wrong thread
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, mod_resources
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-4771 CPU @ 3.50GHz
```

</details>

The only mod that is present is Biomes O' Plenty.

**Comment by Dimmondback** [comment]
Can confirm. Am also having the same crash. Additional information below.
Version: BiomesOPlenty-1.16.3-12.0.0.404-universal
World Seed: 7039716529581469668
Additional World Setting: Bonus Chest = true
How to reproduce: Spawn in and wait ~5s for nearby chunks to load and the crash will occur.

[crash-2020-10-07_02.54.05-client.txt](https://github.com/Glitchfiend/BiomesOPlenty/files/5339708/crash-2020-10-07_02.54.05-client.txt)

**Comment by 0xfeeddeadbeef** [comment]
Thank you!  It no longer crashes. I'm running around in the repro world for a while now, and it's fine. Also, brought back all the other mods.
