### ISSUE TITLE
Crashing during loading new world

### ISSUE THREAD

**Issue by BLXCKONE** [Glitchfiend/BiomesOPlenty#1699]
## Bug Report

Crashing during loading new world.

### How can the crash be reproduced?

Creating new world with Biomes O' Plenty generator.

### Crash Report and Logs

Exit Code: 0 without logs

### Mod Version

BiomesOPlenty-1.16.3-12.0.0.408-universal.jar

**Comment by Forstride** [comment]
There's absolutely nothing to go on here.  It might not have generated a crash report, but you should still have a log from that session, and without it there's really nothing we can do.

**Comment by BLXCKONE** [comment]
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 12.10.20 22:00
Description: Exception initializing level

java.lang.NullPointerException: Exception initializing level
	at net.minecraft.world.biome.provider.BiomeProvider.func_205706_b(SourceFile:142) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_240786_a_(MinecraftServer.java:402) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_240787_a_(MinecraftServer.java:341) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_240800_l__(MinecraftServer.java:305) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:88) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:617) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.lambda$func_240784_a_$0(MinecraftServer.java:229) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer$$Lambda$5188/2118757222.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.world.biome.provider.BiomeProvider.func_205706_b(SourceFile:142) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_240786_a_(MinecraftServer.java:402) ~[?:?] {re:classloading,pl:accesstransformer:B}
-- Affected level --
Details:
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 0
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level name: Nowy świat
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_240787_a_(MinecraftServer.java:341) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_240800_l__(MinecraftServer.java:305) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:88) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:617) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.lambda$func_240784_a_$0(MinecraftServer.java:229) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer$$Lambda$5188/2118757222.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}


-- System Details --
Details:
	Minecraft Version: 1.16.3
	Minecraft Version ID: 1.16.3
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 10541644400 bytes (10053 MB) / 12280922112 bytes (11712 MB) up to 16106127360 bytes (15360 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx15G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 7.0.1+78+master.e9771d8
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-3.0.3-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.3-34.1.17.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.3-34.1.17.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.3-34.1.17.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.3-34.1.17.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine%201.16.3%20HD%20U%20G3%20.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.3-34.1.17.jar fml TRANSFORMATIONSERVICE 
	FML: 34.1
	Forge: net.minecraftforge:34.1.17
	FML Language Providers: 
		javafml@34.1
		minecraft@1
	Mod List: 
		forge-1.16.3-34.1.17-client.jar Minecraft {minecraft@1.16.3 DONE}
		forge-1.16.3-34.1.17-universal.jar Forge {forge@34.1.17 DONE}
		BiomesOPlenty-1.16.3-.jar Biomes O' Plenty {biomesoplenty@1.16.3-12.0.0.405 DONE}
	Crash Report UUID: 4faa091f-9d07-4b83-880c-65ca31e6ed5f
	Player Count: 0 / 8; []
	Data Packs: vanilla, mod:forge, mod:biomesoplenty (incompatible)
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'
	OptiFine Version: OptiFine_1.16.3_HD_U_G3
	OptiFine Build: 20200916-082411
	Render Distance Chunks: 8
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: BSL_v7.2.zip
	OpenGlVersion: 4.6.14736 Compatibility Profile Context 20.9.1 27.20.12029.1000
	OpenGlRenderer: Radeon RX 580 Series
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 8

**Comment by Forstride** [comment]
Try updating OptiFine to the latest preview build, or just remove it if that doesn't work.

**Comment by BLXCKONE** [comment]
Working without Optifine, but I can't imagine a game without shaders :(

**Comment by Stenaven** [comment]
@BLXCKONE your problem might be a render distance that's too high. I got a similar crash/problem when my render distance was very high. Try setting it to 10 chunks and testing that.
