### ISSUE TITLE
The game when I want to create a new World an

### ISSUE THREAD

**Issue by KuroxP** [Glitchfiend/BiomesOPlenty#1712]
## Bug Report

When I press on create new world with "Biomes O' Plenty" the game closes. </br>

### How can the crash be reproduced?

When I press on create new world with "Biomes O' Plenty" the game closes.</br>

### Crash Report and Logs

---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 20/10/20 4:01
Description: Exception initializing level

java.lang.NullPointerException: Exception initializing level
	at net.minecraft.world.biome.provider.BiomeProvider.func_205706_b(SourceFile:142) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_240786_a_(MinecraftServer.java:402) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_240787_a_(MinecraftServer.java:341) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_240800_l__(MinecraftServer.java:305) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:88) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:617) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.lambda$func_240784_a_$0(MinecraftServer.java:229) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer$$Lambda$8108/562682373.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.world.biome.provider.BiomeProvider.func_205706_b(SourceFile:142) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_240786_a_(MinecraftServer.java:402) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A}
-- Affected level --
Details:
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 0
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level name: Bouo
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_240787_a_(MinecraftServer.java:341) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_240800_l__(MinecraftServer.java:305) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:88) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:617) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.lambda$func_240784_a_$0(MinecraftServer.java:229) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer$$Lambda$8108/562682373.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

-- System Details --
Details:
	Minecraft Version: 1.16.3
	Minecraft Version ID: 1.16.3
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1129571360 bytes (1077 MB) / 4294967296 bytes (4096 MB) up to 4294967296 bytes (4096 MB)
	CPUs: 12
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 7.0.1+78+master.e9771d8
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-3.0.3-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.3-34.1.22.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.3-34.1.22.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.3-34.1.22.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.3-34.1.22.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/preview_OptiFine_1.16.3_HD_U_G4_pre2.jar OptiFine TRANSFORMATIONSERVICE 
		/OptiForge-MC1.16.3-0.3.4.jar optiforge TRANSFORMATIONSERVICE 
		/forge-1.16.3-34.1.22.jar fml TRANSFORMATIONSERVICE 
		/OptiForge-MC1.16.3-0.3.4.jar FakeOptiFine TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.5.jar mixinbootstrap TRANSFORMATIONSERVICE 
		/OptiForge-MC1.16.3-0.3.4.jar optiforgewrapper TRANSFORMATIONSERVICE 
	FML: 34.1
	Forge: net.minecraftforge:34.1.22
	FML Language Providers: 
		javafml@34.1
		minecraft@1
	Mod List: 
		forge-1.16.3-34.1.22-client.jar Minecraft {minecraft@1.16.3 DONE}
		mcw-bridges-1.0.4-mc1.16.3.jar Macaw's Bridges {mcwbridges@1.0.4 DONE}
		useful_railroads-1.16.3-1.4.5.32.jar Useful Railroads {usefulrailroads@1.4.5.32 DONE}
		BiomesOPlenty-1.16.3-12.0.0.409-universal.jar Biomes O' Plenty {biomesoplenty@1.16.3-12.0.0.409 DONE}
		dungeons-plus-1.16.3-1.0.3 (1).jar Dungeons Plus {dungeons_plus@1.0.3 DONE}
		jei-1.16.3-7.6.0.49.jar Just Enough Items {jei@7.5.0.43 DONE}
		OptiForge-MC1.16.3-0.3.4.jar OptiForge {optiforge@0.3.4 DONE}
		Enderium+1.0.1.jar Enderium {enderium@1.0.1 DONE}
		mcw-windows-1.0.2-mc1.16.3.jar Macaw's Windows {mcwwindows@1.0.2 DONE}
		caelus-forge-1.16.3-2.0.0.3.jar Caelus API {caelus@1.16.3-2.0.0.3 DONE}
		curios-forge-1.16.3-4.0.2.0.jar Curios API {curios@1.16.3-4.0.2.0 DONE}
		Neat+1.7-24.jar Neat {neat@1.7-24 DONE}
		CoffeeSpawner-1.16.3-7.0.0.jar Coffee Spawner {coffeespawner@1.16.3-7.0.0 DONE}
		Xaeros_Minimap_20.26.0_Forge_1.16.3.jar Xaero's Minimap {xaerominimap@20.26.0 DONE}
		XaerosWorldMap_1.11.0_Forge_1.16.3.jar Xaero's World Map {xaeroworldmap@1.11.0 DONE}
		citadel-1.4.1.jar Citadel {citadel@1.4.1 DONE}
		enderchests-1.16-1.7.3.jar EnderChests {enderchests@1.7.3 DONE}
		netheritehorsearmor-1.4.jar Netherite Horse Armor Mod {netheritehorsearmor@1.4 DONE}
		backpacked-1.6.0-1.16.3.jar Backpacked {backpacked@1.6.0 DONE}
		branders-spawnermod-1.16.3-1.6.7.jar Enhanced Mob Spawners {spawnermod@1.6.7 DONE}
		RingOfEnderchest-1.16.3-1.2.4.jar Ring of Enderchest {ring_of_enderchest@1.2.4 DONE}
		u_team_core-1.16.3-3.1.10.183.jar U Team Core {uteamcore@3.1.10.183 DONE}
		mcw-doors-1.0.1fix-mc1.16.3-1.16.2.jar Macaw's Doors {mcwdoors@1.0.1 DONE}
		mapperbase-1.16.3-2.1.0.1.jar Mapper Base {mapperbase@1.16.3-2.1.0.1 DONE}
		embellishcraft-1.16.3-3.1.0.1.jar EmbellishCraft {embellishcraft@1.16.3-3.1.0.1 DONE}
		embellishcraft-bop-1.16.3-3.1.0.jar EmbellishCraft BoP Addon {embellishcraft-bop@1.16.3-3.1.0 DONE}
		curiouselytra-forge-1.16.3-4.0.0.1.jar Curious Elytra {curiouselytra@1.16.3-4.0.0.1 DONE}
		iceandfire-2.1.0-1.16.3.jar Ice and Fire {iceandfire@2.0.3-1.16.3 DONE}
		Hwyla-Mod-1.16.3.jar Waila {waila@1.10.11-B78_1.16.2 DONE}
		BackTools-1.16.3-10.0.0.jar Back Tools {backtools@10.0.0 DONE}
		walljump-forge-1.16.3-1.3.6.jar Wall-Jump! {walljump@1.16.3-1.3.6 DONE}
		iChunUtil-1.16.3-10.0.0.jar iChunUtil {ichunutil@10.0.0 DONE}
		carryon-1.16.3-1.15.1.7.jar Carry On {carryon@1.15.1.7 DONE}
		forge-1.16.3-34.1.22-universal.jar Forge {forge@34.1.22 DONE}
		shetiphiancore-1.16-3.8.2.jar ShetiPhian-Core {shetiphiancore@3.8.2 DONE}
		CosmeticArmorReworked-1.16.3-v1.jar CosmeticArmorReworked {cosmeticarmorreworked@1.16.3-v1 DONE}
		Upgraded+Netherite+1.16.3+-+1.6.0.jar Upgraded Netherite {upgradednetherite@1.6.0 DONE}
		structure-gel-api-1.16.3-1.4.2.jar Structure Gel API {structure_gel@1.4.2 DONE}
	Crash Report UUID: 157646d0-b44d-4ac4-a577-9cc9a611abc4
	Player Count: 0 / 8; []
	Data Packs: vanilla, mod:mcwbridges (incompatible), mod:usefulrailroads, mod:biomesoplenty (incompatible), mod:dungeons_plus, mod:jei, mod:optiforge (incompatible), mod:enderium, mod:mcwwindows (incompatible), mod:caelus, mod:curios, mod:neat (incompatible), mod:coffeespawner, mod:xaerominimap, mod:xaeroworldmap, mod:citadel (incompatible), mod:enderchests, mod:netheritehorsearmor, mod:backpacked (incompatible), mod:spawnermod (incompatible), mod:ring_of_enderchest (incompatible), mod:uteamcore, mod:mcwdoors, mod:mapperbase (incompatible), mod:embellishcraft (incompatible), mod:embellishcraft-bop (incompatible), mod:curiouselytra, mod:iceandfire (incompatible), mod:waila, mod:backtools, mod:walljump (incompatible), mod:ichunutil, mod:carryon, mod:forge, mod:shetiphiancore, mod:cosmeticarmorreworked (incompatible), mod:upgradednetherite (incompatible), mod:structure_gel
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'
	OptiFine Version: OptiFine_1.16.3_HD_U_G4_pre2
	OptiFine Build: 20201007-190609
	Render Distance Chunks: 14
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: Chocapic13_V8_Ultra.zip
	OpenGlVersion: 4.6.0 NVIDIA 456.71
	OpenGlRenderer: GeForce GTX 1070/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12</br>

### Mod Version
Biomes O' Plenty 1.16.3-12.0.0.409 </br>

**Comment by Forstride** [comment]
See the following: https://github.com/sp614x/optifine/issues/4880

**Comment by KuroxP** [comment]
> See the following: [sp614x/optifine#4880](https://github.com/sp614x/optifine/issues/4880)

Sorry, I didn't see this before my report, hope this issue can be solved in the future
