### ISSUE TITLE
BoP world type breaks dimensions added by mods on dedicated servers

### ISSUE THREAD

**Issue by malte0811** [Glitchfiend/BiomesOPlenty#1718]
### What's the issue you encountered?

Dimensions added by other mods (and probably datapacks) are ignored on dedicated servers if the `biomesoplenty` world type is used. This is probably caused by [this](https://github.com/Glitchfiend/BiomesOPlenty/blob/96c2b21ea2883646440f7d31b972b1dceec36418/src/main/java/biomesoplenty/common/world/BOPDimensionType.java#L59-L65) function ignoring all user-added dimensions. This was noticed on ForgeCraft 1.

### How can the issue be reproduced?

Install BoP for Minecraft 1.16.3 on a dedicated server together with any mod adding a dimension ([example](https://www.curseforge.com/minecraft/mc-mods/advanced-mining-dimension)), or a non-mod datapack doing so. Set the world type to `biomesoplenty`. Run `/forge tps` and notice that the dimension is not shown. Launch the same instance with a different world type (e.g. `default`) and notice that the dimension will be shown.  
Related note: Why does the issue template say "recreating your issue with only Biomes O' Plenty installed"? Do you assume that cross-mod issues do not exist? Alternatively: why are the only existing issue templates for "standalone" installations?

### Mod Version
BiomesOPlenty: 1.16.3-12.0.0.408  
Forge: 34.1.23

**Comment by ConnorTron110** [comment]
Can confirm for ATM 6 on a dedicated server.
Wouldn't class this as a minor bug since it prevents All Dim driven mods from even functioning.

**Comment by Inpaladin** [comment]
This is also an issue in singleplayer, and causes bop to fail to load any save with the bop world type.

**Comment by JacobCoffee** [comment]
All dimensions inc. _**Woot**_ farms 👍

**Comment by ConnorTron110** [comment]
> This is also an issue in singleplayer, and causes bop to fail to load any save with the bop world type.
Yeah ok, ill look into fixing both of these issues since it seems like the mod has gone quiet. No guarantee but ill try my best.

**Comment by Forstride** [comment]
This *should* be fixed now in the latest release, but it'll need further testing

**Comment by ConnorTron110** [comment]
@Forstride Just tested latest version and it seems its fixed. Ive only tested Ratlantis as of now but i will test other mods.

**Comment by godleydemon** [comment]
> @Forstride Just tested latest version and it seems its fixed. Ive only tested Ratlantis as of now but i will test other mods.

Just tested this with ATM6 1.1.9b and it still has the same problem on 1.16.3-12.0.0.412

**Comment by MachinegunMarty** [comment]
Release 1.16.4-forge-35.0.15 server + client
BiomesOPlenty-1.16.4-13.0.0.420-universal.jar
mining_dimension-1.16.4-1.0.1.jar

I added "Advanced Mining Dimensions" to my existing world (and a datapack for mining dimensions called more_ores).
When clicking the teleport block it read: Mining Dimension hasn't been made yet.
It seems that this was a minecraft issue and should be fixed with forge 35.0.15 and mining dimension 1.0.1. 
After 2 server reboots still no mining world.
I removed the datapack and started the server again. Now a mining dimension was made.
I entered the mining world and mined some then exited back to the overworld.
Shut down the server and added the datapack again.

Now the server won't start anymore. 

I removed the datapack - Server won't start
I removed the dimension folder in my world folder - Server won't start
I removed the advanced mining mod - Server won't start

The errors in the log are from biomesoplenty:

[11Nov2020 23:22:27.532] [Server thread/INFO] [biomesoplenty/]: Setting world generator settings to biomesoplenty
[11Nov2020 23:22:27.533] [Server thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: Index: 1, Size: 1
	Index: 4
	Listeners:
		0: HIGH
		1: net.minecraftforge.eventbus.EventBus$$Lambda$2710/793292236@24db8756
		2: NORMAL
		3: net.minecraftforge.eventbus.EventBus$$Lambda$2710/793292236@1a11417d
		4: net.minecraftforge.eventbus.EventBus$$Lambda$2710/793292236@3f4d97c3
		5: net.minecraftforge.eventbus.EventBus$$Lambda$2710/793292236@cee9503
		6: net.minecraftforge.eventbus.EventBus$$Lambda$2710/793292236@747752ff
		7: ASM: invtweaks.InvTweaksMod@53f70d13 onServerAboutToStart(Lnet/minecraftforge/fml/event/server/FMLServerAboutToStartEvent;)V
		8: net.minecraftforge.eventbus.EventBus$$Lambda$2710/793292236@647dffa5
java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.rangeCheck(ArrayList.java:659)
	at java.util.ArrayList.get(ArrayList.java:435)
	at biomesoplenty.common.world.BOPWorldTypeUtil.isUsingBopWorldType(BOPWorldTypeUtil.java:46)
	at biomesoplenty.common.world.BOPWorldTypeUtil.setupForDedicatedServer(BOPWorldTypeUtil.java:101)
	at biomesoplenty.core.BiomesOPlenty.serverStarting(BiomesOPlenty.java:75)
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297)
	at net.minecraftforge.fml.server.ServerLifecycleHooks.handleServerAboutToStart(ServerLifecycleHooks.java:96)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:166)
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:620)
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232)
	at java.lang.Thread.run(Thread.java:748)

[11Nov2020 23:22:27.534] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.rangeCheck(ArrayList.java:659) ~[?:1.8.0_272]
	at java.util.ArrayList.get(ArrayList.java:435) ~[?:1.8.0_272]
	at biomesoplenty.common.world.BOPWorldTypeUtil.isUsingBopWorldType(BOPWorldTypeUtil.java:46) ~[biomesoplenty:?]
	at biomesoplenty.common.world.BOPWorldTypeUtil.setupForDedicatedServer(BOPWorldTypeUtil.java:101) ~[biomesoplenty:?]
	at biomesoplenty.core.BiomesOPlenty.serverStarting(BiomesOPlenty.java:75) ~[biomesoplenty:?]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-3.0.5-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-3.0.5-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.5-service.jar:?]
	at net.minecraftforge.fml.server.ServerLifecycleHooks.handleServerAboutToStart(ServerLifecycleHooks.java:96) ~[forge:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:166) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:620) ~[?:?]
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) ~[?:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_272]

**Comment by MachinegunMarty** [comment]
Found a fix:

https://github.com/AllTheMods/ATM-6/issues/258#issuecomment-723029394

So in short: I edited my server.properties and changed: level-type=biomesoplenty to level-type=default.

Now the server starts again.

**Comment by pupnewfster** [comment]
Just putting this here for reference, https://github.com/MinecraftForge/MinecraftForge/commit/93c00b67d97b4c51dff4c807e29556bf8a9b7548 should allow for a more proper fix.
