### ISSUE TITLE
Exception ticking world

### ISSUE THREAD

**Issue by SenZ01** [Glitchfiend/BiomesOPlenty#1742]
I've been running into this issue a few times now.

```
java.lang.NoClassDefFoundError: net/minecraft/world/World$2
	at net.minecraft.world.World.func_190524_a(World.java:557)
	at net.minecraft.world.World.func_175685_c(World.java:494)
	at net.minecraft.world.World.func_175722_b(World.java:440)
	at net.minecraft.world.World.markAndNotifyBlock(World.java:381)
	at net.minecraft.world.World.func_180501_a(World.java:361)
	at net.minecraft.world.World.func_175656_a(World.java:425)
	at biomesoplenty.common.block.BlockBOPGrass.spreadGrass(BlockBOPGrass.java:302)
	at biomesoplenty.common.block.BlockBOPGrass.func_180650_b(BlockBOPGrass.java:288)
	at net.minecraft.block.Block.func_180645_a(Block.java:508)
	at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:476)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:225)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:279)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

```
```
-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.world.World.func_190524_a(World.java:557)
	at net.minecraft.world.World.func_175685_c(World.java:494)
	at net.minecraft.world.World.func_175722_b(World.java:440)
	at net.minecraft.world.World.markAndNotifyBlock(World.java:381)
	at net.minecraft.world.World.func_180501_a(World.java:361)
	at net.minecraft.world.World.func_175656_a(World.java:425)
	at biomesoplenty.common.block.BlockBOPGrass.spreadGrass(BlockBOPGrass.java:302)
	at biomesoplenty.common.block.BlockBOPGrass.func_180650_b(BlockBOPGrass.java:288)
	at net.minecraft.block.Block.func_180645_a(Block.java:508)
	at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:476)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:225)

```
```
-- Affected level --
Details:
	Level name: WHY
	All players: 1 total; [EntityPlayerMP['SenZ0_'/474, l='WHY', x=146.59, y=72.00, z=907.37]]
	Chunk stats: ServerChunkCache: 374 Drop: 0
	Level seed: -1890616090579318725
	Level generator: ID 07 - OTG, ver 0. Features enabled: true
	Level generator options: OpenTerrainGenerator
	Level spawn location: World: (212,69,1012), Chunk: (at 4,4,4 in 13,63; contains blocks 208,0,1008 to 223,255,1023), Region: (0,1; contains chunks 0,32 to 31,63, blocks 0,0,512 to 511,255,1023)
	Level time: 3887 game time, 3887 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 55783 (now: false), thunder time: 70142 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:279)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)
```
**Please let me know if there is anything i can help with.**

**Comment by SenZ01** [comment]
![2020-11-13_05 52 04](https://user-images.githubusercontent.com/74424517/99101809-6bb5aa80-25dd-11eb-9c14-b5029a92f97c.png)
The last thing i saw before my World Crashed.

**Comment by BugmanBugman** [comment]
Is this 1.12?

**Comment by SenZ01** [comment]
Yes

**Comment by SenZ01** [comment]
> Is this 1.12?

Yes.

**Comment by SenZ01** [comment]
[crash-2020-11-13_06.01.26-server.txt](https://github.com/Glitchfiend/BiomesOPlenty/files/5538894/crash-2020-11-13_06.01.26-server.txt)
**Full Crashlog here**

**Comment by Forstride** [comment]
We do not support 1.12.2, as it says when opening a new issue.
