### ISSUE TITLE
Biomes O' Plenty (biomesoplenty) encountered an error during the load_registries event phase

### ISSUE THREAD

**Issue by xPavelow** [Glitchfiend/BiomesOPlenty#1753]
## Bug Report

Biomes O' Plenty (biomesoplenty) encountered an error during the load_registries event phase

anytime i open the server

[ Include a detailed step by step process for recreating your crash with only Biomes O' Plenty installed. ]</br>

### Crash Report and Logs

---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 12/3/20 4:38 PM
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:85) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:51) ~[forge:?] {re:classloading}
	at net.minecraft.server.Main.main(Main.java:95) ~[?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_221] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_221] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_221] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_221] {}
	at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[forge-1.16.4-35.0.2.jar:35.0] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?] {}
	at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63) [forge-1.16.4-35.0.2.jar:?] {}
	at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60) [forge-1.16.4-35.0.2.jar:?] {}
	at net.minecraftforge.server.ServerMain.main(ServerMain.java:57) [forge-1.16.4-35.0.2.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: main
Stacktrace:
	at biomesoplenty.common.biome.BiomeRegistry.configureTechnicalBiomes(BiomeRegistry.java:149) ~[biomesoplenty:?] {re:classloading}
-- MOD biomesoplenty --
Details:
	Mod File: BiomesOPlenty-1.16.4-13.0.0.422-universal.jar
	Failure message: Biomes O' Plenty (biomesoplenty) encountered an error during the load_registries event phase
		java.lang.NullPointerException: null
	Mod Version: 1.16.4-13.0.0.422
	Mod Issue URL: https://github.com/Glitchfiend/BiomesOPlenty/issues
	Exception message: java.lang.NullPointerException
Stacktrace:
	at biomesoplenty.common.biome.BiomeRegistry.configureTechnicalBiomes(BiomeRegistry.java:149) ~[biomesoplenty:?] {re:classloading}
	at biomesoplenty.init.ModBiomes.registerBiomes(ModBiomes.java:124) ~[biomesoplenty:?] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_64_ModBiomes_registerBiomes_Register.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-3.0.3-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.3-service.jar:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[forge:35.0] {re:classloading}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:111) ~[forge:?] {re:classloading}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:1.8.0_221] {}
	at net.minecraftforge.fml.ModWorkManager$SyncExecutor.driveOne(ModWorkManager.java:56) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.ModWorkManager$DrivenExecutor.drive(ModWorkManager.java:40) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:242) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:229) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:195) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:44) ~[forge:?] {re:classloading}
	at net.minecraft.server.Main.main(Main.java:95) ~[?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_221] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_221] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_221] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_221] {}
	at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[forge-1.16.4-35.0.2.jar:35.0] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?] {}
	at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63) [forge-1.16.4-35.0.2.jar:?] {}
	at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60) [forge-1.16.4-35.0.2.jar:?] {}
	at net.minecraftforge.server.ServerMain.main(ServerMain.java:57) [forge-1.16.4-35.0.2.jar:?] {}

-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_221, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 586677760 bytes (559 MB) / 2147483648 bytes (2048 MB) up to 4294967296 bytes (4096 MB)
	CPUs: 12
	JVM Flags: 12 total; -Xmx4G -Xms2G -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:MaxGCPauseMillis=100 -XX:+DisableExplicitGC -XX:TargetSurvivorRatio=90 -XX:G1NewSizePercent=50 -XX:G1MaxNewSizePercent=80 -XX:G1MixedGCLiveThresholdPercent=35 -XX:+AlwaysPreTouch -XX:+ParallelRefProcEnabled
	ModLauncher: 8.0.6+85+master.325de55
	ModLauncher launch target: fmlserver
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-3.0.3-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.4-35.0.2.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.4-35.0.2.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.4-35.0.2.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.4-35.0.2.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine_1.16.4_HD_U_G5.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.4-35.0.2.jar fml TRANSFORMATIONSERVICE 
	FML: 35.0
	Forge: net.minecraftforge:35.0.2
	FML Language Providers: 
		javafml@35.0
		minecraft@1
	Mod List: 
		forge-1.16.4-35.0.2-server.jar                    |Minecraft                     |minecraft                     |1.16.4              |COMMON_SET|NOSIGNATURE
		mcw-bridges-1.0.4-mc1.16.4.jar                    |Macaw's Bridges               |mcwbridges                    |1.0.4               |COMMON_SET|NOSIGNATURE
		OfflineSkins-1.16.4-v1.jar                        |OfflineSkins                  |offlineskins                  |1.16.4-v1           |COMMON_SET|5e:ed:25:99:e4:44:14:c0:dd:89:c1:a9:4c:10:b5:0d:e4:b1:52:50:45:82:13:d8:d0:32:89:67:56:57:01:53
		guardvillagers-1.16.3-1.1.5.jar                   |Guard Villagers               |guardvillagers                |1.1.5               |COMMON_SET|NOSIGNATURE
		BiomesOPlenty-1.16.4-13.0.0.422-universal.jar     |Biomes O' Plenty              |biomesoplenty                 |1.16.4-13.0.0.422   |VALIDATE  |NOSIGNATURE
		mcw-doors-1.0.1fix-mc1.16.4.jar                   |Macaw's Doors                 |mcwdoors                      |1.0.1               |COMMON_SET|NOSIGNATURE
		Morpheus-1.16.4-4.2.68.jar                        |Morpheus                      |morpheus                      |4.2.68              |COMMON_SET|NOSIGNATURE
		towers_of_the_wild-1.16.4-2.0.1.jar               |Towers Of The Wild            |towers_of_the_wild            |1.16.4-2.0.1        |COMMON_SET|NOSIGNATURE
		TrampleStopper-2.4.7+mc-1.16.4.jar                |Trample Stopper               |tramplestopper                |2.4.7+mc-1.16.4     |COMMON_SET|23:8f:95:0f:65:ec:2e:38:99:79:f4:bc:47:8a:0b:df:29:ef:2d:82:66:20:09:20:02:dc:4a:15:97:45:f8:43
		mcw-windows-1.0.2-mc1.16.4.jar                    |Macaw's Windows               |mcwwindows                    |1.0.2               |COMMON_SET|NOSIGNATURE
		forge-1.16.4-35.0.2-universal.jar                 |Forge                         |forge                         |35.0.2              |COMMON_SET|22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		Waddles-1.16.3-0.8.9.jar                          |Waddles                       |waddles                       |1.16.3-0.8.9        |COMMON_SET|NOSIGNATURE
		extragolems-11.1.6.jar                            |Extra Golems                  |golems                        |11.1.6              |COMMON_SET|NOSIGNATURE
		strawgolem-1.16-1.9.jar                           |Straw Golem                   |strawgolem                    |1.16-1.9            |COMMON_SET|NOSIGNATURE
		FastLeafDecay-v25.jar                             |FastLeafDecay                 |fastleafdecay                 |v25                 |COMMON_SET|NOSIGNATURE
		corpse-1.16.4-1.0.1.jar                           |Corpse                        |corpse                        |1.16.4-1.0.1        |COMMON_SET|NOSIGNATURE
		sit-1.16.2-v1.3.jar                               |Sit                           |sit                           |v1.3                |COMMON_SET|NOSIGNATURE
		earthmobsmod-1.16.4-0.1.2-Beta.jar                |Earth Mobs Mod                |earthmobsmod                  |1.16.4-0.1.2-Beta   |COMMON_SET|NOSIGNATURE
	Crash Report UUID: 4c853e8d-d8ec-403e-be10-9be734b57fd1
### Mod Version
[ Please put the version of the mod you were using here. ]</br>

 BiomesOPlenty-1.16.4-13.0.0.422-universal.jar

**Comment by Forstride** [comment]
Delete your config and let it regenerate a new one

**Comment by xPavelow** [comment]
> Delete your config and let it regenerate a new one

just for biomes o plenty or the entire config folder?

**Comment by Forstride** [comment]
Just for BOP
