### ISSUE TITLE
MC 1.16.5  Crash When Changing "Stone Beach" Toggle to false

### ISSUE THREAD

**Issue by Teralitha** [Glitchfiend/BiomesOPlenty#1866]
## Bug Report
MC 1.16.5 Crash When Changing "Stone Beach" Toggle to false and creating new world.
### How can the crash be reproduced?
I was able to repeat the crash when toggling stone beach between true and false.  Crashes on false.  - Also, you have "wooded wasteland" in the config twice.  One in the main biome list and one in the sub biome list.

### Crash Report and Logs
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 6/5/21 7:46 PM
Description: Exception generating new chunk

java.lang.RuntimeException: Attempted to get unregistered biome ResourceKey[minecraft:worldgen/biome / biomesoplenty:gravel_beach]
	at biomesoplenty.common.util.biome.BiomeUtil.getBiome(BiomeUtil.java:38) ~[?:?] {re:classloading}
	at biomesoplenty.common.util.biome.BiomeUtil.getBiomeId(BiomeUtil.java:58) ~[?:?] {re:classloading}
	at biomesoplenty.common.world.layer.BOPShoreLayer.func_202748_a(BOPShoreLayer.java:97) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.layer.traits.ICastleTransformer.func_215728_a(SourceFile:12) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.layer.traits.IAreaTransformer1.func_202711_b(SourceFile:13) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.layer.traits.IAreaTransformer1$$Lambda$4848/451779965.apply(Unknown Source) ~[?:?] {}
	at net.minecraft.world.gen.area.LazyArea.func_202678_a(SourceFile:26) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.layer.ZoomLayer.func_215728_a(SourceFile:41) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.layer.traits.IAreaTransformer1.func_202711_b(SourceFile:13) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.layer.traits.IAreaTransformer1$$Lambda$4848/451779965.apply(Unknown Source) ~[?:?] {}
	at net.minecraft.world.gen.area.LazyArea.func_202678_a(SourceFile:26) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.layer.traits.ICastleTransformer.func_215728_a(SourceFile:14) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.layer.traits.IAreaTransformer1.func_202711_b(SourceFile:13) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.layer.traits.IAreaTransformer1$$Lambda$4848/451779965.apply(Unknown Source) ~[?:?] {}
	at net.minecraft.world.gen.area.LazyArea.func_202678_a(SourceFile:26) ~[?:?] {re:classloading}
	at biomesoplenty.common.world.layer.BOPRiverMixLayer.func_215723_a(BOPRiverMixLayer.java:37) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.layer.traits.IAreaTransformer2.func_215724_a(SourceFile:15) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.layer.traits.IAreaTransformer2$$Lambda$4849/1624143312.apply(Unknown Source) ~[?:?] {}
	at net.minecraft.world.gen.area.LazyArea.func_202678_a(SourceFile:26) ~[?:?] {re:classloading}
	at biomesoplenty.common.world.layer.BOPMixOceansLayer.applyPixel(BOPMixOceansLayer.java:28) ~[?:?] {re:classloading}
	at biomesoplenty.common.world.layer.traits.IAreaTransformer3.lambda$null$0(IAreaTransformer3.java:29) ~[?:?] {re:classloading}
	at biomesoplenty.common.world.layer.traits.IAreaTransformer3$$Lambda$4878/679022302.apply(Unknown Source) ~[?:?] {}
	at net.minecraft.world.gen.area.LazyArea.func_202678_a(SourceFile:26) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.layer.Layer.func_242936_a(SourceFile:23) ~[?:?] {re:classloading}
	at biomesoplenty.common.world.BOPBiomeProvider.func_225526_b_(BOPBiomeProvider.java:70) ~[?:?] {re:classloading}
	at net.minecraft.world.biome.provider.BiomeProvider.func_230321_a_(SourceFile:119) ~[?:?] {re:classloading}
	at net.minecraft.world.biome.provider.BiomeProvider.func_225531_a_(SourceFile:83) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.ChunkGenerator.func_235958_g_(SourceFile:111) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.ChunkGenerator.func_235952_a_(SourceFile:334) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.feature.structure.StrongholdStructure.func_230363_a_(SourceFile:31) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.feature.structure.StrongholdStructure.func_230363_a_(SourceFile:19) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.feature.structure.Structure.func_242785_a(Structure.java:222) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.feature.StructureFeature.func_242771_a(SourceFile:35) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.ChunkGenerator.func_242705_a(SourceFile:278) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.ChunkGenerator.func_242707_a(SourceFile:264) ~[?:?] {re:classloading}
	at net.minecraft.world.chunk.ChunkStatus.func_222586_d(ChunkStatus.java:41) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.chunk.ChunkStatus$$Lambda$2328/1773851641.doWork(Unknown Source) ~[?:?] {}
	at net.minecraft.world.chunk.ChunkStatus.func_223198_a(ChunkStatus.java:198) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ChunkManager.lambda$null$18(ChunkManager.java:524) ~[?:?] {re:classloading}
	at net.minecraft.world.server.ChunkManager$$Lambda$5903/1550782648.apply(Unknown Source) ~[?:?] {}
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.0.26.jar:?] {re:classloading,re:classloading}
	at net.minecraft.world.server.ChunkManager.lambda$scheduleChunkGeneration$20(ChunkManager.java:522) ~[?:?] {re:classloading}
	at net.minecraft.world.server.ChunkManager$$Lambda$5888/1468167065.apply(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) ~[?:1.8.0_51] {}
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter.func_219083_b(SourceFile:58) ~[?:?] {re:classloading}
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter$$Lambda$5901/172644990.run(Unknown Source) ~[?:?] {}
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213148_e(SourceFile:94) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213145_a(SourceFile:137) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.run(SourceFile:105) ~[?:?] {re:classloading}
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at biomesoplenty.common.util.biome.BiomeUtil.getBiome(BiomeUtil.java:38) ~[?:?] {re:classloading}
	at biomesoplenty.common.util.biome.BiomeUtil.getBiomeId(BiomeUtil.java:58) ~[?:?] {re:classloading}
	at biomesoplenty.common.world.layer.BOPShoreLayer.func_202748_a(BOPShoreLayer.java:97) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.layer.traits.ICastleTransformer.func_215728_a(SourceFile:12) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.layer.traits.IAreaTransformer1.func_202711_b(SourceFile:13) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.layer.traits.IAreaTransformer1$$Lambda$4848/451779965.apply(Unknown Source) ~[?:?] {}
	at net.minecraft.world.gen.area.LazyArea.func_202678_a(SourceFile:26) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.layer.ZoomLayer.func_215728_a(SourceFile:41) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.layer.traits.IAreaTransformer1.func_202711_b(SourceFile:13) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.layer.traits.IAreaTransformer1$$Lambda$4848/451779965.apply(Unknown Source) ~[?:?] {}
	at net.minecraft.world.gen.area.LazyArea.func_202678_a(SourceFile:26) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.layer.traits.ICastleTransformer.func_215728_a(SourceFile:14) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.layer.traits.IAreaTransformer1.func_202711_b(SourceFile:13) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.layer.traits.IAreaTransformer1$$Lambda$4848/451779965.apply(Unknown Source) ~[?:?] {}
	at net.minecraft.world.gen.area.LazyArea.func_202678_a(SourceFile:26) ~[?:?] {re:classloading}
	at biomesoplenty.common.world.layer.BOPRiverMixLayer.func_215723_a(BOPRiverMixLayer.java:37) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.layer.traits.IAreaTransformer2.func_215724_a(SourceFile:15) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.layer.traits.IAreaTransformer2$$Lambda$4849/1624143312.apply(Unknown Source) ~[?:?] {}
	at net.minecraft.world.gen.area.LazyArea.func_202678_a(SourceFile:26) ~[?:?] {re:classloading}
	at biomesoplenty.common.world.layer.BOPMixOceansLayer.applyPixel(BOPMixOceansLayer.java:28) ~[?:?] {re:classloading}
	at biomesoplenty.common.world.layer.traits.IAreaTransformer3.lambda$null$0(IAreaTransformer3.java:29) ~[?:?] {re:classloading}
	at biomesoplenty.common.world.layer.traits.IAreaTransformer3$$Lambda$4878/679022302.apply(Unknown Source) ~[?:?] {}
	at net.minecraft.world.gen.area.LazyArea.func_202678_a(SourceFile:26) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.layer.Layer.func_242936_a(SourceFile:23) ~[?:?] {re:classloading}
	at biomesoplenty.common.world.BOPBiomeProvider.func_225526_b_(BOPBiomeProvider.java:70) ~[?:?] {re:classloading}
	at net.minecraft.world.biome.provider.BiomeProvider.func_230321_a_(SourceFile:119) ~[?:?] {re:classloading}
	at net.minecraft.world.biome.provider.BiomeProvider.func_225531_a_(SourceFile:83) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.ChunkGenerator.func_235958_g_(SourceFile:111) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.ChunkGenerator.func_235952_a_(SourceFile:334) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.feature.structure.StrongholdStructure.func_230363_a_(SourceFile:31) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.feature.structure.StrongholdStructure.func_230363_a_(SourceFile:19) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.feature.structure.Structure.func_242785_a(Structure.java:222) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.feature.StructureFeature.func_242771_a(SourceFile:35) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.ChunkGenerator.func_242705_a(SourceFile:278) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.ChunkGenerator.func_242707_a(SourceFile:264) ~[?:?] {re:classloading}
	at net.minecraft.world.chunk.ChunkStatus.func_222586_d(ChunkStatus.java:41) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.chunk.ChunkStatus$$Lambda$2328/1773851641.doWork(Unknown Source) ~[?:?] {}
	at net.minecraft.world.chunk.ChunkStatus.func_223198_a(ChunkStatus.java:198) ~[?:?] {re:classloading,pl:accesstransformer:B}
-- Chunk to be generated --
Details:
	Location: 23,7
	Position hash: 30064771095
	Generator: net.minecraft.world.gen.NoiseChunkGenerator@1e9e878d
Stacktrace:
	at net.minecraft.world.server.ChunkManager.lambda$null$18(ChunkManager.java:524) ~[?:?] {re:classloading}
	at net.minecraft.world.server.ChunkManager$$Lambda$5903/1550782648.apply(Unknown Source) ~[?:?] {}
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.0.26.jar:?] {re:classloading,re:classloading,re:classloading}
	at net.minecraft.world.server.ChunkManager.lambda$scheduleChunkGeneration$20(ChunkManager.java:522) ~[?:?] {re:classloading}
	at net.minecraft.world.server.ChunkManager$$Lambda$5888/1468167065.apply(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) ~[?:1.8.0_51] {}
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter.func_219083_b(SourceFile:58) ~[?:?] {re:classloading}
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter$$Lambda$5901/172644990.run(Unknown Source) ~[?:?] {}
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213148_e(SourceFile:94) ~[?:?] {re:classloading}

-- Affected level --
Details:
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 9
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level name: New World
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_240787_a_(MinecraftServer.java:353) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_240800_l__(MinecraftServer.java:308) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:60) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:621) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer$$Lambda$5773/1163307431.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1045037424 bytes (996 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 16
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.1.25.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.25.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.1.25.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.25.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.1.25.jar fml TRANSFORMATIONSERVICE 
	FML: 36.1
	Forge: net.minecraftforge:36.1.25
	FML Language Providers: 
		javafml@36.1
		minecraft@1
	Mod List: 
		forge-1.16.5-36.1.25-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |DONE      |Manifest: NOSIGNATURE
		backpacked-1.10.1-1.16.3.jar                      |Backpacked                    |backpacked                    |1.10.1              |DONE      |Manifest: NOSIGNATURE
		BiomesOPlenty-1.16.5-13.1.0.469-universal.jar     |Biomes O' Plenty              |biomesoplenty                 |1.16.5-13.1.0.469   |DONE      |Manifest: NOSIGNATURE
		treeharvester_1.16.5-2.2.jar                      |Tree Harvester                |treeharvester                 |2.2                 |DONE      |Manifest: NOSIGNATURE
		solcarrot-1.16.3-1.9.10.jar                       |Spice of Life: Carrot Edition |solcarrot                     |1.16.3-1.9.10       |DONE      |Manifest: NOSIGNATURE
		ironagefurniture+1.16.4-1.16.5+0.2.0.5.jar        |Iron Age Furniture            |ironagefurniture              |1.16.4-0.2.0        |DONE      |Manifest: NOSIGNATURE
		Hwyla-forge-1.10.11-B78_1.16.2.jar                |Waila                         |waila                         |1.10.11-B78_1.16.2  |DONE      |Manifest: NOSIGNATURE
		jei-1.16.5-7.7.0.103.jar                          |Just Enough Items             |jei                           |7.7.0.103           |DONE      |Manifest: NOSIGNATURE
		simplefarming-1.16.5-1.3.6.jar                    |Simple Farming                |simplefarming                 |1.16.4-1.3.6        |DONE      |Manifest: NOSIGNATURE
		villagespawnpoint_1.16.5-1.5.jar                  |Village Spawn Point           |villagespawnpoint             |1.5                 |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.1.25-universal.jar                |Forge                         |forge                         |36.1.25             |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		collective-1.16.5-2.26.jar                        |Collective                    |collective                    |2.26                |DONE      |Manifest: NOSIGNATURE
		DynamicSurroundings-1.16.4-4.0.4.2.jar            |§3Dynamic Surroundings        |dsurround                     |1.16.4-4.0.4.2      |DONE      |Manifest: b4:98:14:b9:76:55:25:4f:e5:5f:4d:71:90:87:43:5b:f9:d5:3a:02:60:42:5e:da:1f:15:9c:ff:be:a9:7c:77
		World-Map-Mod-1.16.4.jar                          |Xaero's World Map             |xaeroworldmap                 |1.11.1              |DONE      |Manifest: NOSIGNATURE
		OresAboveDiamonds-1.16.4-v6.3.3.jar               |Ores Above Diamonds           |oresabovediamonds             |6.3.3               |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 121f8b70-61f9-4f1b-86c0-5f7d4136730e
	Player Count: 0 / 8; []
	Data Packs: vanilla, mod:backpacked (incompatible), mod:biomesoplenty, mod:treeharvester, mod:solcarrot (incompatible), mod:ironagefurniture (incompatible), mod:waila, mod:jei, mod:simplefarming, mod:villagespawnpoint, mod:forge, mod:collective, mod:dsurround, mod:xaeroworldmap, mod:oresabovediamonds (incompatible)
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'
### Mod Version
BiomesOPlenty-1.16.5-13.1.0.469-universal.jar

**Comment by Adubbz** [comment]
You need to include logs if you’re reporting a crash.

**Comment by Teralitha** [comment]
Done

**Comment by Teralitha** [comment]
Edited post for more accurate info
