### ISSUE TITLE
[1.16.5] Generating new worlds can cause the game to get stuck and reports "Exception generating new chunk"

### ISSUE THREAD

**Issue by LTCatt** [Glitchfiend/BiomesOPlenty#1884]
## Bug Report

Generating new worlds can cause the game to get stuck in the following stages.
After deleting BOP from mods folder alone, the issue doesn't appear anymore.

![image](https://user-images.githubusercontent.com/40348278/126887708-88e4e72d-79ad-4b4e-b7d4-195426eb1ddf.png)

Here's my config file if you need it:
[biomesoplenty.zip](https://github.com/Glitchfiend/BiomesOPlenty/files/6873379/biomesoplenty.zip)

</br>

### How can the crash be reproduced?

Appears randomly while creating a new world.
There is a high probability that it will happen, and three attempts will almost certainly trigger it.</br>

### Crash Report and Logs

You can find a crash report in the end of this log file.
[latest.log](https://github.com/Glitchfiend/BiomesOPlenty/files/6873373/latest.log)

Error executing task on Chunk source main thread executor for minecraft:overworld

java.util.concurrent.CompletionException: net.minecraft.crash.ReportedException: Exception generating new chunk
	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniCompose(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter.func_219083_b(SourceFile:58) ~[?:?]
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213148_e(SourceFile:94) ~[?:?]
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213145_a(SourceFile:137) ~[?:?]
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.run(SourceFile:105) ~[?:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?]

Caused by: net.minecraft.crash.ReportedException: Exception generating new chunk
	at net.minecraft.world.server.ChunkManager.lambda$null$18(ChunkManager.java:688) ~[?:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.0.26.jar:?]
	at net.minecraft.world.server.ChunkManager.lambda$chunkGenerate$20(ChunkManager.java:673) ~[?:?]
	... 12 more

Caused by: java.lang.IllegalArgumentException
	at net.minecraft.util.WeightedRandom.func_76273_a(SourceFile:20) ~[?:?]
	at net.minecraft.util.WeightedRandom.func_76271_a(SourceFile:39) ~[?:?]
	at net.minecraft.world.spawner.WorldEntitySpawner.func_77191_a(WorldEntitySpawner.java:334) ~[?:?]
	at net.minecraft.world.gen.NoiseChunkGenerator.func_230354_a_(NoiseChunkGenerator.java:623) ~[?:?]
	at net.minecraft.world.chunk.ChunkStatus.func_222602_b(ChunkStatus.java:89) ~[?:?]
	at net.minecraft.world.chunk.ChunkStatus$ISelectiveWorker.doWork(ChunkStatus.java:240) ~[?:?]
	at net.minecraft.world.chunk.ChunkStatus.func_223198_a(ChunkStatus.java:198) ~[?:?]
	at net.minecraft.world.server.ChunkManager.lambda$null$18(ChunkManager.java:675) ~[?:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.0.26.jar:?]
	at net.minecraft.world.server.ChunkManager.lambda$chunkGenerate$20(ChunkManager.java:673) ~[?:?]
	... 12 more
</br>

### Mod Version
Both 1.16.5-13.1.0.477 and 1.16.5-13.1.0.471 have this issue.</br>

**Comment by Forstride** [comment]
This doesn't seem to be caused by BOP at all.  Some other mod is likely adding an entity spawn with presumably invalid values for the min/max group size (Or the spawn frequency), and you're having the crash happen more frequently because of it spawning in our biomes or whatever.  Sadly, the stacktrace doesn't give any hints as to what said entity is, so we can't really help.  You're just gonna have to remove any mods that add mobs one by one to find the culprit yourself.
