### ISSUE TITLE
language provider

### ISSUE THREAD

**Issue by hu050411** [Glitchfiend/BiomesOPlenty#1929]
### What's the issue you encountered?

Whenever i load biomesOPlenty 1.18 i get this error. Mod File BiomesOPlenty-1.18.1-15.0.0.51-universal.jar needs language provider javafml:39 or above to load.  How do i fix this

### How can the issue be reproduced?

No idea

### Logs

[29Dec2021 15:41:32.940] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, YoItsMeme, --version, 1.18-forge-38.0.17, --gameDir, C:\Users\hayde\AppData\Roaming\.minecraft, --assetsDir, C:\Users\hayde\AppData\Roaming\.minecraft\assets, --assetIndex, 1.18, --uuid, e66c4aa0de2f4dd3a1294ac459c79c80, --accessToken, ????????, --clientId, MGY3YWE2MDktODJmMS00NzI0LTlkMzItNTUyMzhjNjZkNjU5, --xuid, --userType, mojang, --versionType, release, --launchTarget, forgeclient, --fml.forgeVersion, 38.0.17, --fml.mcVersion, 1.18, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20211130.085255] [29Dec2021 15:41:32.959] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 9.0.7+91+master.8569cdf starting: java version 17.0.1 by Microsoft [29Dec2021 15:41:33.174] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/hayde/AppData/Roaming/.minecraft/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2319! Service=ModLauncher Env=CLIENT [29Dec2021 15:41:34.081] [main/ERROR] [net.minecraftforge.fml.loading.LanguageLoadingProvider/LOADING]: Missing language javafml version [39,) wanted by BiomesOPlenty-1.18.1-15.0.0.51-universal.jar, found 38 [29Dec2021 15:41:34.083] [main/ERROR] [net.minecraftforge.fml.loading.LanguageLoadingProvider/LOADING]: Missing language javafml version [39,) wanted by NaturesCompass-1.18.1-1.9.4-forge.jar, found 38 [29Dec2021 15:41:35.760] [main/INFO] [mixin/]: Compatibility level set to JAVA_17 [29Dec2021 15:41:35.766] [main/INFO] [cpw.mods.modlauncher.LaunchServiceHandler/MODLAUNCHER]: Launching target 'forgeclient' with arguments [--version, 1.18-forge-38.0.17, --gameDir, C:\Users\hayde\AppData\Roaming\.minecraft, --assetsDir, C:\Users\hayde\AppData\Roaming\.minecraft\assets, --uuid, e66c4aa0de2f4dd3a1294ac459c79c80, --username, YoItsMeme, --assetIndex, 1.18, --accessToken, ????????, --clientId, MGY3YWE2MDktODJmMS00NzI0LTlkMzItNTUyMzhjNjZkNjU5, --xuid, --userType, mojang, --versionType, release] [15:41:47] [Render thread/WARN]: Assets URL 'union:/C:/Users/hayde/AppData/Roaming/.minecraft/libraries/net/minecraft/client/1.18-20211130.085255/client-1.18-20211130.085255-srg.jar%2359!/assets/.mcassetsroot' uses unexpected schema [15:41:47] [Render thread/WARN]: Assets URL 'union:/C:/Users/hayde/AppData/Roaming/.minecraft/libraries/net/minecraft/client/1.18-20211130.085255/client-1.18-20211130.085255-srg.jar%2359!/data/.mcassetsroot' uses unexpected schema [29Dec2021 15:41:47.365] [Render thread/INFO] [com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService/]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD' [15:41:48] [Render thread/INFO]: Setting user: YoItsMeme [15:41:49] [Render thread/WARN]: Invalid floating point value for option textBackgroundOpacity =  java.lang.NumberFormatException: empty String 	at jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1842) ~[?:?] 	at jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110) ~[?:?] 	at java.lang.Double.parseDouble(Double.java:651) ~[?:?] 	at net.minecraft.client.Options$2.m_142547_(Options.java:415) ~[client-1.18-20211130.085255-srg.jar%2359!:?] 	at net.minecraft.client.Options.m_168427_(Options.java:272) ~[client-1.18-20211130.085255-srg.jar%2359!:?] 	at net.minecraft.client.Options.m_92140_(Options.java:375) ~[client-1.18-20211130.085255-srg.jar%2359!:?] 	at net.minecraft.client.Options.<init>(Options.java:204) ~[client-1.18-20211130.085255-srg.jar%2359!:?] 	at net.minecraft.client.Minecraft.<init>(Minecraft.java:423) ~[client-1.18-20211130.085255-srg.jar%2359!:?] 	at net.minecraft.client.main.Main.main(Main.java:169) ~[client-1.18-20211130.085255-srg.jar%2359!:?] 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] 	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] 	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.18-38.0.17.jar%2323!:?] 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.0.7.jar%235!:?] 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.0.7.jar%235!:?] 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.0.7.jar%235!:?] 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.0.7.jar%235!:?] 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.0.7.jar%235!:?] 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.0.7.jar%235!:?] 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.0.7.jar%235!:?] 	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:90) [bootstraplauncher-0.1.17.jar:?] [15:41:49] [Render thread/INFO]: Backend library: LWJGL version 3.2.2 SNAPSHOT [29Dec2021 15:41:51.914] [Render thread/FATAL] [net.minecraftforge.fml.ModLoader/CORE]: Error during pre-loading phase net.minecraftforge.fml.ModLoadingException: Mod File BiomesOPlenty-1.18.1-15.0.0.51-universal.jar needs language provider javafml:39 or above to load §7We have found 38 	at net.minecraftforge.fml.ModLoadingException.lambda$fromEarlyException$0(ModLoadingException.java:64) ~[fmlcore-1.18-38.0.17.jar%2360!:?] 	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?] 	at java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720) ~[?:?] 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?] 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] 	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?] 	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?] 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] 	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?] 	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?] 	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?] 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?] 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] 	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?] 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] 	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?] 	at net.minecraftforge.fml.ModLoader.<init>(ModLoader.java:108) ~[fmlcore-1.18-38.0.17.jar%2360!:?] 	at net.minecraftforge.fml.ModLoader.get(ModLoader.java:140) ~[fmlcore-1.18-38.0.17.jar%2360!:?] 	at net.minecraftforge.client.loading.ClientModLoader.lambda$begin$1(ClientModLoader.java:106) ~[forge-1.18-38.0.17-universal.jar%2363!:?] 	at net.minecraftforge.client.loading.ClientModLoader.lambda$createRunnableWithCatch$4(ClientModLoader.java:127) ~[forge-1.18-38.0.17-universal.jar%2363!:?] 	at net.minecraftforge.client.loading.ClientModLoader.begin(ClientModLoader.java:106) ~[forge-1.18-38.0.17-universal.jar%2363!:?] 	at net.minecraft.client.Minecraft.<init>(Minecraft.java:458) ~[client-1.18-20211130.085255-srg.jar%2359!:?] 	at net.minecraft.client.main.Main.main(Main.java:169) ~[client-1.18-20211130.085255-srg.jar%2359!:?] 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] 	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] 	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.18-38.0.17.jar%2323!:?] 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.0.7.jar%235!:?] 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.0.7.jar%235!:?] 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.0.7.jar%235!:?] 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.0.7.jar%235!:?] 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.0.7.jar%235!:?] 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.0.7.jar%235!:?] 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.0.7.jar%235!:?] 	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:90) [bootstraplauncher-0.1.17.jar:?] [15:41:52] [Render thread/WARN]: Couldn't get pack info for: net.minecraft.server.packs.ResourcePackFileNotFoundException: 'pack.mcmeta' in ResourcePack 'C:\Users\hayde\AppData\Roaming\.minecraft\resourcepacks\ooocraft-1-16-v1.zip' [29Dec2021 15:41:52.357] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.sound.SoundLoadEvent to a broken mod state [29Dec2021 15:41:52.754] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.ColorHandlerEvent$Block to a broken mod state [29Dec2021 15:41:52.837] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.ColorHandlerEvent$Item to a broken mod state [29Dec2021 15:41:54.389] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.ParticleFactoryRegisterEvent to a broken mod state [29Dec2021 15:41:54.511] [Render thread/INFO] [com.mojang.text2speech.NarratorWindows/]: Narrator library for x64 successfully loaded [29Dec2021 15:41:54.623] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterClientReloadListenersEvent to a broken mod state [29Dec2021 15:41:54.623] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$RegisterLayerDefinitions to a broken mod state [29Dec2021 15:41:54.624] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$RegisterRenderers to a broken mod state [15:41:54] [Render thread/INFO]: Reloading ResourceManager: Default [29Dec2021 15:41:55.290] [Worker-Main-13/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.ModelRegistryEvent to a broken mod state [29Dec2021 15:41:55.666] [Worker-Main-15/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state [29Dec2021 15:41:55.668] [Worker-Main-9/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state [29Dec2021 15:41:55.696] [Worker-Main-14/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state [29Dec2021 15:42:16.380] [Worker-Main-13/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state [29Dec2021 15:42:19.323] [Worker-Main-13/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state [29Dec2021 15:42:19.345] [Worker-Main-13/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state [29Dec2021 15:42:19.442] [Worker-Main-13/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state [29Dec2021 15:42:19.522] [Worker-Main-13/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state [29Dec2021 15:42:19.547] [Worker-Main-13/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state [29Dec2021 15:42:19.583] [Worker-Main-13/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state [15:42:19] [Render thread/INFO]: OpenAL initialized on device OpenAL Soft on Realtek HD Audio 2nd output (Realtek(R) Audio) [15:42:19] [Render thread/INFO]: Sound engine started [15:42:20] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/blocks.png-atlas [29Dec2021 15:42:20.175] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state [15:42:20] [Render thread/INFO]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas [29Dec2021 15:42:20.177] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state [15:42:20] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/banner_patterns.png-atlas [29Dec2021 15:42:20.179] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state [15:42:20] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/shield_patterns.png-atlas [29Dec2021 15:42:20.181] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state [15:42:20] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas [29Dec2021 15:42:20.182] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state [15:42:20] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas [29Dec2021 15:42:20.184] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state [15:42:20] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas [29Dec2021 15:42:20.186] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state [29Dec2021 15:42:20.707] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.ModelBakeEvent to a broken mod state [29Dec2021 15:42:21.403] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$AddLayers to a broken mod state [29Dec2021 15:42:22.474] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterShadersEvent to a broken mod state [15:42:22] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas [29Dec2021 15:42:22.763] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state [15:42:22] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas [29Dec2021 15:42:22.765] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state [15:42:22] [Render thread/INFO]: Created: 128x128x0 minecraft:textures/atlas/mob_effects.png-atlas [29Dec2021 15:42:22.766] [Render thread/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state [15:42:23] [Render thread/FATAL]: Crash report saved to C:\Users\hayde\AppData\Roaming\.minecraft\crash-reports\crash-2021-12-29_15.42.23-fml.txt

### Mod Version

1.18.1-15.0.0.51

### Additional information

nope

**Comment by Adubbz** [comment]
You're trying to run 1.18.1 mods on 1.18. You need to update to Minecraft 1.18.1.
