### ISSUE TITLE
"The game crashed whilst rendering overlay"

### ISSUE THREAD

**Issue by Sherane0** [Glitchfiend/BiomesOPlenty#1983]
### What's the issue you encountered?

**Game loads, shows the "Saving world" screen and then crashes with this error:**
```
The game crashed whilst rendering overlay
Error: java.lang.IllegalArgumentException: Multiple entries with same key: biomesoplenty:sign/cherry#main=net.minecraft.client.model.geom.builders.LayerDefinition@7ab5a0b8 and biomesoplenty:sign/cherry#main=net.minecraft.client.model.geom.builders.LayerDefinition@7ab5a0b8
Exit Code: -1
```
**Deleting all the config files or changing version of the mod did not fixed the problem**

**---- Minecraft Crash Report ----**

Description: Rendering overlay

```
java.lang.IllegalArgumentException: Multiple entries with same key: biomesoplenty:sign/cherry#main=net.minecraft.client.model.geom.builders.LayerDefinition@7ab5a0b8 and biomesoplenty:sign/cherry#main=net.minecraft.client.model.geom.builders.LayerDefinition@7ab5a0b8
	at com.google.common.collect.ImmutableMap.conflictException(ImmutableMap.java:376) ~[guava-31.0.1-jre.jar%2321!/:?] {}
	at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:370) ~[guava-31.0.1-jre.jar%2321!/:?] {}
	at com.google.common.collect.RegularImmutableMap.checkNoConflictInKeyBucket(RegularImmutableMap.java:153) ~[guava-31.0.1-jre.jar%2321!/:?] {}
	at com.google.common.collect.RegularImmutableMap.fromEntryArray(RegularImmutableMap.java:115) ~[guava-31.0.1-jre.jar%2321!/:?] {}
	at com.google.common.collect.ImmutableMap$Builder.buildOrThrow(ImmutableMap.java:574) ~[guava-31.0.1-jre.jar%2321!/:?] {}
	at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:538) ~[guava-31.0.1-jre.jar%2321!/:?] {}
	at net.minecraft.client.model.geom.LayerDefinitions.m_171110_(LayerDefinitions.java:288) ~[client-1.18.1-20211210.034407-srg.jar%23253!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.model.geom.EntityModelSet.m_6213_(EntityModelSet.java:24) ~[client-1.18.1-20211210.034407-srg.jar%23253!/:?] {re:classloading,re:mixin}
	at net.minecraft.server.packs.resources.ResourceManagerReloadListener.m_10759_(ResourceManagerReloadListener.java:15) ~[client-1.18.1-20211210.034407-srg.jar%23253!/:?] {re:computing_frames,re:mixin,re:classloading}
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:787) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?] {}
	at net.minecraft.server.packs.resources.SimpleReloadInstance.m_143940_(SimpleReloadInstance.java:71) ~[client-1.18.1-20211210.034407-srg.jar%23253!/:?] {re:computing_frames,re:classloading}
	at net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:118) ~[client-1.18.1-20211210.034407-srg.jar%23253!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:computing_frames,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.server.packs.resources.SimpleReloadInstance.m_10834_(SimpleReloadInstance.java:70) ~[client-1.18.1-20211210.034407-srg.jar%23253!/:?] {re:computing_frames,re:classloading}
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:784) ~[?:?] {}
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?] {re:mixin}
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) ~[?:?] {re:mixin}
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?] {}
	at net.minecraft.server.packs.resources.SimpleReloadInstance.m_143940_(SimpleReloadInstance.java:71) ~[client-1.18.1-20211210.034407-srg.jar%23253!/:?] {re:computing_frames,re:classloading}
	at net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:118) ~[client-1.18.1-20211210.034407-srg.jar%23253!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:computing_frames,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.server.packs.resources.SimpleReloadInstance.m_10834_(SimpleReloadInstance.java:70) ~[client-1.18.1-20211210.034407-srg.jar%23253!/:?] {re:computing_frames,re:classloading}
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?] {}
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?] {re:mixin}
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) ~[?:?] {re:mixin}
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?] {}
	at net.minecraft.server.packs.resources.SimpleReloadInstance.m_143940_(SimpleReloadInstance.java:71) ~[client-1.18.1-20211210.034407-srg.jar%23253!/:?] {re:computing_frames,re:classloading}
	at net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:118) ~[client-1.18.1-20211210.034407-srg.jar%23253!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:computing_frames,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.server.packs.resources.SimpleReloadInstance.m_10834_(SimpleReloadInstance.java:70) ~[client-1.18.1-20211210.034407-srg.jar%23253!/:?] {re:computing_frames,re:classloading}
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?] {}
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?] {re:mixin}
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) ~[?:?] {re:mixin}
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?] {}
	at net.minecraft.server.packs.resources.SimpleReloadInstance.m_143940_(SimpleReloadInstance.java:71) ~[client-1.18.1-20211210.034407-srg.jar%23253!/:?] {re:computing_frames,re:classloading}
	at net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:118) ~[client-1.18.1-20211210.034407-srg.jar%23253!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:computing_frames,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.server.packs.resources.SimpleReloadInstance.m_10834_(SimpleReloadInstance.java:70) ~[client-1.18.1-20211210.034407-srg.jar%23253!/:?] {re:computing_frames,re:classloading}
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?] {}
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?] {re:mixin}
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) ~[?:?] {re:mixin}
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?] {}
	at net.minecraft.server.packs.resources.SimpleReloadInstance.m_143940_(SimpleReloadInstance.java:71) ~[client-1.18.1-20211210.034407-srg.jar%23253!/:?] {re:computing_frames,re:classloading}
	at net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:118) ~[client-1.18.1-20211210.034407-srg.jar%23253!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:computing_frames,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.server.packs.resources.SimpleReloadInstance.m_10834_(SimpleReloadInstance.java:70) ~[client-1.18.1-20211210.034407-srg.jar%23253!/:?] {re:computing_frames,re:classloading}
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?] {}
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?] {re:mixin}
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) ~[?:?] {re:mixin}
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?] {}
	at net.minecraft.server.packs.resources.SimpleReloadInstance.m_143940_(SimpleReloadInstance.java:71) ~[client-1.18.1-20211210.034407-srg.jar%23253!/:?] {re:computing_frames,re:classloading}
	at net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:118) ~[client-1.18.1-20211210.034407-srg.jar%23253!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:computing_frames,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.server.packs.resources.SimpleReloadInstance.m_10834_(SimpleReloadInstance.java:70) ~[client-1.18.1-20211210.034407-srg.jar%23253!/:?] {re:computing_frames,re:classloading}
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?] {}
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?] {re:mixin}
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) ~[?:?] {re:mixin}
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?] {}
	at net.minecraft.server.packs.resources.SimpleReloadInstance.m_143940_(SimpleReloadInstance.java:71) ~[client-1.18.1-20211210.034407-srg.jar%23253!/:?] {re:computing_frames,re:classloading}
	at net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:118) ~[client-1.18.1-20211210.034407-srg.jar%23253!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:computing_frames,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.server.packs.resources.SimpleReloadInstance.m_10834_(SimpleReloadInstance.java:70) ~[client-1.18.1-20211210.034407-srg.jar%23253!/:?] {re:computing_frames,re:classloading}
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?] {}
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?] {re:mixin}
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) ~[?:?] {re:mixin}
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?] {}
	at com.mojang.blaze3d.systems.RenderSystem.m_69884_(RenderSystem.java:210) ~[client-1.18.1-20211210.034407-srg.jar%23253!/:?] {re:mixin,xf:OptiFine:default,re:classloading,xf:OptiFine:default,pl:mixin:APP:flywheel.mixins.json:RenderTexturesMixin,pl:mixin:A}
	at com.mojang.blaze3d.systems.RenderSystem.m_69495_(RenderSystem.java:197) ~[client-1.18.1-20211210.034407-srg.jar%23253!/:?] {re:mixin,xf:OptiFine:default,re:classloading,xf:OptiFine:default,pl:mixin:APP:flywheel.mixins.json:RenderTexturesMixin,pl:mixin:A}
	at com.mojang.blaze3d.platform.Window.m_85435_(Window.java:442) ~[client-1.18.1-20211210.034407-srg.jar%23253!/:?] {re:classloading,xf:OptiFine:default,re:mixin,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1063) ~[client-1.18.1-20211210.034407-srg.jar%23253!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:blueprint.mixins.json:client.MinecraftMixin,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:mixins.ipnext.json:MixinMinecraftClient,pl:mixin:APP:offhandcombat-common.mixins.json:ClickMixin,pl:mixin:APP:offhandcombat.mixins.json:RightClickMixin,pl:mixin:APP:terrablender_forge.mixins.json:client.MixinMinecraft,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:661) ~[client-1.18.1-20211210.034407-srg.jar%23253!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:blueprint.mixins.json:client.MinecraftMixin,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:mixins.ipnext.json:MixinMinecraftClient,pl:mixin:APP:offhandcombat-common.mixins.json:ClickMixin,pl:mixin:APP:offhandcombat.mixins.json:RightClickMixin,pl:mixin:APP:terrablender_forge.mixins.json:client.MixinMinecraft,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.1-20211210.034407-srg.jar%23253!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.18.1-39.1.0.jar%2323!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}

```

### How can the issue be reproduced?

**Launch the game with the list of mods:**
_YUNG's Better Dungeons        
Big Brain                     
Windowlogging                 
Music Player                  
Mod Name Tooltip              
NBT Tool                      
Advancement Frames            
Name Pain                     
YUNG's API                    
Guard Villagers               
clickadv mod                  
Carry the Nametag             
Balm                          
Carpet Stairs Mod             
Dynamic view distance         
Just Enough Resources         
Throwable Explosives          
Cloth Config v4 API           
Sound Physics Remastered      
Stack Refill                  
More Horse Armor              
Enchanting Overhauled         
Corpse                        
Advancement Plaques           
Better Ping Display           
Repurposed Structures         
Better Compatibility Checker  
Biomes O' Plenty              
Just Enough Painting Previews 
Chunk Animator                
MinecraftCapes Mod            
SuperMartijn642's Core Lib    
Highlighter                   
spark                         
Curios API                    
Corail Woodcutter             
Extended Lights               
Throwability                  
Edible Nether Wart            
Construction Wand             
Sapience                      
The Weirding Gadget           
Better Trident Return         
Smaller Nether Portals        
GeckoLib                      
Better Mods Button            
DarkPaintings                 
Gadgets                       
Notes                         
Torch Slab Mod                
Connectible Chains            
Config Menus for Forge        
Tree Harvester                
Just Enough Items             
Visual Workbench              
Additional Bars               
Stoneholm                     
Snow Under Trees              
Catalogue                     
Block Diversity               
Forge                         
When Dungeons Arise           
Minecraft                     
Logprot                       
TerraBlender                  
Shoulder Surfing              
FirstPersonModel Mod          
Inventory Hotswap             
Ding                          
betterfpsdist mod             
Mysterious Mountain Lib       
Majrusz Library               
NotEnoughAnimations Mod       
Flywheel                      
Create: Alloyed               
Create: Steam Powered         
AutoRegLib                    
EntityCulling                 
Hardcore Revival              
MapTooltip                    
Buddycards Expansions         
Signs o' Plenty               
AppleSkin                     
DamageTilt                    
Puzzles Lib                   
Aquaculture 2                 
MineMenu                      
CosmeticArmorReworked         
Step                          
Tetra                         
Bottled Air                   
PreciseBlockPlacing           
No Null Processors            
Tiny Redstone                 
Extended Note block           
Better Signs                  
Connectivity Mod              
Wonderful Enchantments        
Glassential                   
Villager Names                
ItemLocks                     
True Darkness                 
BetterPortalOpening           
Xaero's World Map             
Controlling                   
Citadel                       
Alex's Mobs                   
Feature NBT Deadlock Be Gone  
Item Zoom                     
Patina Pipeworks              
Zetter                        
Better Beacon Placement       
Carry On                      
Despawning Eggs Hatch         
Buddycards Core               
Equipment Compare             
Farmer's Delight              
Copper's Delight              
Corn Delight                  
Customizable Elytra           
Decorative Compat             
Crash Utilities               
Let Sleeping Dogs Lie         
Skinned Lanterns              
Horse Stats Mod               
Fish On The Line              
GoProne                       
Hole Filler Mod               
Leap                          
Collective                    
Drawers Tooltip               
Elytra Bombing                
YUNG's Better Strongholds     
Eating Animation              
Inventory Profiles Next       
Architectury                  
Better Recipe Book            
Off Hand Combat               
Building Wands                
FindMe                        
AI-Improvements               
Cherished Worlds              
Lan Server Properties         
Inventory Essentials          
Cursery Mod                   
Scaffolding Drops Nearby      
Amplified Nether + Seed Fix   
Simple Inventory Sorter       
Snowy Weaponry                
Xtra Arrows                   
Snorkel Mod                   
More Ore Stones               
Redstone Pen                  
Additional Lanterns           
GlobalSettings                
Create                        
Create Deco                   
Netherite Cake Mod            
Weapon Throw                  
Macaw's Paintings             
Tumbleweed                    
Customizable Player Models    
Item Borders                  
Decorative Blocks             
Dungeon Crawl                 
Lost and Fished               
Armor Hotswap                 
LazyDFU                       
Bedspreads                    
Farsight mod                  
Wall-Jump!                    
Blueprint                     
Compat O' Plenty              
Panorama                      
3dSkinLayers                  
Villainous Fish AI            
Bundles Unlocked              
Dash                          
CraftingTweaks                
EnchantmentDescriptions       
SwingThroughGrass             
Tool Belt                     
Extract Poison                
Armor Poser                   
Cookietology                  
Move Boats                    
Iceberg                       
Quark                         
mutil                         
Variant Crafting Tables       
Shulker Tooltip               
Nether Gold Veins             
Storage Drawers               
Inventory HUD+(Forge edition) 
Scaffolding power             
Hunter Illager                
Creeper Overhaul              
Extended Creative Inventory   
BetterF3                      
Armor Sound Tweak             
Chisels & bits                
Create Crafts & Additions     
Optifine_

### Logs

https://gist.github.com/Sherane0/c745547d089622367b57cf1918ddabfe

### Mod Version

15.0.0.104 & 15.0.0.105

### Additional information

Optifine version - OptiFine_1.18.1_HD_U_H4

**Comment by Adubbz** [comment]
Signs have already been added to the main release of BOP. Signs O' Plenty is redundant and responsible for this crash.
