### ISSUE TITLE
Just tried to update to latest version now Biomes o Plenty is crashing on start.

### ISSUE THREAD

**Issue by PernDragon** [Glitchfiend/BiomesOPlenty#1985]
### What's the issue you encountered?

I tried to run the latest version of biomes o plenty with only optifine and without optifine.  Minecraft wont run.
I tried going back to the last version only to have the same problem.  I had updated Terrablender as well.  

### How can the issue be reproduced?

Install Biomes o Plenty and run on the latest forge
[crash-2022-03-09_07.37.08-fml.txt](https://github.com/Glitchfiend/BiomesOPlenty/files/8215211/crash-2022-03-09_07.37.08-fml.txt)
[crash-2022-03-09_07.40.17-fml.txt](https://github.com/Glitchfiend/BiomesOPlenty/files/8215213/crash-2022-03-09_07.40.17-fml.txt)
[crash-2022-03-09_07.32.37-fml.txt](https://github.com/Glitchfiend/BiomesOPlenty/files/8215214/crash-2022-03-09_07.32.37-fml.txt)
.

### Logs

[09Mar2022 07:42:17.037] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, perndragon, --version, 1.18.2-forge-40.0.12, --gameDir, C:\Users\sirel\AppData\Roaming\.minecraft, --assetsDir, C:\Users\sirel\AppData\Roaming\.minecraft\assets, --assetIndex, 1.18, --uuid, d6e2e1677df6498c8df2827a55ba7e3a, --accessToken, ????????, --clientId, YjdjMzU1Y2UtYzc3Ny00YzQxLTgzZjktOTY4MmY3NTVjNmU2, --xuid, 2533275021645015, --userType, msa, --versionType, release, --launchTarget, forgeclient, --fml.forgeVersion, 40.0.12, --fml.mcVersion, 1.18.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220228.144236] [09Mar2022 07:42:17.044] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 9.1.3+9.1.3+main.9b69c82a starting: java version 17.0.1 by Microsoft [09Mar2022 07:42:17.282] [main/INFO] [optifine.OptiFineTransformationService/]: OptiFineTransformationService.onLoad [09Mar2022 07:42:17.284] [main/INFO] [optifine.OptiFineTransformationService/]: OptiFine ZIP file URL: union:/C:/Users/sirel/AppData/Roaming/.minecraft/mods/OptiFine_1.18.2_HD_U_H6_pre1.jar%2352!/ [09Mar2022 07:42:17.297] [main/INFO] [optifine.OptiFineTransformationService/]: OptiFine ZIP file: C:\Users\sirel\AppData\Roaming\.minecraft\mods\OptiFine_1.18.2_HD_U_H6_pre1.jar [09Mar2022 07:42:17.300] [main/INFO] [optifine.OptiFineTransformer/]: Target.PRE_CLASS is available [09Mar2022 07:42:17.395] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/sirel/AppData/Roaming/.minecraft/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2314!/ Service=ModLauncher Env=CLIENT [09Mar2022 07:42:17.405] [main/INFO] [optifine.OptiFineTransformationService/]: OptiFineTransformationService.initialize [09Mar2022 07:42:18.575] [main/INFO] [optifine.OptiFineTransformationService/]: OptiFineTransformationService.transformers [09Mar2022 07:42:18.583] [main/INFO] [optifine.OptiFineTransformer/]: Targets: 347 [09Mar2022 07:42:19.134] [main/INFO] [optifine.OptiFineTransformationService/]: additionalClassesLocator: [optifine., net.optifine.] [09Mar2022 07:42:19.706] [main/INFO] [mixin/]: Compatibility level set to JAVA_17 [09Mar2022 07:42:19.722] [main/INFO] [cpw.mods.modlauncher.LaunchServiceHandler/MODLAUNCHER]: Launching target 'forgeclient' with arguments [--version, 1.18.2-forge-40.0.12, --gameDir, C:\Users\sirel\AppData\Roaming\.minecraft, --assetsDir, C:\Users\sirel\AppData\Roaming\.minecraft\assets, --uuid, d6e2e1677df6498c8df2827a55ba7e3a, --username, perndragon, --assetIndex, 1.18, --accessToken, ????????, --clientId, YjdjMzU1Y2UtYzc3Ny00YzQxLTgzZjktOTY4MmY3NTVjNmU2, --xuid, 2533275021645015, --userType, msa, --versionType, release] [09Mar2022 07:42:19.902] [main/WARN] [mixin/]: Error loading class: net/minecraft/world/level/levelgen/StructureSettings (java.lang.ClassNotFoundException: net.minecraft.world.level.levelgen.StructureSettings) [09Mar2022 07:42:19.902] [main/WARN] [mixin/]: @Mixin target net.minecraft.world.level.levelgen.StructureSettings was not found terrablender.mixins.json:MixinStructureSettings [09Mar2022 07:42:20.326] [main/WARN] [mixin/]: Error loading class: net/minecraft/world/level/levelgen/NoiseChunk$NoiseFiller (java.lang.ClassNotFoundException: net.minecraft.world.level.levelgen.NoiseChunk$NoiseFiller) [09Mar2022 07:42:20.329] [main/WARN] [mixin/]: Error loading class: net/minecraft/core/RegistryAccess$RegistryHolder (java.lang.ClassNotFoundException: net.minecraft.core.RegistryAccess$RegistryHolder) [09Mar2022 07:42:20.337] [main/WARN] [mixin/]: Error loading class: net/minecraft/core/RegistryAccess$RegistryHolder (java.lang.ClassNotFoundException: net.minecraft.core.RegistryAccess$RegistryHolder) [09Mar2022 07:42:20.338] [main/WARN] [mixin/]: Error loading class: net/minecraft/core/RegistryAccess$RegistryHolder (java.lang.ClassNotFoundException: net.minecraft.core.RegistryAccess$RegistryHolder) [09Mar2022 07:42:20.338] [main/WARN] [mixin/]: Error loading class: net/minecraft/core/RegistryAccess$RegistryHolder (java.lang.ClassNotFoundException: net.minecraft.core.RegistryAccess$RegistryHolder) [09Mar2022 07:42:20.341] [main/WARN] [mixin/]: Error loading class: net/minecraft/core/RegistryAccess$RegistryHolder (java.lang.ClassNotFoundException: net.minecraft.core.RegistryAccess$RegistryHolder) [09Mar2022 07:42:21.991] [main/FATAL] [mixin/]: Mixin apply failed terrablender_forge.mixins.json:client.MixinMinecraft -> net.minecraft.client.Minecraft: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException @Shadow method doLoadLevel in terrablender_forge.mixins.json:client.MixinMinecraft was not located in the target class net.minecraft.client.Minecraft. Using refmap terrablender.refmap.json org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow method doLoadLevel in terrablender_forge.mixins.json:client.MixinMinecraft was not located in the target class net.minecraft.client.Minecraft. Using refmap terrablender.refmap.json 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachSpecialMethod(MixinPreProcessorStandard.java:442) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachShadowMethod(MixinPreProcessorStandard.java:415) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachMethods(MixinPreProcessorStandard.java:343) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:302) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:280) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] 	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1288) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:292) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] 	at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] 	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] 	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156) ~[modlauncher-9.1.3.jar:9.1.3+9.1.3+main.9b69c82a] 	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-9.1.3.jar:?] 	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-9.1.3.jar:?] 	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-9.1.3.jar:?] 	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:110) ~[securejarhandler-1.0.3.jar:?] 	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$16(ModuleClassLoader.java:216) ~[securejarhandler-1.0.3.jar:?] 	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:226) ~[securejarhandler-1.0.3.jar:?] 	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:216) ~[securejarhandler-1.0.3.jar:?] 	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:132) ~[securejarhandler-1.0.3.jar:?] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] 	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:506) ~[OptiFine_1.18.2_HD_U_H6_pre1.jar%2363!/:?] 	at net.minecraft.CrashReport.m_127526_(CrashReport.java:173) ~[client-1.18.2-20220228.144236-srg.jar%2358!/:?] 	at net.minecraft.CrashReport.m_127529_(CrashReport.java:343) ~[client-1.18.2-20220228.144236-srg.jar%2358!/:?] 	at net.minecraft.client.main.Main.main(Main.java:137) ~[client-1.18.2-20220228.144236-srg.jar%2358!/:?] 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] 	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] 	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.18.2-40.0.12.jar%2316!/:?] 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?] 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?] 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?] 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?] 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?] 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?] 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?] 	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?]

### Mod Version

15.0.0.104 and the one just uplodaed 4 hours ago

### Additional information

non

**Comment by PernDragon** [comment]
problem resolved it's self not sure why
