### ISSUE TITLE
biomes o plenty couldnt load correctly 

### ISSUE THREAD

**Issue by Kattidi4** [Glitchfiend/BiomesOPlenty#2027]
### What's the issue you encountered?

im trying to play on a server with my friends with this mod but when i launch the game it says that the mod couldnt be loaded correctly
![Screenshot (8)](https://user-images.githubusercontent.com/109006688/178127453-fe9d9d99-d030-4af8-9ff9-308ddce08198.png)

### How can the issue be reproduced?

launching the game

### Logs

[02:56:08] [main/INFO]: ModLauncher running: args [--username, qiriInenes, --version, rsg, --gameDir, C:\Users\smajl\AppData\Roaming\.minecraft\versions\rsg, --assetsDir, C:\Users\smajl\AppData\Roaming\.minecraft\assets, --assetIndex, 1.19, --uuid, 05fe23ef-9ca1-11eb-b83c-d45d64bce613, --accessToken, ????????, --clientId, ${clientid}, --xuid, ${auth_xuid}, --userType, mojang, --versionType, release, --width, 925, --height, 530, --launchTarget, forgeclient, --fml.forgeVersion, 41.0.64, --fml.mcVersion, 1.19, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220607.102129] [02:56:08] [main/INFO]: ModLauncher 10.0.1+10.0.1+main.e9521dc3 starting: java version 17.0.3 by Microsoft; OS Windows 10 arch amd64 version 10.0 [02:56:08] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/smajl/AppData/Roaming/.minecraft/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2390!/ Service=ModLauncher Env=CLIENT [02:56:09] [main/INFO]: Found mod file BiomesOPlenty-1.19-17.0.0.141.jar of type MOD with provider {mods folder locator at C:\Users\smajl\AppData\Roaming\.minecraft\versions\rsg\mods} [02:56:09] [main/INFO]: Found mod file TerraBlender-forge-1.19-2.0.0.117.jar of type MOD with provider {mods folder locator at C:\Users\smajl\AppData\Roaming\.minecraft\versions\rsg\mods} [02:56:09] [main/INFO]: Found mod file Towns-and-Towers-1.19-1.7.2.jar of type MOD with provider {mods folder locator at C:\Users\smajl\AppData\Roaming\.minecraft\versions\rsg\mods} [02:56:09] [main/WARN]: Mod file C:\Users\smajl\AppData\Roaming\.minecraft\libraries\net\minecraftforge\fmlcore\1.19-41.0.64\fmlcore-1.19-41.0.64.jar is missing mods.toml file [02:56:09] [main/WARN]: Mod file C:\Users\smajl\AppData\Roaming\.minecraft\libraries\net\minecraftforge\javafmllanguage\1.19-41.0.64\javafmllanguage-1.19-41.0.64.jar is missing mods.toml file [02:56:09] [main/WARN]: Mod file C:\Users\smajl\AppData\Roaming\.minecraft\libraries\net\minecraftforge\lowcodelanguage\1.19-41.0.64\lowcodelanguage-1.19-41.0.64.jar is missing mods.toml file [02:56:09] [main/WARN]: Mod file C:\Users\smajl\AppData\Roaming\.minecraft\libraries\net\minecraftforge\mclanguage\1.19-41.0.64\mclanguage-1.19-41.0.64.jar is missing mods.toml file [02:56:09] [main/INFO]: Found mod file fmlcore-1.19-41.0.64.jar of type LIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@5f5b5ca4 [02:56:09] [main/INFO]: Found mod file javafmllanguage-1.19-41.0.64.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@5f5b5ca4 [02:56:09] [main/INFO]: Found mod file lowcodelanguage-1.19-41.0.64.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@5f5b5ca4 [02:56:09] [main/INFO]: Found mod file mclanguage-1.19-41.0.64.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@5f5b5ca4 [02:56:09] [main/INFO]: Found mod file client-1.19-20220607.102129-srg.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@5f5b5ca4 [02:56:09] [main/INFO]: Found mod file forge-1.19-41.0.64-universal.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@5f5b5ca4 [02:56:09] [main/INFO]: No dependencies to load found. Skipping! [02:56:13] [main/INFO]: Compatibility level set to JAVA_17 [02:56:13] [main/INFO]: Launching target 'forgeclient' with arguments [--version, rsg, --gameDir, C:\Users\smajl\AppData\Roaming\.minecraft\versions\rsg, --assetsDir, C:\Users\smajl\AppData\Roaming\.minecraft\assets, --uuid, 05fe23ef-9ca1-11eb-b83c-d45d64bce613, --username, qiriInenes, --assetIndex, 1.19, --accessToken, ????????, --clientId, ${clientid}, --xuid, ${auth_xuid}, --userType, mojang, --versionType, release, --width, 925, --height, 530] [02:56:24] [pool-3-thread-1/INFO]: Building optimized datafixer [02:56:35] [Render thread/WARN]: Assets URL 'union:/C:/Users/smajl/AppData/Roaming/.minecraft/libraries/net/minecraft/client/1.19-20220607.102129/client-1.19-20220607.102129-srg.jar%23146!/assets/.mcassetsroot' uses unexpected schema [02:56:35] [Render thread/WARN]: Assets URL 'union:/C:/Users/smajl/AppData/Roaming/.minecraft/libraries/net/minecraft/client/1.19-20220607.102129/client-1.19-20220607.102129-srg.jar%23146!/data/.mcassetsroot' uses unexpected schema [02:56:35] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD' [02:56:37] [Render thread/ERROR]: Failed to verify authentication com.mojang.authlib.exceptions.InvalidCredentialsException: Status: 401 	at com.mojang.authlib.exceptions.MinecraftClientHttpException.toAuthenticationException(MinecraftClientHttpException.java:56) ~[authlib-3.5.41.jar%23120!/:?] 	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.fetchProperties(YggdrasilUserApiService.java:140) ~[authlib-3.5.41.jar%23120!/:?] 	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.<init>(YggdrasilUserApiService.java:47) ~[authlib-3.5.41.jar%23120!/:?] 	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.createUserApiService(YggdrasilAuthenticationService.java:158) ~[authlib-3.5.41.jar%23120!/:?] 	at net.minecraft.client.Minecraft.m_193585_(Minecraft.java:614) ~[client-1.19-20220607.102129-srg.jar%23146!/:?] 	at net.minecraft.client.Minecraft.<init>(Minecraft.java:392) ~[client-1.19-20220607.102129-srg.jar%23146!/:?] 	at net.minecraft.client.main.Main.main(Main.java:169) ~[client-1.19-20220607.102129-srg.jar%23146!/:?] 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] 	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] 	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19-41.0.64.jar%2393!/:?] 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.1.jar%2381!/:?] 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.1.jar%2381!/:?] 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.1.jar%2381!/:?] 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.1.jar%2381!/:?] 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.1.jar%2381!/:?] 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.1.jar%2381!/:?] 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.1.jar%2381!/:?] 	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.1.jar:?] Caused by: com.mojang.authlib.exceptions.MinecraftClientHttpException: Status: 401 	at com.mojang.authlib.minecraft.client.MinecraftClient.readInputStream(MinecraftClient.java:85) ~[authlib-3.5.41.jar%23120!/:?] 	at com.mojang.authlib.minecraft.client.MinecraftClient.get(MinecraftClient.java:48) ~[authlib-3.5.41.jar%23120!/:?] 	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.fetchProperties(YggdrasilUserApiService.java:121) ~[authlib-3.5.41.jar%23120!/:?] 	... 18 more [02:56:37] [Render thread/INFO]: Setting user: qiriInenes [02:56:38] [Render thread/INFO]: Backend library: LWJGL version 3.3.1 build 7 [02:56:40] [modloading-worker-0/INFO]: Forge mod loading, version 41.0.64, for MC 1.19 with MCP 20220607.102129 [02:56:40] [modloading-worker-0/INFO]: MinecraftForge v41.0.64 Initialized [02:56:41] [modloading-worker-0/ERROR]: Failed to register automatic subscribers. ModID: biomesoplenty, class biomesoplenty.core.BiomesOPlenty java.lang.NoClassDefFoundError: net/minecraftforge/client/event/ColorHandlerEvent$Item 	at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?] 	at java.lang.Class.privateGetDeclaredMethods(Class.java:3402) ~[?:?] 	at java.lang.Class.privateGetPublicMethods(Class.java:3427) ~[?:?] 	at java.lang.Class.getMethods(Class.java:2019) ~[?:?] 	at net.minecraftforge.eventbus.EventBus.registerClass(EventBus.java:75) ~[eventbus-6.0.0.jar%2378!/:?] 	at net.minecraftforge.eventbus.EventBus.register(EventBus.java:118) ~[eventbus-6.0.0.jar%2378!/:?] 	at net.minecraftforge.fml.javafmlmod.AutomaticEventSubscriber.lambda$inject$6(AutomaticEventSubscriber.java:61) ~[javafmllanguage-1.19-41.0.64.jar%23148!/:?] 	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?] 	at net.minecraftforge.fml.javafmlmod.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:48) ~[javafmllanguage-1.19-41.0.64.jar%23148!/:?] 	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:78) ~[javafmllanguage-1.19-41.0.64.jar%23148!/:?] 	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19-41.0.64.jar%23147!/:?] 	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?] 	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) [?:?] 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?] 	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?] 	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?] 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?] 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?] Caused by: java.lang.ClassNotFoundException: net.minecraftforge.client.event.ColorHandlerEvent$Item 	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:141) ~[securejarhandler-2.0.3.jar:?] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] 	... 18 more [02:56:41] [Render thread/FATAL]: Failed to complete lifecycle event CONSTRUCT, 1 errors found [02:56:42] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.sound.SoundEngineLoadEvent to a broken mod state [02:56:43] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterColorHandlersEvent$Block to a broken mod state [02:56:43] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterColorHandlersEvent$Item to a broken mod state [02:56:44] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterParticleProvidersEvent to a broken mod state [02:56:45] [Render thread/INFO]: Narrator library for x64 successfully loaded [02:56:45] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterClientReloadListenersEvent to a broken mod state [02:56:45] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$RegisterLayerDefinitions to a broken mod state [02:56:45] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$RegisterRenderers to a broken mod state [02:56:45] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterTextureAtlasSpriteLoadersEvent to a broken mod state [02:56:45] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterClientTooltipComponentFactoriesEvent to a broken mod state [02:56:45] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterEntitySpectatorShadersEvent to a broken mod state [02:56:45] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterKeyMappingsEvent to a broken mod state [02:56:45] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterRecipeBookCategoriesEvent to a broken mod state [02:56:45] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterGuiOverlaysEvent to a broken mod state [02:56:45] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterDimensionSpecialEffectsEvent to a broken mod state [02:56:45] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterNamedRenderTypesEvent to a broken mod state [02:56:46] [Worker-Main-4/ERROR]: Failed to retrieve profile key pair java.io.IOException: Could not retrieve profile key pair 	at net.minecraft.client.multiplayer.ProfileKeyPairManager.m_233789_(ProfileKeyPairManager.java:137) ~[client-1.19-20220607.102129-srg.jar%23146!/:?] 	at net.minecraft.client.multiplayer.ProfileKeyPairManager.m_233796_(ProfileKeyPairManager.java:63) ~[client-1.19-20220607.102129-srg.jar%23146!/:?] 	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) [?:?] 	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) [?:?] 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?] 	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?] 	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?] 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?] 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?] [02:56:46] [Render thread/INFO]: Reloading ResourceManager: Default [02:56:46] [Worker-Main-5/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.ModelEvent$RegisterGeometryLoaders to a broken mod state [02:56:48] [Worker-Main-6/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state [02:56:55] [Worker-Main-4/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state [02:57:06] [Worker-Main-5/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.ModelEvent$RegisterAdditional to a broken mod state [02:57:07] [Worker-Main-5/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state [02:57:07] [Worker-Main-8/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state [02:57:13] [Worker-Main-5/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state [02:57:13] [Worker-Main-5/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state [02:57:13] [Worker-Main-5/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state [02:57:13] [Worker-Main-5/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state [02:57:14] [Worker-Main-5/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state [02:57:14] [Worker-Main-5/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state [02:57:14] [Render thread/WARN]: Missing sound for event: minecraft:item.goat_horn.play [02:57:14] [Render thread/WARN]: Missing sound for event: minecraft:entity.goat.screaming.horn_break [02:57:14] [Render thread/INFO]: OpenAL initialized on device OpenAL Soft on Speakers (USB PnP Sound Device) [02:57:14] [Render thread/INFO]: Sound engine started [02:57:14] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.sound.SoundEngineLoadEvent to a broken mod state [02:57:15] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/blocks.png-atlas [02:57:15] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state [02:57:15] [Render thread/INFO]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas [02:57:15] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state [02:57:15] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/banner_patterns.png-atlas [02:57:15] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state [02:57:15] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/shield_patterns.png-atlas [02:57:15] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state [02:57:15] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas [02:57:15] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state [02:57:15] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas [02:57:15] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state [02:57:15] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas [02:57:15] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state [02:57:17] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.ModelEvent$BakingCompleted to a broken mod state [02:57:18] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state [02:57:18] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state [02:57:18] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state [02:57:18] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state [02:57:18] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state [02:57:18] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state [02:57:18] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state [02:57:18] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state [02:57:18] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state [02:57:18] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state [02:57:18] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state [02:57:18] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state [02:57:18] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state [02:57:18] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state [02:57:18] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state [02:57:18] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state [02:57:18] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state [02:57:18] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state [02:57:18] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state [02:57:18] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state [02:57:18] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state [02:57:18] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$CreateSkullModels to a broken mod state [02:57:18] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.EntityRenderersEvent$AddLayers to a broken mod state [02:57:20] [Render thread/WARN]: Shader rendertype_entity_translucent_emissive could not find sampler named Sampler2 in the specified shader program. [02:57:22] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.RegisterShadersEvent to a broken mod state [02:57:22] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas [02:57:22] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state [02:57:22] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas [02:57:22] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state [02:57:22] [Render thread/INFO]: Created: 128x128x0 minecraft:textures/atlas/mob_effects.png-atlas [02:57:22] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state [02:57:23] [Render thread/FATAL]: Preparing crash report with UUID e37aa699-3e02-4de1-89ec-3e883e2965c4 [02:57:23] [Render thread/FATAL]: Crash report saved to C:\Users\smajl\AppData\Roaming\.minecraft\versions\rsg\crash-reports\crash-2022-07-10_02.57.23-fml.txt [02:57:23] [Render thread/FATAL]: Preparing crash report with UUID 2ed7c2f2-477a-4c23-b3be-8da5e6b1f6bd [03:00:47] [Worker-Bootstrap-1/INFO]: 4256 Datafixer optimizations took 263047 milliseconds

### Mod Version

1.19-17.0.0.141

**Comment by Adubbz** [comment]
You need to update the mod.

**Comment by Kattidi4** [comment]
Thats the latest version i did everything i could to make it work but i
dont know what happening

**Comment by Adubbz** [comment]
That is not the latest version. The latest is 17.0.0.142

**Comment by Kattidi4** [comment]
The issue wasn’t the biomes o’ plenty version turns out it was the forge
version that messed it up

**Comment by Kattidi4** [comment]
Im doing it on tlauncher they are using the same version but it works for
them, im gonna try again tomorrow and if it doesn’t work I don’t know what
else to do
