### ISSUE TITLE
BiomesOPlenty Not Opening On Pebblehost

### ISSUE THREAD

**Issue by UnlockedGamerdDL** [Glitchfiend/BiomesOPlenty#2060]
### What's the issue you encountered?

So I downloaded a few mods onto my multiplayer Pebblehost server such as BiomesOPlenty and TerraBlender. I am currently using Forge 1.19.2. When I try and start/restart my server, I am given this command message -
22.11 02:00:48 [Server] [INFO] BiomesOPlenty-1.19.2-17.1.1.162-deobf.jar         |Biomes O' Plenty              |biomesoplenty                 |0.0NONE             |[ERROR]     |Manifest: NOSIGNATURE

I am new to Pebblehost and mods as well, so I have no idea how to fix this issue. It seems to work with other mods, just not BiomesOPlenty. Any idea how to fix this?

### How can the issue be reproduced?

This issue can be reproduced simply by installing BiomesOPlenty to a Pebblehost server, and starting/restarting the server.

### Logs

[22Nov2022 02:00:39.235] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--launchTarget, forgeserver, --fml.forgeVersion, 43.1.7, --fml.mcVersion, 1.19.2, --fml.mcpVersion, 20220805.130853] [22Nov2022 02:00:39.242] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 10.0.8+10.0.8+main.0ef7e830 starting: java version 17 by AdoptOpenJDK; OS Linux arch amd64 version 4.18.0-348.2.1.el8_5.x86_64 [22Nov2022 02:00:39.396] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/home/minecraft/multicraft/servers/server400281/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2363!/ Service=ModLauncher Env=SERVER [22Nov2022 02:00:39.692] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file /home/minecraft/multicraft/servers/server400281/libraries/net/minecraftforge/fmlcore/1.19.2-43.1.7/fmlcore-1.19.2-43.1.7.jar is missing mods.toml file [22Nov2022 02:00:39.695] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file /home/minecraft/multicraft/servers/server400281/libraries/net/minecraftforge/javafmllanguage/1.19.2-43.1.7/javafmllanguage-1.19.2-43.1.7.jar is missing mods.toml file [22Nov2022 02:00:39.707] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file /home/minecraft/multicraft/servers/server400281/libraries/net/minecraftforge/lowcodelanguage/1.19.2-43.1.7/lowcodelanguage-1.19.2-43.1.7.jar is missing mods.toml file [22Nov2022 02:00:39.710] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file /home/minecraft/multicraft/servers/server400281/libraries/net/minecraftforge/mclanguage/1.19.2-43.1.7/mclanguage-1.19.2-43.1.7.jar is missing mods.toml file [22Nov2022 02:00:39.786] [main/INFO] [net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator/]: No dependencies to load found. Skipping! [22Nov2022 02:00:41.348] [main/INFO] [mixin/]: Compatibility level set to JAVA_17 [22Nov2022 02:00:41.360] [main/INFO] [cpw.mods.modlauncher.LaunchServiceHandler/MODLAUNCHER]: Launching target 'forgeserver' with arguments [] [22Nov2022 02:00:45.668] [main/INFO] [net.minecraft.util.datafix.DataFixers/]: Building unoptimized datafixer [22Nov2022 02:00:47.998] [modloading-worker-0/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Failed to create mod instance. ModID: biomesoplenty, class biomesoplenty.core.BiomesOPlenty java.lang.NoSuchFieldError: BIOME_REGISTRY 	at biomesoplenty.core.BiomesOPlenty.<clinit>(BiomesOPlenty.java:41) ~[BiomesOPlenty-1.19.2-17.1.1.162-deobf.jar%2399!/:?] 	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] 	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78) ~[?:?] 	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] 	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] 	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] 	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19.2-43.1.7.jar%23105!/:?] 	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.2-43.1.7.jar%23104!/:?] 	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?] 	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) [?:?] 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?] 	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1176) [?:?] 	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1647) [?:?] 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1614) [?:?] 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?] [22Nov2022 02:00:48.035] [modloading-worker-0/INFO] [net.minecraftforge.common.ForgeMod/FORGEMOD]: Forge mod loading, version 43.1.7, for MC 1.19.2 with MCP 20220805.130853 [22Nov2022 02:00:48.043] [modloading-worker-0/INFO] [net.minecraftforge.common.MinecraftForge/FORGE]: MinecraftForge v43.1.7 Initialized [22Nov2022 02:00:48.253] [main/FATAL] [net.minecraftforge.fml.ModLoader/LOADING]: Failed to complete lifecycle event CONSTRUCT, 1 errors found [22Nov2022 02:00:48.345] [main/FATAL] [net.minecraftforge.common.ForgeMod/]: Preparing crash report with UUID 29b9d664-6907-4791-af55-ec2eb1c19b33 [22Nov2022 02:00:48.345] [main/FATAL] [net.minecraftforge.server.loading.ServerModLoader/]: Crash report saved to ./crash-reports/crash-2022-11-22_02.00.48-fml.txt [22Nov2022 02:00:48.347] [main/FATAL] [net.minecraftforge.common.ForgeMod/]: Preparing crash report with UUID 4bfefdc8-9938-410c-9738-6d4da002cc71 [22Nov2022 02:00:48.348] [main/ERROR] [net.minecraft.server.Main/FATAL]: Failed to start the minecraft server net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [ 	Biomes O' Plenty (biomesoplenty) has failed to load correctly §7java.lang.NoSuchFieldError: BIOME_REGISTRY ] 	at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:243) ~[fmlcore-1.19.2-43.1.7.jar%23104!/:?] 	at net.minecraftforge.fml.ModLoader.lambda$dispatchAndHandleError$24(ModLoader.java:208) ~[fmlcore-1.19.2-43.1.7.jar%23104!/:?] 	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?] 	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:208) ~[fmlcore-1.19.2-43.1.7.jar%23104!/:?] 	at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$14(ModLoader.java:185) ~[fmlcore-1.19.2-43.1.7.jar%23104!/:?] 	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] 	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:185) ~[fmlcore-1.19.2-43.1.7.jar%23104!/:?] 	at net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:32) ~[forge-1.19.2-43.1.7-universal.jar%23108!/:?] 	at net.minecraft.server.Main.main(Main.java:113) ~[server-1.19.2-20220805.130853-srg.jar%23103!/:?] 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?] 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] 	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] 	at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:29) ~[fmlloader-1.19.2-43.1.7.jar%2367!/:?] 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2354!/:?] 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2354!/:?] 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2354!/:?] 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2354!/:?] 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2354!/:?] 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2354!/:?] 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2354!/:?]

### Mod Version

1.19.2

**Comment by Adubbz** [comment]
You have downloaded the wrong version of the mod. Use the standard version, not the deobf one.
