### ISSUE TITLE
Nasty bug killing world save file

### ISSUE THREAD

**Issue by uhloin** [Glitchfiend/BiomesOPlenty#2066]
### What's the issue you encountered?

Yesterday my old world stops to load. Error log (stdout) contains very long stacktrace started from:

[23:11:42] [Render thread/ERROR] [minecraft/LevelStorageSource]: Exception reading C:\Users\xen\AppData\Roaming\.minecraft\saves\Dark\level.dat
java.lang.RuntimeException: Tried to read NBT tag with too high complexity, depth > 512
	at net.minecraft.nbt.CompoundTag$1.m_7300_(CompoundTag.java:34) ~[client-1.19.2-20220805.130853-srg.jar%23218!/:?] {re:classloading}
	at net.minecraft.nbt.CompoundTag$1.m_7300_(CompoundTag.java:30) ~[client-1.19.2-20220805.130853-srg.jar%23218!/:?] {re:classloading}

I started to search a parser for NBT-file level.dat to find what happened but could not find appropriate utility to discover a problem. As result I was forced to write parser by myself. It found "nasty nesting" in NBT with nesting depth 512 and more. Then I checked my older backup for the same world which loaded without errors. I found it also has nasty nesting but less than critical level 512.

This nesting always started from Compound tag "biomesoplenty". After thousands of tags it increased by 1 and nested tag "biomesoplenty" is started. And more and more. May be it is increased every save or some other event. Text result of parse is very big so I send you only a piece where "biomesoplenty" started and increased by +3 in loop. See strings biomesoplenty=Compound{9} ... biomesoplenty=Compound{10} ... biomesoplenty=Compound{11}

And sorry I cannot install MC 1.19.3 but my version is next from last (17.1.2.492) and probably this problem is older.
[level.zip](https://github.com/Glitchfiend/BiomesOPlenty/files/10229929/level.zip)

### How can the issue be reproduced?

-

### Mod Version

17.1.2.492

**Comment by uhloin** [comment]
To fix my save I used NBTExplorer and deleted whole branches surface_rule:
Data/WorldGenSettings/dimensions/minecraft.overworld/generator/settings/surface_rule
Data/WorldGenSettings/dimensions/minecraft.the_end/generator/settings/surface_rule
Data/WorldGenSettings/dimensions/minecraft.the_nether/generator/settings/surface_rule

I do not sure if I done right thing but looks like new biomes successfully generated in the not explored areas for BOP, BYG and Ars Nouveau.

**Comment by uhloin** [comment]
After read about surface_rule-s I understood It was bad idea. 

Next my attempt was to create new world and use NBTExplorer.exe to copy WorldGenSettings from new world to old. Looks like after this branch does not grow recursively.

**Comment by uhloin** [comment]
I found cause of issue in other mod (Alex's mobs)
