### ISSUE TITLE
Biome O plenty bug

### ISSUE THREAD

**Issue by BENOITSKINPVP** [Glitchfiend/BiomesOPlenty#2246]
### What's the issue you encountered?

![image](https://github.com/user-attachments/assets/318b16f7-77ee-45f9-8acc-2b59f37c76d6)
 cant do nothing I tried literaly everything

### How can the issue be reproduced?

[latest log.txt](https://github.com/user-attachments/files/16431456/latest.log.txt)
[crash-2024-07-30_21.10.57-fml.txt](https://github.com/user-attachments/files/16431469/crash-2024-07-30_21.10.57-fml.txt)

### Logs

[30juil.2024 21:30:34.937] [main/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Caught exception during event RegistryEvent.Register<minecraft:worldgen/biome> dispatch for modid biomesoplenty java.lang.NullPointerException: null 	at biomesoplenty.common.biome.BiomeRegistry.configureTechnicalBiomes(BiomeRegistry.java:149) ~[?:?] 	at biomesoplenty.init.ModBiomes.registerBiomes(ModBiomes.java:141) ~[?:?] 	at net.minecraftforge.eventbus.ASMEventHandler_298_ModBiomes_registerBiomes_Register.invoke(.dynamic) ~[?:?] 	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] 	at net.minecraftforge.eventbus.EventBus$$Lambda$3200/1493755606.invoke(Unknown Source) ~[?:?] 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] 	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:106) [?:36.2] 	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:107) [?:?] 	at net.minecraftforge.fml.ModContainer$$Lambda$3380/1469692066.run(Unknown Source) [?:?] 	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) [?:1.8.0_51] 	at net.minecraftforge.fml.ModWorkManager$SyncExecutor.driveOne(ModWorkManager.java:42) [?:?] 	at net.minecraftforge.fml.ModWorkManager$DrivenExecutor.drive(ModWorkManager.java:26) [?:?] 	at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:235) [?:?] 	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:222) [?:?] 	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:188) [?:?] 	at net.minecraftforge.fml.client.ClientModLoader.lambda$begin$1(ClientModLoader.java:89) [?:?] 	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2971/438793128.run(Unknown Source) [?:?] 	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$4(ClientModLoader.java:109) [?:?] 	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2972/2024860730.run(Unknown Source) [?:?] 	at net.minecraftforge.fml.client.ClientModLoader.begin(ClientModLoader.java:89) [?:?] 	at net.minecraft.client.Minecraft.<init>(Minecraft.java:437) [?:?] 	at net.minecraft.client.main.Main.main(Main.java:149) [?:?] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] 	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:37) [forge-1.16.5-36.2.35.jar:36.2] 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$476/1910034407.call(Unknown Source) [forge-1.16.5-36.2.35.jar:36.2] 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?] 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?] 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?] 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?] 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?] [30juil.2024 21:30:35.173] [main/WARN] [net.minecraftforge.registries.ForgeRegistry/REGISTRIES]: Registry minecraft:worldgen/biome: The object minecraft:the_end has been registered twice for the same name minecraft:the_end. [30juil.2024 21:30:35.173] [main/WARN] [net.minecraftforge.registries.ForgeRegistry/REGISTRIES]: Registry minecraft:worldgen/biome: The object minecraft:end_barrens has been registered twice for the same name minecraft:end_barrens. [30juil.2024 21:30:35.173] [main/WARN] [net.minecraftforge.registries.ForgeRegistry/REGISTRIES]: Registry minecraft:worldgen/biome: The object minecraft:small_end_islands has been registered twice for the same name minecraft:small_end_islands. [30juil.2024 21:30:35.173] [main/WARN] [net.minecraftforge.registries.ForgeRegistry/REGISTRIES]: Registry minecraft:worldgen/biome: The object minecraft:end_midlands has been registered twice for the same name minecraft:end_midlands. [30juil.2024 21:30:35.173] [main/WARN] [net.minecraftforge.registries.ForgeRegistry/REGISTRIES]: Registry minecraft:worldgen/biome: The object minecraft:end_highlands has been registered twice for the same name minecraft:end_highlands. [30juil.2024 21:30:35.501] [main/FATAL] [net.minecraftforge.registries.GameData/]: Detected errors during registry event dispatch, rolling back to VANILLA state [30juil.2024 21:30:36.181] [main/FATAL] [net.minecraftforge.registries.GameData/]: Detected errors during registry event dispatch, roll back to VANILLA complete [30juil.2024 21:30:36.185] [main/FATAL] [net.minecraftforge.fml.ModLoader/LOADING]: Failed to complete lifecycle event LOAD_REGISTRIES, 1 errors found [30juil.2024 21:30:36.206] [main/WARN] [net.minecraft.client.GameSettings/]: Removed resource pack programmer_art from options because it doesn't seem to exist anymore [30juil.2024 21:30:36.226] [main/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.sound.SoundLoadEvent to a broken mod state [30juil.2024 21:30:36.255] [main/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.ColorHandlerEvent$Block to a broken mod state [30juil.2024 21:30:36.256] [main/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.ColorHandlerEvent$Item to a broken mod state [30juil.2024 21:30:36.603] [main/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.ParticleFactoryRegisterEvent to a broken mod state [30juil.2024 21:30:36.628] [main/INFO] [com.mojang.text2speech.NarratorWindows/]: Narrator library for x64 successfully loaded [30juil.2024 21:30:36.688] [main/INFO] [net.minecraft.resources.SimpleReloadableResourceManager/]: Reloading ResourceManager: Default [30juil.2024 21:30:36.695] [main/INFO] [net.optifine.Config/]: [OptiFine] *** Reloading textures *** [30juil.2024 21:30:36.695] [main/INFO] [net.optifine.Config/]: [OptiFine] Resource packs: Default [30juil.2024 21:30:36.752] [main/INFO] [net.optifine.reflect.Reflector/]: [OptiFine] *** Reflector Forge *** [30juil.2024 21:30:36.753] [main/INFO] [net.optifine.Log/]: [OptiFine] (Reflector) Class not present: mods.betterfoliage.client.BetterFoliageClient [30juil.2024 21:30:36.771] [Worker-Main-9/INFO] [net.optifine.Config/]: [OptiFine] Multitexture: false [30juil.2024 21:30:36.771] [Worker-Main-13/INFO] [net.optifine.Config/]: [OptiFine] Multitexture: false [30juil.2024 21:30:36.771] [Worker-Main-11/INFO] [net.optifine.Config/]: [OptiFine] Multitexture: false [30juil.2024 21:30:36.772] [Worker-Main-8/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.ModelRegistryEvent to a broken mod state [30juil.2024 21:30:36.776] [Worker-Main-13/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state [30juil.2024 21:30:36.776] [Worker-Main-11/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state [30juil.2024 21:30:36.776] [Worker-Main-9/ERROR] [net.minecraftforge.fml.ModLoader/]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state [30juil.2024 21:30:36.801] [main/INFO] [net.optifine.Log/]: [OptiFine] (Reflector) Field not present: net.minecraftforge.client.model.pipeline.LightUtil.itemConsumer [30juil.2024 21:30:36.802] [main/INFO] [net.optifine.Log/]: [OptiFine] (Reflector) Field not present: net.minecraftforge.client.model.pipeline.LightUtil.tessellator [30juil.2024 21:30:36.806] [main/INFO] [net.optifine.Log/]: [OptiFine] (Reflector) Class not present: net.minecraftforge.fml.common.ModContainer [30juil.2024 21:30:36.821] [main/INFO] [net.optifine.reflect.Reflector/]: [OptiFine] *** Reflector Vanilla *** [30juil.2024 21:30:38.850] [Worker-Main-8/WARN] [net.minecraft.client.renderer.model.ModelBakery/]: Unable to load model: 'mowziesmobs:barakoa_mask_misery_frame#inventory' referenced from: mowziesmobs:barakoa_mask_misery_frame#inventory: {} [30juil.2024 21:30:38.851] [Worker-Main-8/WARN] [net.minecraft.client.renderer.model.ModelBakery/]: java.io.FileNotFoundException: mowziesmobs:models/item/barakoa_mask_misery_frame.json [30juil.2024 21:30:38.851] [Worker-Main-8/WARN] [net.minecraft.client.renderer.model.ModelBakery/]: Unable to load model: 'mowziesmobs:barakoa_mask_rage_frame#inventory' referenced from: mowziesmobs:barakoa_mask_rage_frame#inventory: {} [30juil.2024 21:30:38.851] [Worker-Main-8/WARN] [net.minecraft.client.renderer.model.ModelBakery/]: java.io.FileNotFoundException: mowziesmobs:models/item/barakoa_mask_rage_frame.json [30juil.2024 21:30:38.851] [Worker-Main-8/WARN] [net.minecraft.client.renderer.model.ModelBakery/]: Unable to load model: 'mowziesmobs:barakoa_mask_bliss_frame#inventory' referenced from: mowziesmobs:barakoa_mask_bliss_frame#inventory: {} [30juil.2024 21:30:38.851] [Worker-Main-8/WARN] [net.minecraft.client.renderer.model.ModelBakery/]: java.io.FileNotFoundException: mowziesmobs:models/item/barakoa_mask_bliss_frame.json [30juil.2024 21:30:38.851] [Worker-Main-8/WARN] [net.minecraft.client.renderer.model.ModelBakery/]: Unable to load model: 'mowziesmobs:barakoa_mask_fear_frame#inventory' referenced from: mowziesmobs:barakoa_mask_fear_frame#inventory: {} [30juil.2024 21:30:38.851] [Worker-Main-8/WARN] [net.minecraft.client.renderer.model.ModelBakery/]: java.io.FileNotFoundException: mowziesmobs:models/item/barakoa_mask_fear_frame.json [30juil.2024 21:30:38.851] [Worker-Main-8/WARN] [net.minecraft.client.renderer.model.ModelBakery/]: Unable to load model: 'mowziesmobs:wrought_axe_in_hand#inventory' referenced from: mowziesmobs:wrought_axe_in_hand#inventory: {} [30juil.2024 21:30:38.851] [Worker-Main-8/WARN] [net.minecraft.client.renderer.model.ModelBakery/]: java.io.FileNotFoundException: mowziesmobs:models/item/wrought_axe_in_hand.json [30juil.2024 21:30:38.851] [Worker-Main-8/WARN] [net.minecraft.client.renderer.model.ModelBakery/]: Unable to load model: 'mowziesmobs:barakoa_mask_fury_frame#inventory' referenced from: mowziesmobs:barakoa_mask_fury_frame#inventory: {} [30juil.2024 21:30:38.851] [Worker-Main-8/WARN] [net.minecraft.client.renderer.model.ModelBakery/]: java.io.FileNotFoundException: mowziesmobs:models/item/barakoa_mask_fury_frame.json [30juil.2024 21:30:39.070] [Worker-Main-8/INFO] [net.optifine.Config/]: [OptiFine] Multitexture: false

### Mod Version

1.16.5

**Comment by Forstride** [comment]
You likely just need to delete your existing BOP configs
