### ISSUE TITLE
Game crashes when player put a boat on the ground

### ISSUE THREAD

**Issue by Sailorxxvx** [Glitchfiend/BiomesOPlenty#2288]
### What's the issue you encountered?

1.21.1 whenever player put a boat on the ground, the game crashes.

### How can the issue be reproduced?

placing any boat on the ground.

### Logs

Description: Unexpected error  java.lang.IllegalStateException: Entity class net.minecraft.world.entity.vehicle.Boat has not defined synched data value 15 	at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.syncher.SynchedEntityData$Builder.build(SynchedEntityData.java:167) ~[client-1.21.1-20240808.144430-srg.jar%23325!/:?] {re:classloading} 	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.entity.Entity.<init>(Entity.java:267) ~[client-1.21.1-20240808.144430-srg.jar%23325!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:cupboard.mixins.json:EntityLoadMixin from mod cupboard,pl:mixin:APP:bookshelf.mixins.json:access.entity.AccessorEntity from mod bookshelf,pl:mixin:APP:balm.neoforge.mixins.json:EntityMixin from mod balm,pl:mixin:APP:curios.mixins.json:AccessorEntity from mod curios,pl:mixin:APP:touhou_little_maid.mixins.json:EntityMixin from mod touhou_little_maid,pl:mixin:APP:icarus.mixins.json:EntityMixin from mod icarus,pl:mixin:APP:kiwi.mixins.json:customization.sit.EntityMixin from mod kiwi,pl:mixin:APP:physicsmod.mixins.json:MixinEntity from mod physicsmod,pl:mixin:APP:physicsmod.mixins.json:ocean.MixinEntity from mod physicsmod,pl:mixin:APP:physicsmod.mixins.json:item.MixinEntity from mod physicsmod,pl:mixin:A} 	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.entity.vehicle.VehicleEntity.<init>(VehicleEntity.java:24) ~[client-1.21.1-20240808.144430-srg.jar%23325!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B} 	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.entity.vehicle.Boat.<init>(Boat.java:94) ~[client-1.21.1-20240808.144430-srg.jar%23325!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:doapi.mixins.json:boat.MixinBoatEntity from mod doapi,pl:mixin:APP:physicsmod.mixins.json:ocean.MixinBoat from mod physicsmod,pl:mixin:A} 	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.entity.vehicle.Boat.<init>(Boat.java:99) ~[client-1.21.1-20240808.144430-srg.jar%23325!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:doapi.mixins.json:boat.MixinBoatEntity from mod doapi,pl:mixin:APP:physicsmod.mixins.json:ocean.MixinBoat from mod physicsmod,pl:mixin:A} 	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.item.BoatItem.getBoat(BoatItem.java:81) ~[client-1.21.1-20240808.144430-srg.jar%23325!/:?] {re:classloading} 	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.item.BoatItem.use(BoatItem.java:59) ~[client-1.21.1-20240808.144430-srg.jar%23325!/:?] {re:classloading} 	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.item.ItemStack.use(ItemStack.java:391) ~[client-1.21.1-20240808.144430-srg.jar%23325!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:glitchcore.mixins.json:MixinItemStack from mod glitchcore,pl:mixin:APP:enchdesc.mixins.json:patch.MixinItemStack from mod enchdesc,pl:mixin:A} 	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.multiplayer.MultiPlayerGameMode.lambda$useItem$5(MultiPlayerGameMode.java:387) ~[client-1.21.1-20240808.144430-srg.jar%23325!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A} 	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.multiplayer.MultiPlayerGameMode.startPrediction(MultiPlayerGameMode.java:264) ~[client-1.21.1-20240808.144430-srg.jar%23325!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A} 	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.multiplayer.MultiPlayerGameMode.useItem(MultiPlayerGameMode.java:371) ~[client-1.21.1-20240808.144430-srg.jar%23325!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A} 	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.Minecraft.startUseItem(Minecraft.java:1766) ~[client-1.21.1-20240808.144430-srg.jar%23325!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A} 	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.Minecraft.handleKeybinds(Minecraft.java:2023) ~[client-1.21.1-20240808.144430-srg.jar%23325!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A} 	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.Minecraft.tick(Minecraft.java:1837) ~[client-1.21.1-20240808.144430-srg.jar%23325!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A} 	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.Minecraft.runTick(Minecraft.java:1161) ~[client-1.21.1-20240808.144430-srg.jar%23325!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A} 	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.Minecraft.run(Minecraft.java:807) ~[client-1.21.1-20240808.144430-srg.jar%23325!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A} 	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.main.Main.main(Main.java:230) ~[client-1.21.1-20240808.144430-srg.jar%23325!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:physicsmod.mixins.json:MixinMain from mod physicsmod,pl:mixin:A,pl:runtimedistcleaner:A} 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?] {} 	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?] {} 	at MC-BOOTSTRAP/fml_loader@4.0.29/net.neoforged.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:136) ~[loader-4.0.29.jar%23174!/:4.0] {} 	at MC-BOOTSTRAP/fml_loader@4.0.29/net.neoforged.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:124) ~[loader-4.0.29.jar%23174!/:4.0] {} 	at MC-BOOTSTRAP/fml_loader@4.0.29/net.neoforged.fml.loading.targets.CommonClientLaunchHandler.runService(CommonClientLaunchHandler.java:32) ~[loader-4.0.29.jar%23174!/:4.0] {} 	at MC-BOOTSTRAP/fml_loader@4.0.29/net.neoforged.fml.loading.targets.CommonLaunchHandler.lambda$launchService$4(CommonLaunchHandler.java:118) ~[loader-4.0.29.jar%23174!/:4.0] {} 	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-11.0.4.jar%23167!/:?] {} 	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-11.0.4.jar%23167!/:?] {} 	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-11.0.4.jar%23167!/:?] {} 	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.run(Launcher.java:103) [modlauncher-11.0.4.jar%23167!/:?] {} 	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.main(Launcher.java:74) [modlauncher-11.0.4.jar%23167!/:?] {} 	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-11.0.4.jar%23167!/:?] {} 	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-11.0.4.jar%23167!/:?] {} 	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.run(BootstrapLauncher.java:210) [bootstraplauncher-2.0.2.jar:?] {} 	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:69) [bootstraplauncher-2.0.2.jar:?] {} 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?] {} 	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?] {} 	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:110) [JavaWrapper.jar:?] {} 	at oolloo.jlw.Wrapper.main(Wrapper.java:103) [JavaWrapper.jar:?] {

### Mod Version

21.1.0.7

**Comment by DarthCaesium** [comment]
I have not had any problems like this when using BOP on 1.21.1 NeoForge, are you sure this isn't to do with another mod?

**Comment by Forstride** [comment]
Closed due to the issue being for a version we no longer support.  Also pretty sure it was fixed in newer versions anyway
