### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by reaverreaper** [Glitchfiend/BiomesOPlenty#2305]
### What's the issue you encountered?

-- Head --
Thread: Render thread
Suspected Mod: 
	Biomes O' Plenty (biomesoplenty), Version: 21.4.0.12
		Issue tracker URL: https://github.com/Glitchfiend/BiomesOPlenty/issues
		at TRANSFORMER/biomesoplenty@21.4.0.12/biomesoplenty.init.ModClient.lambda$registerRenderers$51(ModClient.java:331)
Stacktrace:
	at TRANSFORMER/minecraft@1.21.4/net.minecraft.client.renderer.entity.EntityRenderers.lambda$createEntityRenderers$43(EntityRenderers.java:189) ~[forge-1.21.4-54.0.12-client.jar!/:?]
	at SECURE-BOOTSTRAP/it.unimi.dsi.fastutil@8.5.15/it.unimi.dsi.fastutil.objects.Object2ObjectMap.lambda$forEach$0(Object2ObjectMap.java:209) ~[fastutil-8.5.15.jar!/:?]
	at SECURE-BOOTSTRAP/it.unimi.dsi.fastutil@8.5.15/it.unimi.dsi.fastutil.objects.Object2ObjectOpenHashMap$MapEntrySet.fastForEach(Object2ObjectOpenHashMap.java:1008) ~[fastutil-8.5.15.jar!/:?]
	at SECURE-BOOTSTRAP/it.unimi.dsi.fastutil@8.5.15/it.unimi.dsi.fastutil.objects.Object2ObjectMap.forEach(Object2ObjectMap.java:211) ~[fastutil-8.5.15.jar!/:?]
	at TRANSFORMER/minecraft@1.21.4/net.minecraft.client.renderer.entity.EntityRenderers.createEntityRenderers(EntityRenderers.java:185) ~[forge-1.21.4-54.0.12-client.jar!/:?]
	at TRANSFORMER/minecraft@1.21.4/net.minecraft.client.renderer.entity.EntityRenderDispatcher.onResourceManagerReload(EntityRenderDispatcher.java:496) ~[forge-1.21.4-54.0.12-client.jar!/:?]
	at TRANSFORMER/minecraft@1.21.4/net.minecraft.server.packs.resources.ResourceManagerReloadListener.lambda$reload$0(ResourceManagerReloadListener.java:16) ~[forge-1.21.4-54.0.12-client.jar!/:?]
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:787) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at TRANSFORMER/minecraft@1.21.4/net.minecraft.server.packs.resources.SimpleReloadInstance.lambda$new$3(SimpleReloadInstance.java:68) ~[forge-1.21.4-54.0.12-client.jar!/:?]
	at TRANSFORMER/minecraft@1.21.4/net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:164) ~[forge-1.21.4-54.0.12-client.jar!/:?]
	at TRANSFORMER/minecraft@1.21.4/net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[forge-1.21.4-54.0.12-client.jar!/:?]
	at TRANSFORMER/minecraft@1.21.4/net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:138) ~[forge-1.21.4-54.0.12-client.jar!/:?]
Transformer Audit:
  net.minecraft.client.renderer.entity.EntityRenderDispatcher
    REASON: classloading
    PLUGIN: accesstransformer:BEFORE
    PLUGIN: runtimedistcleaner:AFTER
  net.minecraft.client.renderer.entity.EntityRenderers
    REASON: mixin
    PLUGIN: accesstransformer:BEFORE
    REASON: classloading
    PLUGIN: accesstransformer:BEFORE
  net.minecraft.server.packs.resources.ResourceManagerReloadListener
    REASON: classloading
    REASON: mixin
  net.minecraft.server.packs.resources.SimpleReloadInstance
    REASON: classloading
  net.minecraft.util.thread.BlockableEventLoop
    REASON: mixin
    PLUGIN: accesstransformer:BEFORE
    REASON: classloading
    PLUGIN: accesstransformer:BEFORE
  net.minecraft.util.thread.ReentrantBlockableEventLoop
    REASON: mixin
    REASON: classloading
-- Overlay render details --
Details:
	Overlay name: net.minecraftforge.client.loading.ForgeLoadingOverlay
Stacktrace:
	at TRANSFORMER/minecraft@1.21.4/net.minecraft.client.renderer.GameRenderer.render(GameRenderer.java:507) ~[forge-1.21.4-54.0.12-client.jar:?]
	at TRANSFORMER/minecraft@1.21.4/net.minecraft.client.Minecraft.runTick(Minecraft.java:1240) ~[forge-1.21.4-54.0.12-client.jar:?]
	at TRANSFORMER/minecraft@1.21.4/net.minecraft.client.Minecraft.run(Minecraft.java:836) ~[forge-1.21.4-54.0.12-client.jar:?]
	at TRANSFORMER/minecraft@1.21.4/net.minecraft.client.main.Main.main(Main.java:240) ~[forge-1.21.4-54.0.12-client.jar:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at SECURE-BOOTSTRAP/net.minecraftforge.fmlloader@1.21.4-54.0.12/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:96) ~[fmlloader-1.21.4-54.0.12.jar!/:?]
	at SECURE-BOOTSTRAP/net.minecraftforge.fmlloader@1.21.4-54.0.12/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.lambda$makeService$0(CommonLaunchHandler.java:79) ~[fmlloader-1.21.4-54.0.12.jar!/:?]
	at SECURE-BOOTSTRAP/cpw.mods.modlauncher@10.2.2/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:77) [modlauncher-10.2.2.jar!/:?]
	at SECURE-BOOTSTRAP/cpw.mods.modlauncher@10.2.2/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:97) [modlauncher-10.2.2.jar!/:?]
	at SECURE-BOOTSTRAP/cpw.mods.modlauncher@10.2.2/cpw.mods.modlauncher.Launcher.run(Launcher.java:116) [modlauncher-10.2.2.jar!/:?]
	at SECURE-BOOTSTRAP/cpw.mods.modlauncher@10.2.2/cpw.mods.modlauncher.Launcher.main(Launcher.java:75) [modlauncher-10.2.2.jar!/:?]
	at SECURE-BOOTSTRAP/cpw.mods.modlauncher@10.2.2/cpw.mods.modlauncher.BootstrapEntry.main(BootstrapEntry.java:17) [modlauncher-10.2.2.jar!/:?]
	at net.minecraftforge.bootstrap@2.1.7/net.minecraftforge.bootstrap.Bootstrap.moduleMain(Bootstrap.java:188) [bootstrap-2.1.7.jar!/:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at net.minecraftforge.bootstrap.Bootstrap.bootstrapMain(Bootstrap.java:133) [bootstrap-2.1.7.jar:2.1.7]
	at net.minecraftforge.bootstrap.Bootstrap.start(Bootstrap.java:53) [bootstrap-2.1.7.jar:2.1.7]
	at net.minecraftforge.bootstrap.ForgeBootstrap.main(ForgeBootstrap.java:19) [bootstrap-2.1.7.jar:2.1.7]
Transformer Audit:
  net.minecraft.client.Minecraft
    REASON: mixin
    PLUGIN: accesstransformer:BEFORE
    PLUGIN: runtimedistcleaner:AFTER
    REASON: classloading
    PLUGIN: accesstransformer:BEFORE
    PLUGIN: mixin:APP:glitchcore.mixins.json:client.MixinMinecraft
    PLUGIN: mixin:APP:journeymap.mixins.json:client.MinecraftMixin
    PLUGIN: mixin:AFTER
    PLUGIN: runtimedistcleaner:AFTER
  net.minecraft.client.main.Main
    REASON: classloading
  net.minecraft.client.renderer.GameRenderer
    REASON: mixin
    PLUGIN: runtimedistcleaner:AFTER
    REASON: classloading
    PLUGIN: mixin:APP:journeymap.mixins.json:client.GameRendererInvoker
    PLUGIN: mixin:AFTER
    PLUGIN: runtimedistcleaner:AFTER

-- Uptime --
Details:
	JVM uptime: 24.960s
	Wall uptime: 8.607s
	High-res time: 20.434s
	Client ticks: 83 ticks / 4.150s

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: No
	Packs: mod_resources, vanilla

### How can the issue be reproduced?

just starting it with the latest forge update

### Logs

<script src="https://gist.github.com/reaverreaper/421404a302b4b87abee946311c9614d9.js"></script>

### Mod Version

BiomesOPlenty-forge-1.21.4-21.4.0.12

### Additional information

The game crashed whilst rendering overlay
Error: java.lang.IllegalArgumentException: Failed to create model for biomesoplenty:empyreal_chest_boat

always throws up different model error

**Comment by Forstride** [comment]
We can't replicate this ourselves, but apparently localization strings were missing for boats, so it's possible some other mod could've been causing the crash due to that.

Could you try the latest build and see if it still crashes?

**Comment by reaverreaper** [comment]
took out the other mods while using the latest build still having that errorr

**Comment by reaverreaper** [comment]
took out the other mods while using the latest build still having that error, either i need to install minecraft again or doing something wrong

**Comment by Dinosaur-Guts** [comment]
I just wanted to pop in and say I'm having the same issue even with the update. I'm only using Biomes'O Plenty and the required mods for it. It keeps showing:
The game crashed whilst rendering overlay
Error: java.lang.IllegalArgumentException: Failed to create model for biomesoplenty:hellbark_boat

The boats change with each crash:
model for biomesoplenty:fir_chest_boat
model for biomesoplenty:empyreal_boat

**Comment by reaverreaper** [comment]
deleted and reinstalled minecraft and still crashes with the mahogany_chest_boat, i think the boats are crashing it

**Comment by CrainFartor** [comment]
I'm not sure if this helps, but I thought I could force minecraft to create the localization strings by using a resource pack.

I'm not sure about everyone else, but I'm running linux manjaro and using the PrismLauncher, maybe it is an issue when using anything but the official launcher?
I want to clarify that I'm not running a pirated copy, I had to log in to microsoft using an O-auth link to download minecraft with this 3rd party launcher.

I had the same issue, minecraft was crashing at launch and there was an error regarding boats.

This is what I did:
1: disabled all 3 mods (Biomes, Glitch and Terra) 
2: installed a texture pack
3: launched minecraft and enabled the texture pack, then exit minecraft
4: enabled all 3 mods and launched minecraft
5: minecraft no longer crashes before reaching the main screen, but it says failed to load resources
6: created a new world, i can enter and play for 10 seconds, then it still crashes.

Does anyone have any ideas on how to force the game to create the missing strings? i tried reinstalling already.

**Comment by Dinosaur-Guts** [comment]
With the post above I wanted to specify that I'm on Windows running through the launcher. I don't use a mod loader since I don't use many mods. I've also been modding this way for years so I'm not unfamiliar with having to troubleshoot or reinstall things.

For me the error is always boats, or chest_boats that cause the crash.

I also want to point out that I can load the game without Glitchcore in the mods folder. It just won't let me progress past the screen that says I need glitchcore 2.3.0.3

I get the same error when TerraBlender is removed.

If I load without BOP it starts up just fine.


Okay, I just tried to start it up just now to get the error again and it worked? I've done nothing different to the files and this time it started just fine? I could have swore I restarted my computer during my last post but maybe that was it? I'm really confused but at least it is working.
Went in and spawned boats and everything seems fine? I will update this post if I have any issues. Good luck and hope the restart helps!

**Comment by reaverreaper** [comment]
crashed my game, without even getting into the game and i just turned on my pc 

the boat crash still

**Comment by Dinosaur-Guts** [comment]
So I'm on laptop and tried running it again after work. It crashed, same boat crash.
However I unplugged my computer to head to bed and tried it one more time. It opened just fine. BOP and no bad boats.
If my computer is plugged in it crashes. If it is not plugged in it starts fine. It seems I'm able to plug it in and still have the game continue running fine as I spawn and punch boats.
I remain so confused.

**Comment by reaverreaper** [comment]
switched to fabric didn't want to and no crash so it's probably a forge bug
