### ISSUE TITLE
Crash when generating a new world with structures disabled

### ISSUE THREAD

**Issue by eanataw** [Glitchfiend/BiomesOPlenty#34]
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 8/1/13 10:29 AM
Description: Exception generating new chunk

java.lang.NullPointerException
    at net.minecraft.world.chunk.storage.ExtendedBlockStorage.func_76657_c(SourceFile:99)
    at net.minecraft.world.chunk.Chunk.func_76603_b(Chunk.java:383)
    at biomesoplenty.world.ChunkProviderBOP.func_73154_d(ChunkProviderBOP.java:382)
    at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:131)
    at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:166)
    at net.minecraft.world.World.func_72964_e(World.java:527)
    at net.minecraft.world.World.func_72798_a(World.java:412)
    at net.minecraft.world.World.func_72799_c(World.java:436)
    at net.minecraft.world.World.func_72922_b(World.java:383)
    at net.minecraft.world.WorldProvider.func_76566_a(WorldProvider.java:102)
    at net.minecraft.world.WorldServer.func_73052_b(WorldServer.java:828)
    at net.minecraft.world.WorldServer.func_72963_a(WorldServer.java:792)
    at net.minecraft.world.World.<init>(World.java:296)
    at net.minecraft.world.WorldServer.<init>(WorldServer.java:108)
    at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:74)
    at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:107)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:443)
    at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:582)
A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at net.minecraft.world.chunk.storage.ExtendedBlockStorage.func_76657_c(SourceFile:99)
    at net.minecraft.world.chunk.Chunk.func_76603_b(Chunk.java:383)
    at biomesoplenty.world.ChunkProviderBOP.func_73154_d(ChunkProviderBOP.java:382)

-- Chunk to be generated --
Details:
    Location: -14,-5
    Position hash: -17179869198
    Generator: RandomLevelSource
Stacktrace:
    at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:131)
    at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:166)
    at net.minecraft.world.World.func_72964_e(World.java:527)

-- Requested block coordinates --
Details:
    Found chunk: true
    Location: World: (-220,64,-76), Chunk: (at 4,4,4 in -14,-5; contains blocks -224,0,-80 to -209,255,-65), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
Stacktrace:
    at net.minecraft.world.World.func_72798_a(World.java:412)
    at net.minecraft.world.World.func_72799_c(World.java:436)
    at net.minecraft.world.World.func_72922_b(World.java:383)
    at net.minecraft.world.WorldProvider.func_76566_a(WorldProvider.java:102)
    at net.minecraft.world.WorldServer.func_73052_b(WorldServer.java:828)
    at net.minecraft.world.WorldServer.func_72963_a(WorldServer.java:792)

-- Affected level --
Details:
    Level name: New World
    All players: 0 total; []
    Chunk stats: ServerChunkCache: 0 Drop: 0
    Level seed: -7530029528993038504
    Level generator: ID 04 - BIOMESOP, ver 0. Features enabled: false
    Level generator options: 
    Level spawn location: World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 0 game time, 0 day time
    Level dimension: 0
    Level storage version: 0x04ABD - Anvil
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
    at net.minecraft.world.World.<init>(World.java:296)
    at net.minecraft.world.WorldServer.<init>(WorldServer.java:108)
    at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:74)
    at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:107)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:443)
    at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:582)

-- System Details --
Details:
    Minecraft Version: 1.6.2
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.7.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 343663848 bytes (327 MB) / 499908608 bytes (476 MB) up to 954466304 bytes (910 MB)
    JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Suspicious classes: FML and Forge are installed
    IntCache: cache: 0, tcache: 0, allocated: 1, tallocated: 75
    FML: MCP v8.04 FML v6.2.35.803 Minecraft Forge 9.10.0.803 5 mods loaded, 5 mods active
    mcp{8.04} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    FML{6.2.35.803} [Forge Mod Loader](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    Forge{9.10.0.803} [Minecraft Forge](coremods) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    BiomesOPlenty{0.5.9.2} [Biomes O' Plenty](Biomes-O-Plenty-0.5.9.2-1.6.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    UndergroundBiomes{0.4.2a} [Underground Biomes](UndergroundBiomes 1.6.x - 0.4.2a.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available
    Profiler Position: N/A (disabled)
    Player Count: 0 / 8; []
    Type: Integrated Server (map_client.txt)
    Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by Adubbz** [comment]
Hey eanataw, would you mind hopping on our Discord and pinging myself and Forstride when you are around?
