### ISSUE TITLE
Crash when teleporting (Already Decorating)

### ISSUE THREAD

**Issue by techbrew-mc** [Glitchfiend/BiomesOPlenty#386]
Singleplayer, BoP generated world.  Forge 1.7.10 - 10.13.2.1277.  Java 8.  Windows 64.

I've crashed multiple times when teleporting.  This first example is (I believe) when teleporting to a chunk that didn't exist yet:

    java.lang.RuntimeException: Already decorating!!
       at net.minecraft.world.biome.BiomeDecorator.func_150512_a(BiomeDecorator.java:97)
       at biomesoplenty.api.biome.BOPInheritedBiome.func_76728_a(BOPInheritedBiome.java:42)
       at net.minecraft.world.gen.ChunkProviderGenerate.func_73153_a(ChunkProviderGenerate.java:421)
       at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:279)
       at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1040)
       at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190)
       at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131)

Full report: http://pastebin.com/62c5W9Bg

Example 2 happened when teleporting to a chunk that already existed.  This has happened several other times as well:

    java.lang.RuntimeException: Already decorating!!
        at net.minecraft.world.biome.BiomeDecorator.func_150512_a(BiomeDecorator.java:97)
        at biomesoplenty.api.biome.BOPInheritedBiome.func_76728_a(BOPInheritedBiome.java:42)
        at net.minecraft.world.gen.ChunkProviderGenerate.func_73153_a(ChunkProviderGenerate.java:421)
        at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:279)
        at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1040)
        at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:52)
        at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:12)
        at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:344)
        at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302)
        at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12)

(The rest of the details are essentially the same as the full report linked above)

**Comment by pchard** [comment]
I have this issue on my server...
