### ISSUE TITLE
[1.8] Crash in debug world

### ISSUE THREAD

**Issue by SteveKunG** [Glitchfiend/BiomesOPlenty#459]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  NEICorePlugin (NotEnoughItems-1.8-1.0.5.93-dev.jar)
  CCCDeobfPlugin (unknown)
  CCLCorePlugin (CodeChickenLib-1.8-1.1.2.132-dev.jar)
  CodeChickenCorePlugin (CodeChickenCore-1.8-1.0.5.34-dev.jar)
  MorePlanetsPlugin (bin)
Contact their authors BEFORE contacting forge

// Sorry :(

Time: 4/5/2558, 22:23 น.
Description: Unexpected error

java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=variant, clazz=class biomesoplenty.common.block.BlockBOPDoublePlant$FoliageType, values=[flax, tall_cattail]} as it does not exist in BlockState{block=minecraft:air, properties=[]}
	at net.minecraft.block.state.BlockState$StateImplementation.getValue(BlockState.java:167)
	at biomesoplenty.common.block.BlockBOPDoublePlant.getLowerShearDrops(BlockBOPDoublePlant.java:227)
	at biomesoplenty.common.block.BlockDoubleDecoration.onSheared(BlockDoubleDecoration.java:213)
	at codechicken.nei.api.ItemInfo.getIdentifierItems(ItemInfo.java:479)
	at codechicken.nei.HUDRenderer.renderOverlay(HUDRenderer.java:39)
	at codechicken.nei.ClientHandler.tickEvent(ClientHandler.java:157)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_38_ClientHandler_tickEvent_RenderTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:55)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraftforge.fml.common.FMLCommonHandler.onRenderTickEnd(FMLCommonHandler.java:381)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1109)
	at net.minecraft.client.Minecraft.run(Minecraft.java:376)
	at net.minecraft.client.main.Main.main(Main.java:117)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at net.minecraftforge.gradle.GradleStartCommon.launch(Unknown Source)
	at GradleStart.main(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.block.state.BlockState$StateImplementation.getValue(BlockState.java:167)
	at biomesoplenty.common.block.BlockBOPDoublePlant.getLowerShearDrops(BlockBOPDoublePlant.java:227)
	at biomesoplenty.common.block.BlockDoubleDecoration.onSheared(BlockDoubleDecoration.java:213)
	at codechicken.nei.api.ItemInfo.getIdentifierItems(ItemInfo.java:479)
	at codechicken.nei.HUDRenderer.renderOverlay(HUDRenderer.java:39)
	at codechicken.nei.ClientHandler.tickEvent(ClientHandler.java:157)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_38_ClientHandler_tickEvent_RenderTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:55)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:138)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Player891'/107, l='MpServer', x=162.26, y=71.21, z=26.07]]
	Chunk stats: MultiplayerChunkCache: 256, 256
	Level seed: 0
	Level generator: ID 05 - debug_all_block_states, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: 0.00,1.00,0.00 - World: (0,1,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 360 game time, 6000 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: spectator (ID 3). Hardcore: false. Cheats: false
	Forced entities: 1 total; [EntityPlayerSP['Player891'/107, l='MpServer', x=162.26, y=71.21, z=26.07]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.addWorldInfoToCrashReport(WorldClient.java:392)
	at net.minecraft.client.Minecraft.addGraphicsAndWorldToCrashReport(Minecraft.java:2600)
	at net.minecraft.client.Minecraft.run(Minecraft.java:405)
	at net.minecraft.client.main.Main.main(Main.java:117)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at net.minecraftforge.gradle.GradleStartCommon.launch(Unknown Source)
	at GradleStart.main(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.8
	Operating System: Windows 7 (x86) version 6.1
	Java Version: 1.8.0_45, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 753235384 bytes (718 MB) / 1060372480 bytes (1011 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 3 total; -Xincgc -Xmx1024M -Xms1024M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.10 FML v8.0.76.1371 Minecraft Forge 11.14.1.1371 9 mods loaded, 9 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	FML{8.0.76.1371} [Forge Mod Loader] (forgeSrc-1.8-11.14.1.1371.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	Forge{11.14.1.1371} [Minecraft Forge] (forgeSrc-1.8-11.14.1.1371.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	CodeChickenCore{1.0.5.34} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	NotEnoughItems{1.0.5.93} [Not Enough Items] (NotEnoughItems-1.8-1.0.5.93-dev.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	BiomesOPlenty{1.0} [Biomes O' Plenty] (bin) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	minecraftbyexample{1.0} [minecraftbyexample] (bin) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	MorePlanets{2.0.0} [More Planets] (bin) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	DamageIndicatorsMod{3.3.3} [Damage Indicators] ([1.8]DamageIndicatorsMod-3.3.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available->Available->Available->Available->Available->Available
	Loaded coremods (and transformers): 
NEICorePlugin (NotEnoughItems-1.8-1.0.5.93-dev.jar)
  codechicken.nei.asm.NEITransformer
CCCDeobfPlugin (unknown)
  
CCLCorePlugin (CodeChickenLib-1.8-1.1.2.132-dev.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.RenderHookTransformer
CodeChickenCorePlugin (CodeChickenCore-1.8-1.0.5.34-dev.jar)
  codechicken.core.asm.InterfaceDependancyTransformer
  codechicken.core.asm.TweakTransformer
  codechicken.core.asm.DelegatedTransformer
  codechicken.core.asm.DefaultImplementationTransformer
MorePlanetsPlugin (bin)
  stevekung.mods.moreplanets.plugin.asm.MorePlanetsTransformer
	Launched Version: 1.8
	LWJGL: 2.9.1
	OpenGL: GeForce 9500 GT/PCIe/SSE2 GL version 3.3.0, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)

**Comment by cheeserolls** [comment]
Hi @SteveKunG - what were you doing when this crash happened?  It looks like you were shearing a tall plant.  I've just pushed a patch to the 1.8 branch which I think will fix the problem - but I wasn't actually able to reproduce it myself, so I'd like to understand better what happened.  Thanks

**Comment by SteveKunG** [comment]
I create new Debug World and getting crash like this. I don't know why happened this.

**Comment by cheeserolls** [comment]
Ah yes - that makes sense now.  I think my patch should have fixed the problem.  I think the crash was happening when the top half and bottom half of a large plant were not together.  That shouldn't happen in a normal game, but it probably does happen in the debug world.

**Comment by SteveKunG** [comment]
Thank you. That's work.
