### ISSUE TITLE
Crash with Thermal Expansion

### ISSUE THREAD

**Issue by Thaliana** [Glitchfiend/BiomesOPlenty#480]
When I tried to right click Thermal Expansion liquid tank with BoP honey bucket, nothing happened. And then I tried shift-right click, the game crushed. I'm using minecraft version 1.7.10, BoP 2.1.0.1283 and Thermal Expansion 4.0.1-182. The crush still happens after I removed all other mods and create a new super-flat world in creative mode.

**Comment by Thaliana** [comment]
This is the crush report. I also reported to team CoFH and they say the fault is with BoP Honey Bucket. What's more, emptying the honey bucket with TE fluid transposer or by right-click Forestry still fails to return a bucket properly. A item.bucket.name (#4328) is returned instead.
```
---- Minecraft Crash Report ----
// But it works on my machine.

Time: 15-5-28 AM 9:19
Description: Ticking memory connection

java.lang.NullPointerException: Ticking memory connection
    at cofh.thermalexpansion.block.tank.TileTank.fill(TileTank.java:326)
    at biomesoplenty.common.items.ItemBOPBucket.func_77659_a(ItemBOPBucket.java:58)
    at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:146)
    at net.minecraft.server.management.ItemInWorldManager.func_73085_a(ItemInWorldManager.java:316)
    at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:539)
    at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
    at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
    at cofh.thermalexpansion.block.tank.TileTank.fill(TileTank.java:326)
    at biomesoplenty.common.items.ItemBOPBucket.func_77659_a(ItemBOPBucket.java:58)
    at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:146)
    at net.minecraft.server.management.ItemInWorldManager.func_73085_a(ItemInWorldManager.java:316)
    at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:539)
    at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
    at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)

-- Ticking connection --
Details:
    Connection: net.minecraft.network.NetworkManager@1178001
Stacktrace:
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows XP (x86) version 5.1
    Java Version: 1.8.0_45, Oracle Corporation
    Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
    Memory: 178195144 bytes (169 MB) / 330608640 bytes (315 MB) up to 1037959168 bytes (989 MB)
    JVM Flags: 1 total; -Xmx1024m
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.85.1291 Minecraft Forge 10.13.2.1291 8 mods loaded, 8 mods active
    mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FML{7.10.85.1291} [Forge Mod Loader] (forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forge{10.13.2.1291} [Minecraft Forge] (forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    <CoFH ASM>{000} [CoFH ASM] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.1283-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CoFHCore{1.7.10R3.0.2} [CoFH Core] (CoFHCore-[1.7.10]3.0.2-262.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ThermalFoundation{1.7.10R1.0.0} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.0.0-81.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ThermalExpansion{1.7.10R4.0.1} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.1-182.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CoFHCore: -[1.7.10]3.0.2-262
    ThermalFoundation: -[1.7.10]1.0.0-81
    ThermalExpansion: -[1.7.10]4.0.1-182
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Player Count: 1 / 8; [EntityPlayerMP['Gorilla'/0, l='New World', x=-136.56, y=56.00, z=-1130.49]]
    Type: Integrated Server (map_client.txt)
    Is Modded: Definitely; Client brand changed to 'fml,forge'
```
