### ISSUE TITLE
BiomesOPlenty crashes game (v 1.8) at startup (with multiple other mods installed)

### ISSUE THREAD

**Issue by marcbaas** [Glitchfiend/BiomesOPlenty#501]
Some how, the current version of BiomesOPlenty keeps crashing my game when I'm starting it. I have tried it on my server as well, with the same result.

Maybe it's a conflict with another mod, though I'm not familiar enough with the minecraft debugging messages to be able to determine the exact cause.

Platform is Mac OSX 10.10.3
Java 8 update 45
I have Liteloader 1.8 running and Forge 11.14.3.1450
Game version is 1.8

Let me know if you need more info and I'll do my best to provide it.

Here is the error log that Minecraft produces upon crashing:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  BOPLoadingPlugin (BiomesOPlenty-1.8-3.0.0.1363-universal.jar)
Contact their authors BEFORE contacting forge

// But it works on my machine.

Time: 6/29/15 9:33 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: java.lang.NoSuchMethodError: net.minecraftforge.fluids.Fluid.<init>(Ljava/lang/String;Lnet/minecraft/util/ResourceLocation;Lnet/minecraft/util/ResourceLocation;)V
	at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:163)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:553)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:248)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:412)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:325)
	at net.minecraft.client.main.Main.main(SourceFile:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoSuchMethodError: net.minecraftforge.fluids.Fluid.<init>(Ljava/lang/String;Lnet/minecraft/util/ResourceLocation;Lnet/minecraft/util/ResourceLocation;)V
	at biomesoplenty.common.fluids.HoneyFluid.<init>(HoneyFluid.java:21)
	at biomesoplenty.common.fluids.HoneyFluid.<clinit>(HoneyFluid.java:17)
	at biomesoplenty.common.init.ModBlocks.init(ModBlocks.java:233)
	at biomesoplenty.core.BiomesOPlenty.preInit(BiomesOPlenty.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:537)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:550)
	... 10 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.8
	Operating System: Mac OS X (x86_64) version 10.10.3
	Java Version: 1.8.0_40, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 225941160 bytes (215 MB) / 484966400 bytes (462 MB) up to 954728448 bytes (910 MB)
	JVM Flags: 1 total; -Xmx1G
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.10 FML v8.0.99.99 Minecraft Forge 11.14.3.1450 18 mods loaded, 18 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8-11.14.3.1450.jar) 
	UCH	Forge{11.14.3.1450} [Minecraft Forge] (forge-1.8-11.14.3.1450.jar) 
	UCH	moSwords{v6} [Mo Swords Mod] ([1.8] moSwords v6.jar) 
	UCE	BiomesOPlenty{3.0.0} [Biomes O' Plenty] (BiomesOPlenty-1.8-3.0.0.1363-universal.jar) 
	UCH	bc{1.0} [Ollij93's BowCraft] (BowCraft-1.1.jar) 
	UCH	Chameleon{1.8-0.1.0} [Chameleon] (Chameleon-1.8-0.1.0.jar) 
	UCH	craftablehorsearmour{1.0} [Craftable Horse Armour [CHA&S]] (Craftable Horse Armour and Saddle 1.2.1.jar) 
	UCH	wuppy29_koi{1.12.0} [Koi] (Koi 1.8.0-1.12.0.jar) 
	UCH	chef{4.0} [Master Chef] (Master_Chef_v4.0-1.8.jar) 
	UCH	morematerials{1.0.20150201.0} [More Materials] (morematerials-1.0.20150201.0-MC1.8-20150125.jar) 
	UCH	cfm{3.4.7} [�9MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.4.7-build5(1.8).jar) 
	UCH	parachutemod{3.1.1} [Parachute Mod] (parachutemod-1.8.0-3.1.1-23.jar) 
	UCH	ParkourMod{1.0} [Parkour Mod (Assassin's Creed Style)] (Parkour Mod for Minecraft 1.8 by Shadow38PL.jar) 
	UCH	PetBat{1.3.7} [Pet Bat] (PetBat-1.8.jar) 
	UCH	plantmegapack{5.04} [Plant Mega Pack] (plantmegapack-5.04-1.8-1334.jar) 
	UCH	shipwrecks_winslow{1.6.3} [Shipwrecks!] (shipwrecks_winslow-1.8.0-1.6.3.jar) 
	UCH	SophisticatedWolves{3.5.0} [SophisticatedWolves] (SophisticatedWolves-3.5.0.jar) 
	Loaded coremods (and transformers): 
BOPLoadingPlugin (BiomesOPlenty-1.8-3.0.0.1363-universal.jar)
  
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '2.1 NVIDIA-10.2.7 310.41.25f01' Renderer: 'NVIDIA GeForce GT 750M OpenGL Engine'

**Comment by Adubbz** [comment]
Looks like you're using an outdated Forge. We recently updated our fluids to make use of the new fluid rendering code which is only in newer versions of Forge.

Don't mind my copy-pasted response :P

**Comment by BK-Thunder** [comment]
I have the same problem. I am using Minecraft 1.8-Forge11.14.3.1450 and Biomes O Plenty crashes my minecraft. I only have one other mod installed.
