### ISSUE TITLE
[1.7.10] Server crash in certain chunks, falling blocks?

### ISSUE THREAD

**Issue by agonsdurub** [Glitchfiend/BiomesOPlenty#507]
Hey, just started a custom modpack and I've been having problems with people getting stuck in chunks. I'm no expert in reading crashlogs but from what I can tell it has something to do with BlockBOPCoral and falling sand.

Anyone care to take a look and help me out here?

http://pastebin.com/DQ5HUX9J

Thank you!

**Comment by DoughnutDev** [comment]
I have the same crash

**Comment by DoughnutDev** [comment]
This is fixed in the new version of BOP this was a issue when Matter Overdrive was installed.

**Comment by Kazzamkablam** [comment]
Welp, I just ran to same bug on new version of BOP:

Time: 8/21/15 5:56 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at biomesoplenty.common.blocks.BlockBOPCoral.func_149705_a(BlockBOPCoral.java:79)
	at net.minecraft.world.World.func_147472_a(World.java:3318)
	at net.minecraft.entity.item.EntityFallingBlock.func_70071_h_(SourceFile:112)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
	at net.minecraft.world.World.func_72870_g(World.java:2034)
	at net.minecraft.world.World.func_72939_s(World.java:1887)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by DoughnutDev** [comment]
Do you have MatterOverdrive?

**Comment by Kazzamkablam** [comment]
yup, I fixed it from my save by deleting falling sand entities

**Comment by Adaptivity** [comment]
@Adubbz this one is fixed by @wwrpg
