### ISSUE TITLE
[1.7.10] Forestry Integration no longer working

### ISSUE THREAD

**Issue by LordMonoxide** [Glitchfiend/BiomesOPlenty#518]
As of ForestryMC/ForestryAPI@9189ad7be65a709f4407c0d15ea4372ec220880f, BoP's Forestry integration is broken.

```
Caused by: java.lang.NoSuchFieldError: plainFlowers
	at biomesoplenty.common.integration.ForestryIntegration.addFlowers(ForestryIntegration.java:50)
	at biomesoplenty.common.integration.ForestryIntegration.init(ForestryIntegration.java:32)
	at biomesoplenty.common.integration.BOPIntegration.postInit(BOPIntegration.java:27)
	at biomesoplenty.BiomesOPlenty.postInit(BiomesOPlenty.java:86)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:742)
	... 10 more
```

(It would also be nice to have config options to disable integrations for cases like this.)

**Comment by Xen1290** [comment]
Can confirm this crash @Glitchfiend

**Comment by LordMonoxide** [comment]
For anyone looking for a build of Forestry that still works with BoP, [this](http://ic2api.player.to:8080/job/Forestry_Dev/627/) is the latest build that works (July 2nd).

**Comment by erkro1** [comment]
I also confirm this crash, please fix it.

**Comment by erkro1** [comment]
@LordMonoxide latest build that works is actually 639, which can be found here: http://ic2api.player.to:8080/job/Forestry_Dev/639/

**Comment by Adubbz** [comment]
To be honest, I think the easiest option will be to just quickly rip it out. It's situations like this that really make me not want to bother with integrating with other mods.

**Comment by Adubbz** [comment]
This should be addressed as of 1.7.10-2.1.0.1387.

**Comment by erkro1** [comment]
Couldn't you just comment out [this line](https://github.com/Glitchfiend/BiomesOPlenty/blob/BOP-1.7.10-2.1.x/src/main/java/biomesoplenty/common/integration/ForestryIntegration.java#L32), that would still make the other Forestry support work if I'm correct.

Or do you just don't want to bother with any Forestry as of now with unstable builds changing things?

**Comment by Adubbz** [comment]
Possibly, but really it's enough having to keep up with the changes in Minecraft and Forge, let alone the changes in other mods too. For now it's easiest to just disable it completely without worrying about something else in their API changing and the whole situation occurring again. I don't think we handled integration particularly well either for this to be an issue. Ideally it should have been a case of 'right, it looks like something changed, we don't know what it is, log it, disable Forestry completely and continue on our merry way'.

**Comment by mezz** [comment]
@Adubbz do you have any objection to me moving the BoP compatibility to Forestry and maintaining it there?

**Comment by Adubbz** [comment]
No objections at all, you guys probably know better than us what needs integration and what doesn't

**Comment by mezz** [comment]
Thanks, added to Forestry https://github.com/ForestryMC/ForestryMC/commit/c56f09897c68f2bb5630861c05fc17bd2aa479cb

Can you catch the Plugin error and ignore it instead of fully disabling the plugin? That way BoP will handle Forestry versions before 4.0, and Forestry will take care of later versions.

**Comment by Adubbz** [comment]
Yeah, i'm fine with doing that. I'll see to it when I get some time.
