### ISSUE TITLE
[1.8] another crash during world load

### ISSUE THREAD

**Issue by croftyraider** [Glitchfiend/BiomesOPlenty#536]
This time the servers were online, so no funny business there.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  FMLPlugin (InventoryTweaks-1.59-176.jar)
  CCLCorePlugin (CodeChickenLib-1.8-1.1.2.133-universal.jar)
  BetterFps (BetterFps-1.1.0.jar)
  BOPLoadingPlugin (BiomesOPlenty-1.8-3.0.0.1389-universal.jar)
  CodeChickenCorePlugin (CodeChickenCore-1.8-1.0.5.36-universal.jar)
  CCCDeobfPlugin (unknown)
  CoreMod (Aroma1997Core-1.8-1.0.3.4.jar)
  NEICorePlugin (NotEnoughItems-1.8-1.0.5.104-universal.jar)
Contact their authors BEFORE contacting forge

// Who set us up the TNT?

Time: 9/15/15 5:36 PM
Description: Getting biome

java.lang.ArrayIndexOutOfBoundsException: -3
	at biomesoplenty.common.world.layer.GenLayerClimate.func_75904_a(GenLayerClimate.java:30)
	at biomesoplenty.common.world.layer.GenLayerBiomeBOP.func_75904_a(GenLayerBiomeBOP.java:41)
	at net.minecraft.world.gen.layer.GenLayerZoom.func_75904_a(SourceFile:19)
	at net.minecraft.world.gen.layer.GenLayerZoom.func_75904_a(SourceFile:19)
	at biomesoplenty.common.world.layer.GenLayerBiomeEdgeBOP.func_75904_a(GenLayerBiomeEdgeBOP.java:30)
	at biomesoplenty.common.world.layer.GenLayerSubBiomesBOP.func_75904_a(GenLayerSubBiomesBOP.java:31)
	at biomesoplenty.common.world.layer.GenLayerBiomeIslands.func_75904_a(GenLayerBiomeIslands.java:32)
	at net.minecraft.world.gen.layer.GenLayerZoom.func_75904_a(SourceFile:19)
	at biomesoplenty.common.world.layer.GenLayerRaggedEdges.func_75904_a(GenLayerRaggedEdges.java:27)
	at net.minecraft.world.gen.layer.GenLayerZoom.func_75904_a(SourceFile:19)
	at net.minecraft.world.gen.layer.GenLayerShore.func_75904_a(SourceFile:15)
	at net.minecraft.world.gen.layer.GenLayerZoom.func_75904_a(SourceFile:19)
	at net.minecraft.world.gen.layer.GenLayerZoom.func_75904_a(SourceFile:19)
	at net.minecraft.world.gen.layer.GenLayerSmooth.func_75904_a(SourceFile:15)
	at biomesoplenty.common.world.layer.GenLayerRiverMixBOP.func_75904_a(GenLayerRiverMixBOP.java:39)
	at net.minecraft.world.gen.layer.GenLayerVoronoiZoom.func_75904_a(SourceFile:22)
	at net.minecraft.world.biome.WorldChunkManager.func_76936_a(WorldChunkManager.java:78)
	at net.minecraft.world.biome.BiomeCache$Block.<init>(SourceFile:27)
	at net.minecraft.world.biome.BiomeCache.func_76840_a(SourceFile:53)
	at net.minecraft.world.biome.BiomeCache.func_180284_a(SourceFile:62)
	at net.minecraft.world.biome.WorldChunkManager.func_180300_a(WorldChunkManager.java:66)
	at net.minecraft.world.chunk.Chunk.func_177411_a(Chunk.java:1352)
	at net.minecraft.world.World.getBiomeGenForCoordsBody(World.java:161)
	at net.minecraft.world.WorldProvider.getBiomeGenForCoords(WorldProvider.java:375)
	at net.minecraft.world.World.func_180494_b(World.java:150)
	at net.minecraftforge.client.ForgeHooksClient.getSkyBlendColour(ForgeHooksClient.java:392)
	at net.minecraft.world.World.getSkyColorBody(World.java:1410)
	at net.minecraft.world.WorldProvider.getSkyColor(WorldProvider.java:409)
	at net.minecraft.world.World.func_72833_a(World.java:1397)
	at net.minecraft.client.renderer.EntityRenderer.func_78466_h(EntityRenderer.java:1695)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1224)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1210)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1035)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:345)
	at net.minecraft.client.main.Main.main(SourceFile:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at biomesoplenty.common.world.layer.GenLayerClimate.func_75904_a(GenLayerClimate.java:30)
	at biomesoplenty.common.world.layer.GenLayerBiomeBOP.func_75904_a(GenLayerBiomeBOP.java:41)
	at net.minecraft.world.gen.layer.GenLayerZoom.func_75904_a(SourceFile:19)
	at net.minecraft.world.gen.layer.GenLayerZoom.func_75904_a(SourceFile:19)
	at biomesoplenty.common.world.layer.GenLayerBiomeEdgeBOP.func_75904_a(GenLayerBiomeEdgeBOP.java:30)
	at biomesoplenty.common.world.layer.GenLayerSubBiomesBOP.func_75904_a(GenLayerSubBiomesBOP.java:31)
	at biomesoplenty.common.world.layer.GenLayerBiomeIslands.func_75904_a(GenLayerBiomeIslands.java:32)
	at net.minecraft.world.gen.layer.GenLayerZoom.func_75904_a(SourceFile:19)
	at biomesoplenty.common.world.layer.GenLayerRaggedEdges.func_75904_a(GenLayerRaggedEdges.java:27)
	at net.minecraft.world.gen.layer.GenLayerZoom.func_75904_a(SourceFile:19)
	at net.minecraft.world.gen.layer.GenLayerShore.func_75904_a(SourceFile:15)
	at net.minecraft.world.gen.layer.GenLayerZoom.func_75904_a(SourceFile:19)
	at net.minecraft.world.gen.layer.GenLayerZoom.func_75904_a(SourceFile:19)
	at net.minecraft.world.gen.layer.GenLayerSmooth.func_75904_a(SourceFile:15)
	at biomesoplenty.common.world.layer.GenLayerRiverMixBOP.func_75904_a(GenLayerRiverMixBOP.java:39)
	at net.minecraft.world.gen.layer.GenLayerVoronoiZoom.func_75904_a(SourceFile:22)
	at net.minecraft.world.biome.WorldChunkManager.func_76936_a(WorldChunkManager.java:78)
	at net.minecraft.world.biome.BiomeCache$Block.<init>(SourceFile:27)
	at net.minecraft.world.biome.BiomeCache.func_76840_a(SourceFile:53)
	at net.minecraft.world.biome.BiomeCache.func_180284_a(SourceFile:62)
	at net.minecraft.world.biome.WorldChunkManager.func_180300_a(WorldChunkManager.java:66)
	at net.minecraft.world.chunk.Chunk.func_177411_a(Chunk.java:1352)

-- Coordinates of biome request --
Details:
	Location: World: (-22,65,-22), Chunk: (at 10,4,10 in -2,-2; contains blocks -32,0,-32 to -17,255,-17), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
Stacktrace:
	at net.minecraft.world.World.getBiomeGenForCoordsBody(World.java:161)
	at net.minecraft.world.WorldProvider.getBiomeGenForCoords(WorldProvider.java:375)
	at net.minecraft.world.World.func_180494_b(World.java:150)
	at net.minecraftforge.client.ForgeHooksClient.getSkyBlendColour(ForgeHooksClient.java:392)
	at net.minecraft.world.World.getSkyColorBody(World.java:1410)
	at net.minecraft.world.WorldProvider.getSkyColor(WorldProvider.java:409)
	at net.minecraft.world.World.func_72833_a(World.java:1397)
	at net.minecraft.client.renderer.EntityRenderer.func_78466_h(EntityRenderer.java:1695)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1224)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1210)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['croftyraider'/327, l='MpServer', x=8.50, y=65.00, z=8.50]]
	Chunk stats: MultiplayerChunkCache: 0, 0
	Level seed: 0
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: 196.00,64.00,248.00 - World: (196,64,248), Chunk: (at 4,4,8 in 12,15; contains blocks 192,0,240 to 207,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 1 game time, 1 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 1 total; [EntityPlayerSP['croftyraider'/327, l='MpServer', x=8.50, y=65.00, z=8.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:351)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2502)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:367)
	at net.minecraft.client.main.Main.main(SourceFile:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8
	Operating System: Mac OS X (x86_64) version 10.10.5
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2600659200 bytes (2480 MB) / 3113877504 bytes (2969 MB) up to 3113877504 bytes (2969 MB)
	JVM Flags: 5 total; -XX:+UseParNewGC -XX:+AggressiveOpts -XX:+TieredCompilation -Xms3G -Xmx3G
	IntCache: cache: 0, tcache: 47, allocated: 0, tallocated: 43
	FML: MCP v9.10 FML v8.0.99.99 Minecraft Forge 11.14.3.1513 28 mods loaded, 28 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8-11.14.3.1513.jar) 
	UCHIJAAAA	Forge{11.14.3.1513} [Minecraft Forge] (forge-1.8-11.14.3.1513.jar) 
	UCHIJAAAA	Aroma1997Core{1.0.3.4} [Aroma1997Core] (Aroma1997Core-1.8-1.0.3.4.jar) 
	UCHIJAAAA	betterfps{1.1.0} [BetterFps] (minecraft.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.5.36} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.5.104} [Not Enough Items] (NotEnoughItems-1.8-1.0.5.104-universal.jar) 
	UCHIJAAAA	bspkrsCore{7.01} [bspkrsCore] ([1.8]bspkrsCore-universal-7.01.jar) 
	UCHIJAAAA	Treecapitator{1.8} [Treecapitator] ([1.8]Treecapitator-universal-2.0.5.jar) 
	UCHIJAAAA	Aroma1997CoreHelper{1.0.3.4} [Aroma1997Core|Helper] (Aroma1997Core-1.8-1.0.3.4.jar) 
	UCHIJAAAA	Aroma1997sDimension{1.0} [Aroma1997's Dimensional World] (Aroma1997s-Dimensional-World-1.8-1.1.1.0.jar) 
	UCHIJAAAA	basemetals{1.4.0} [Base Metals] (BaseMetals-1.4.0.jar) 
	UCHIJAAAA	BiomesOPlenty{3.0.0} [Biomes O' Plenty] (BiomesOPlenty-1.8-3.0.0.1389-universal.jar) 
	UCHIJAAAA	Chameleon{1.8-0.1.0} [Chameleon] (Chameleon-1.8-0.1.0.jar) 
	UCHIJAAAA	decorationmegapack{1.18} [Decoration Mega Pack] (decorationmegapack-1.18-1.8-1446.jar) 
	UCHIJAAAA	expchest{4.0} [Exp Chest] (expchest-4.0.jar) 
	UCHIJAAAA	inventorytweaks{1.59-176-9318a76-dirty} [Inventory Tweaks] (InventoryTweaks-1.59-176.jar) 
	UCHIJAAAA	IronChest{6.0.107.754} [Iron Chest] (ironchest-1.8-6.0.107.754-universal.jar) 
	UCHIJAAAA	fyberbackpack{1.0} [Just Backpacks] (justbackpacks-mc1.8-1.0.jar) 
	UCHIJAAAA	plantmegapack{5.08} [Plant Mega Pack] (plantmegapack-5.08-1.8-1450.jar) 
	UCHIJAAAA	poweradvantage{1.2.4} [Power Advantage] (PowerAdvantage-1.2.4.jar) 
	UCHIJAAAA	projectbench{0.5.0} [Project Bench Updated] (ProjectBench-Update-1.8-0.5.0.jar) 
	UCHIJAAAA	AS_Ruins{15.2} [Ruins Spawning System] (Ruins-1.8.jar) 
	UCHIJAAAA	shipwrecks{1.7.0} [Shipwrecks!] (shipwrecks-1.8.0-1.7.1.jar) 
	UCHIJAAAA	steamadvantage{1.3.3} [Steam Advantage] (SteamAdvantage-1.3.3.jar) 
	UCHIJAAAA	StorageDrawers{1.8-2.1.6} [Storage Drawers] (StorageDrawers-1.8-2.1.6.jar) 
	UCHIJAAAA	reinforcedmod{Updated for 1.8} [Reinforced Mod] (The Reinforced Mod 1.8(v1.4.0).jar) 
	UCHIJAAAA	AS_UpdateCheck{1.1.7} [AtomicStryker Update Check Mod] (UpdateCheckerMod-1.8.jar) 
	Loaded coremods (and transformers): 
FMLPlugin (InventoryTweaks-1.59-176.jar)
  invtweaks.forge.asm.ContainerTransformer
CCLCorePlugin (CodeChickenLib-1.8-1.1.2.133-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.RenderHookTransformer
BetterFps (BetterFps-1.1.0.jar)
  me.guichaguri.betterfps.BetterFpsTransformer
BOPLoadingPlugin (BiomesOPlenty-1.8-3.0.0.1389-universal.jar)
  
CodeChickenCorePlugin (CodeChickenCore-1.8-1.0.5.36-universal.jar)
  codechicken.core.asm.InterfaceDependancyTransformer
  codechicken.core.asm.TweakTransformer
  codechicken.core.asm.DelegatedTransformer
  codechicken.core.asm.DefaultImplementationTransformer
CCCDeobfPlugin (unknown)
  
CoreMod (Aroma1997Core-1.8-1.0.3.4.jar)
  
NEICorePlugin (NotEnoughItems-1.8-1.0.5.104-universal.jar)
  codechicken.nei.asm.NEITransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '2.1 NVIDIA-10.4.2 310.41.35f01' Renderer: 'NVIDIA GeForce GTX 680MX OpenGL Engine'
	Launched Version: 1.8
	LWJGL: 2.9.2
	OpenGL: NVIDIA GeForce GTX 680MX OpenGL Engine GL version 2.1 NVIDIA-10.4.2 310.41.35f01, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: [faithful32pack.zip]
	Current Language: English (US)
	Profiler Position: N/A (disabled)

**Comment by Adubbz** [comment]
Same as #535 (Despite the different number, i'm pretty certain it's the same bug)
