### ISSUE TITLE
Piton ID issue with latest #1465

### ISSUE THREAD

**Issue by chezpaul** [Glitchfiend/BiomesOPlenty#559]
Seems like with the latest Biomes, I get a Potion ID conflict with Emerald mod

http://pastebin.com/DQ8Vf6SU

I tried assigning Potion ID but it doesn't seem to read it. Whatever number I put in there will come back different. Should I try changing potion assign to false?
"potion auto assign" {
    B:"Potion Auto Assign"=true
}
"potions ids" {
    I:"Paralysis Potion ID"=27
    I:"Possession Potion ID"=21
}

Going back to #1462 doesn't fix the problem... Argh...
I did not update Emerald Mod...

**Comment by chezpaul** [comment]
If I set to false then I get all kinds of biomes ID conflicts. (even though your option is called POTION AUTO ASSIGN


---- Minecraft Crash Report ----
// Everything's going to plan. No, really, that was supposed to happen.

Time: 12/2/15 8:56 AM
Description: Conflicting biomes forced game to crash: 

code.elix_x.coremods.antiidconflict.managers.BiomesManager$BiomesIDConflictException: Conflict between biomes with same id caused game to crash.
Affected ids:
40 is asked by: Alps (biomesoplenty.common.biome.overworld.BiomeGenAlps), Arctic Ocean (com.lom.lotsomobsbiomes.BiomeGenArcticOcean)
41 is asked by: Arctic (biomesoplenty.common.biome.overworld.BiomeGenArctic), Antartica (com.lom.lotsomobsbiomes.BiomeGenAntartica)
42 is asked by: Bamboo Forest (biomesoplenty.common.biome.overworld.BiomeGenBambooForest), Dino Plains (com.lom.lotsomobsbiomes.BiomeGenDinoPlains)
43 is asked by: Bayou (biomesoplenty.common.biome.overworld.BiomeGenBayou), Dino Mountains (com.lom.lotsomobsbiomes.BiomeGenDinoMountains)
44 is asked by: Bog (biomesoplenty.common.biome.overworld.BiomeGenBog), Dino Ocean (com.lom.lotsomobsbiomes.BiomeGenDinoOcean)
45 is asked by: Boreal Forest (biomesoplenty.common.biome.overworld.BiomeGenBorealForest), Dino Islands (com.lom.lotsomobsbiomes.BiomeGenDinoIslands)
46 is asked by: Brushland (biomesoplenty.common.biome.overworld.BiomeGenBrushland), Dino Jungle (com.lom.lotsomobsbiomes.BiomeGenDinoJungle), Ice Plains (com.lom.lotsomobsbiomes.BiomeGenIcePlains)
47 is asked by: Canyon (biomesoplenty.common.biome.overworld.BiomeGenCanyon), Ice Mountains (com.lom.lotsomobsbiomes.BiomeGenIceMountains)
48 is asked by: Chaparral (biomesoplenty.common.biome.overworld.BiomeGenChaparral), Ice Ocean (com.lom.lotsomobsbiomes.BiomeGenIceOcean)
49 is asked by: Cherry Blossom Grove (biomesoplenty.common.biome.overworld.BiomeGenCherryBlossomGrove), Ice Islands (com.lom.lotsomobsbiomes.BiomeGenIceIslands)
55 is asked by: Deciduous Forest (biomesoplenty.common.biome.overworld.BiomeGenDeciduousForest), Tropical Beach (com.lom.lotsomobsbiomes.BiomeGenTropical)
100 is asked by: Kelp Forest (biomesoplenty.common.biome.overworld.ocean.BiomeGenKelpForest), WitchwoodForest (am2.worldgen.BiomeWitchwoodForest)
118 is asked by: Visceral Heap (biomesoplenty.common.biome.nether.BiomeGenVisceralHeap), Twilight Lake (twilightforest.biomes.TFBiomeTwilightLake)
119 is asked by: Undergarden (biomesoplenty.common.biome.nether.BiomeGenUndergarden), Twilight Forest (twilightforest.biomes.TFBiomeTwilightForest)
120 is asked by: Polar Chasm (biomesoplenty.common.biome.nether.BiomeGenPolarChasm), Dense Twilight Forest (twilightforest.biomes.TFBiomeTwilightForestVariant)
121 is asked by: Spectral Garden (biomesoplenty.common.biome.end.BiomeGenSpectralGarden), Twilight Highlands (twilightforest.biomes.TFBiomeHighlands)
122 is asked by: Lush River (biomesoplenty.common.biome.overworld.tech.BiomeGenLushRiver), Mushroom Forest (twilightforest.biomes.TFBiomeMushrooms)
123 is asked by: Dry River (biomesoplenty.common.biome.overworld.tech.BiomeGenDryRiver), Twilight Swamp (twilightforest.biomes.TFBiomeSwamp)

	at code.elix_x.coremods.antiidconflict.managers.BiomesManager.crash(BiomesManager.java:207)
	at code.elix_x.coremods.antiidconflict.managers.BiomesManager.postinit(BiomesManager.java:53)
	at code.elix_x.coremods.antiidconflict.AntiIdConflictBase.postinit(AntiIdConflictBase.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:742)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by chezpaul** [comment]
So how can I assign potion paralysis to something else other than #25?

**Comment by Bogdan-G** [comment]
Back in another mod going potions
