### ISSUE TITLE
ArrayIndexOutofBoundsException: Crash in BlockBOPNewGrass

### ISSUE THREAD

**Issue by cocopuffs99** [Glitchfiend/BiomesOPlenty#576]
Crash when starting new world with latest BOP (as well as recommended version).  full log: http://pastebin.com/S6Ei0A30

java.lang.ArrayIndexOutOfBoundsException: 4
    at biomesoplenty.common.blocks.BlockBOPNewGrass.getUnlocalizedName(BlockBOPNewGrass.java:175)
    at biomesoplenty.common.itemblocks.ItemBlockBOPMetadata.func_77667_c(ItemBlockBOPMetadata.java:24)

**Comment by cocopuffs99** [comment]
seems to be conflicting with better hud mod
i removed better hud and the error went away
sent a message to betterHUD mod maker

http://pastebin.com/wAGvP8X7

**Comment by fewizz** [comment]
Close this pls.
