### ISSUE TITLE
1.8.9 Crash on World Generation

### ISSUE THREAD

**Issue by Dmitchell94** [Glitchfiend/BiomesOPlenty#629]
every time i try to load into a world it crashes. crash report below:
BiomesOPlenty: 1.8.9-3.0.0.1673
Forge: 11.15.0.1710

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CorePlugin (Fluxed Redstone-1.0.1.9.jar)
  TransformerLoader (OpenComputers-MC1.8.9-1.5.21.1.jar)
  LoadingPlugin (Bloodmoon-MC1.8.8-1.4.jar)
  FldLoadingPlugin (FastLeafDecay-1.8-1.6.jar)
  LoadingPlugin (RandomThings-MC1.8.9-3.5.8.jar)
  ThaumcraftLoader (Thaumcraft-1.8.9-5.1.3.jar)
  FMLPlugin (InventoryTweaks-1.60-beta-30.jar)
  thaumicinfusion (ThaumicInfusion-4.75.jar)
  LoadingPlugin (HardcoreDarkness-MC1.8.8-1.8.jar)
  NowWithRendering (redstonepaste-mc1.8.8-1.7.2.jar)
  CCLCorePlugin (CodeChickenLib-1.8-1.1.2.139-universal.jar)
Contact their authors BEFORE contacting forge

// Oh - I know what I did wrong!

Time: 1/21/16 12:12 AM
Description: Exception in server tick loop

java.lang.IllegalArgumentException
	at net.minecraft.util.WeightedRandom.func_76273_a(SourceFile:17)
	at net.minecraft.util.WeightedRandom.func_76271_a(SourceFile:35)
	at net.minecraft.world.SpawnerAnimals.func_77191_a(SpawnerAnimals.java:221)
	at biomesoplenty.common.world.ChunkProviderGenerateBOP.func_73153_a(ChunkProviderGenerateBOP.java:542)
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:261)
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1081)
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:172)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:114)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:84)
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:307)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:181)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:205)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:441)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 8.1 (amd64) version 6.3
	CPU: 4x Intel(R) Core(TM) i3-2330M CPU @ 2.20GHz
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1184989208 bytes (1130 MB) / 2234249216 bytes (2130 MB) up to 5355339776 bytes (5107 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx5G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 1, tallocated: 105
	FML: MCP 9.19 Powered by Forge 11.15.0.1710 Optifine OptiFine_1.8.9_HD_U_H2 52 mods loaded, 52 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAA	mcp{9.18} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.0.1710.jar) 
	UCHIJAA	Forge{11.15.0.1710} [Minecraft Forge] (forge-1.8.9-11.15.0.1710.jar) 
	UCHIJAA	OpenComputers|Core{1.5.21.1} [OpenComputers (Core)] (minecraft.jar) 
	UCHIJAA	securitycraft{v1.8.1} [SecurityCraft] ([1.8.8] SecurityCraft v1.8.1.jar) 
	UCHIJAA	additionalbanners{1.0.0} [Additional Banners] (AdditionalBanners-1.1.0.jar) 
	UCHIJAA	bagginses{2.1.4} [Bagginses] (Bagginses-1.8.9-2.1.4.jar) 
	UCHIJAA	BiomesOPlenty{3.0.0} [Biomes O' Plenty] (BiomesOPlenty-1.8.9-3.0.0.1673-universal.jar) 
	UCHIJAA	BloodMagic{1.8.9-2.0.0-6} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.8.9-2.0.0-6.jar) 
	UCHIJAA	Bloodmoon{1.2} [Bloodmoon] (Bloodmoon-MC1.8.8-1.4.jar) 
	UCHIJAA	bookshelfapi{2.2.3} [Bookshelf] (Bookshelf-1.8.9-2.2.3.jar) 
	UCHIJAA	ChestTransporter{2.2.0} [Chest Transporter] (ChestTransporter-2.2.0-MC1.8.9.jar) 
	UCHIJAA	ComputerCraft{1.78} [ComputerCraft] (ComputerCraft1.78.jar) 
	UCHIJAA	DurabilityShow{2.1.2} [Durability Show] (Durability Show-1.8.9-2.1.2.jar) 
	UCHIJAA	enderrift{0.70} [Ender-Rift] (EnderRift-0.70.jar) 
	UCHIJAA	EnderZoo{1.8.9-1.1.0} [Ender Zoo] (EnderZoo-1.8.9-1.1.2.jar) 
	UCHIJAA	Baubles{1.1.3.0} [Baubles] (Baubles-1.8.9-1.1.3.0.jar) 
	UCHIJAA	Thaumcraft{5.1.3} [Thaumcraft] (Thaumcraft-1.8.9-5.1.3.jar) 
	UCHIJAA	ExtraFood{0.7.51} [Extra Food] (ExtraFood-1.8.9-0.7.51.jar) 
	UCHIJAA	fastleafdecay{1.6} [Fast Leaf Decay] (FastLeafDecay-1.8-1.6.jar) 
	UCHIJAA	mcmultipart{1.0.5} [MCMultiPart] (MCMultiPart-1.0.5-universal.jar) 
	UCHIJAA	reborncore{1.3.1.9} [RebornCore] (RebornCore-1.8.9-1.3.1.9-universal.jar) 
	UCHIJAA	fluxedredstone{1.0.1.9} [FluxedRedstone] (Fluxed Redstone-1.0.1.9.jar) 
	UCHIJAA	fluxedsolars{$GRADLEVERSION} [Fluxed Solars] (fluxedsolars-1.4.jar) 
	UCHIJAA	foundry{1.3.3.1} [Foundry] (Foundry-1.8.9-1.3.3.1.jar) 
	UCHIJAA	FunOres{1.0.4} [Fun Ores] (FunOres-1.8.9-1.0.4-25.jar) 
	UCHIJAA	gravestone{1.1.2} [Gravestone] (Gravestone Mod 1.1.2.jar) 
	UCHIJAA	HardcoreDarkness{1.8} [Hardcore Darkness] (HardcoreDarkness-MC1.8.8-1.8.jar) 
	UCHIJAA	inventorytweaks{1.60-beta-30-48a432c} [Inventory Tweaks] (InventoryTweaks-1.60-beta-30.jar) 
	UCHIJAA	IronChest{6.0.121.768} [Iron Chest] (ironchest-1.8.9-6.0.121.768.jar) 
	UCHIJAA	JEI{2.21.0.98} [Just Enough Items] (jei_1.8.9-2.21.0.98.jar) 
	UCHIJAA	JEIAddons{0.9.0.32} [Just Enough Items Addons] (JEIAddons_1.8.9-0.9.0.32.jar) 
	UCHIJAA	journeymap{5.1.3} [JourneyMap] (journeymap-1.8.8-5.1.3-unlimited.jar) 
	UCHIJAA	MoreFurnaces{1.5.0} [More Furnaces] (MoreFurnaces-1.5.0-MC1.8.9.jar) 
	UCHIJAA	MultiPageChest{1.4.0} [Multi Page Chest] (MultiPageChest-1.4.0-MC1.8.9.jar) 
	UCHIJAA	NecromancyPlus{1.0} [NecromancyPlus] (Necromancy  1.0 1.8.9.jar) 
	UCHIJAA	neotech{2.2.3} [NeoTech] (NeoTech-1.8.9-2.2.3.jar) 
	UCHIJAA	OpenComputers{1.5.21.1} [OpenComputers] (OpenComputers-MC1.8.9-1.5.21.1.jar) 
	UCHIJAA	PneumaticCraft{1.13.2-3} [PneumaticCraft] (PneumaticCraft-1.8.9-1.13.2-3-universal.jar) 
	UCHIJAA	RandomThings{3.5.8} [Random Things] (RandomThings-MC1.8.9-3.5.8.jar) 
	UCHIJAA	redstonepaste{1.7.2} [Redstone Paste] (redstonepaste-mc1.8.8-1.7.2.jar) 
	UCHIJAA	Roguelike{1.4.5} [Roguelike Dungeons] (RoguelikeDungeons-1.8.9-1.4.5.jar) 
	UCHIJAA	sem{1.4.3} [Steam Engines Mod] (sem-mc1_8_9-1.4.3.jar) 
	UCHIJAA	semmagie{1.4.3} [Steam Engines Mod - Magie Addon] (sem-mc1_8_9-1.4.3.jar) 
	UCHIJAA	sodacanutils{2.0.0} [Sodacan Utilities] (sodacanutils-2.0.3.jar) 
	UCHIJAA	Talismans 2{2.2.0} [Talismans 2] (Talismans2-1.8.9-2.2.0.jar) 
	UCHIJAA	thaumicinfusion{4.75} [Thaumic Infusion] (ThaumicInfusion-4.75.jar) 
	UCHIJAA	thelittlethings{1.2.1-Forge1.8.9} [The Little Things] (The Little Things-v.1.2.1-mc1.8.9.jar) 
	UCHIJAA	thutcore{2.2.1} [ThutCore] (thutcore-2.2.1.jar) 
	UCHIJAA	thuttech{2.2.5} [Thut's Tech] (thuttech-2.2.5.jar) 
	UCHIJAA	VeinMiner{0.31.2_build.unknown} [Vein Miner] (VeinMiner-1.8.9_0.31.2.unknown.jar) 
	UCHIJAA	VeinMinerModSupport{0.31.2_build.unknown} [Mod Support] (VeinMiner-1.8.9_0.31.2.unknown.jar) 
	Loaded coremods (and transformers): 
CorePlugin (Fluxed Redstone-1.0.1.9.jar)
  
TransformerLoader (OpenComputers-MC1.8.9-1.5.21.1.jar)
  li.cil.oc.common.asm.ClassTransformer
LoadingPlugin (Bloodmoon-MC1.8.8-1.4.jar)
  lumien.bloodmoon.asm.ClassTransformer
FldLoadingPlugin (FastLeafDecay-1.8-1.6.jar)
  com.olafski.fastleafdecay.FldTransformer
LoadingPlugin (RandomThings-MC1.8.9-3.5.8.jar)
  lumien.randomthings.asm.ClassTransformer
ThaumcraftLoader (Thaumcraft-1.8.9-5.1.3.jar)
  
FMLPlugin (InventoryTweaks-1.60-beta-30.jar)
  invtweaks.forge.asm.ContainerTransformer
thaumicinfusion (ThaumicInfusion-4.75.jar)
  drunkmafia.thaumicinfusion.common.asm.BlockTransformer
  drunkmafia.thaumicinfusion.common.asm.WorldTransformer
LoadingPlugin (HardcoreDarkness-MC1.8.8-1.8.jar)
  lumien.hardcoredarkness.asm.ClassTransformer
NowWithRendering (redstonepaste-mc1.8.8-1.7.2.jar)
  net.fybertech.nwr.NowWithRendering
CCLCorePlugin (CodeChickenLib-1.8-1.1.2.139-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.RenderHookTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
```

**Comment by Adubbz** [comment]
That issue is not necessarily be BoP, it just shows that a biome from any one of those mods has given an invalid spawnableCreatureList (possibly null). If this happens with BoP on its own feel free to reopen this, but otherwise it's really hard to tell if it's us or not.

**Comment by Dmitchell94** [comment]
I am sorry on further testing this seems to only happen when both Biomes of plenty and NecromancyPlus are installed together. I have reported this to NecromancyPlus.

**Comment by Adubbz** [comment]
No worries, it seems likely to me that NecromancyPlus probably adds a biome and for whatever reason, their list of creatures that can spawn isn't valid. It's certainly reasonable reporting it to us, since it's not immediately obvious who is at fault
