### ISSUE TITLE
Crash on start, file models/biome_finder.json not found

### ISSUE THREAD

**Issue by Sylvestrina** [Glitchfiend/BiomesOPlenty#646]
Hi,

I get a crash right at the start of Minecraft when Forge initializes the mods. Crash report:
---- Minecraft Crash Report ----
// I just don't know what went wrong :(

Time: 01.02.16 11:01
Description: Initializing game

**java.lang.RuntimeException: java.io.FileNotFoundException: biomesoplenty:models/biome_finder.json**
	at com.google.common.base.Throwables.propagate(Throwables.java:160)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:146)
	at net.minecraftforge.client.ForgeHooksClient.onModelBake(ForgeHooksClient.java:353)
	at net.minecraft.client.resources.model.ModelManager.func_110549_a(ModelManager.java:30)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:120)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:478)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.io.FileNotFoundException: biomesoplenty:models/biome_finder.json
	at net.minecraft.client.resources.FallbackResourceManager.func_110536_a(FallbackResourceManager.java:67)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110536_a(SimpleReloadableResourceManager.java:64)
	at net.minecraft.client.resources.model.ModelBakery.func_177594_c(ModelBakery.java:243)
	at net.minecraftforge.client.model.ModelLoader.access$1100(ModelLoader.java:76)
	at net.minecraftforge.client.model.ModelLoader$VanillaLoader.loadModel(ModelLoader.java:823)
	at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:108)
	at net.minecraftforge.client.model.ModelLoader.loadAnyModel(ModelLoader.java:324)
	at net.minecraftforge.client.model.ModelLoader.getModel(ModelLoader.java:305)
	at biomesoplenty.client.handler.ModelBakeHandler.onModelBake(ModelBakeHandler.java:63)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_27_ModelBakeHandler_onModelBake_ModelBakeEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:55)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	... 12 more

There's more, but I think it's boring. My guess is that the location biomesoplenty:models/biome_finder.json is wrong and it should be biomesoplenty:models/**item**/biome_finder.json instead, because that file actually exists.

Anyway, thank you very much for this great mod!

Kind regards,
Sylvestrina

**Comment by Adubbz** [comment]
Need the full log really, that's missing quite a bit of information. Make sure you're using the latest version of Forge and BoP for 1.8.9, and try without any other mods (if there are any, again, the need the full log)

**Comment by Sylvestrina** [comment]
Okay, I've updated Forge and removed one other mod. Still the same error:
---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// Oops.

Time: 01.02.16 20:59
Description: Initializing game

java.lang.RuntimeException: java.io.FileNotFoundException: biomesoplenty:models/biome_finder.json
	at com.google.common.base.Throwables.propagate(Throwables.java:160)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:146)
	at net.minecraftforge.client.ForgeHooksClient.onModelBake(ForgeHooksClient.java:353)
	at net.minecraft.client.resources.model.ModelManager.func_110549_a(ModelManager.java:30)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:120)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:478)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.io.FileNotFoundException: biomesoplenty:models/biome_finder.json
	at net.minecraft.client.resources.FallbackResourceManager.func_110536_a(FallbackResourceManager.java:67)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110536_a(SimpleReloadableResourceManager.java:64)
	at net.minecraft.client.resources.model.ModelBakery.func_177594_c(ModelBakery.java:243)
	at net.minecraftforge.client.model.ModelLoader.access$1100(ModelLoader.java:76)
	at net.minecraftforge.client.model.ModelLoader$VanillaLoader.loadModel(ModelLoader.java:823)
	at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:108)
	at net.minecraftforge.client.model.ModelLoader.loadAnyModel(ModelLoader.java:324)
	at net.minecraftforge.client.model.ModelLoader.getModel(ModelLoader.java:305)
	at biomesoplenty.client.handler.ModelBakeHandler.onModelBake(ModelBakeHandler.java:63)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_27_ModelBakeHandler_onModelBake_ModelBakeEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:55)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	... 12 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.google.common.base.Throwables.propagate(Throwables.java:160)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:146)
	at net.minecraftforge.client.ForgeHooksClient.onModelBake(ForgeHooksClient.java:353)
	at net.minecraft.client.resources.model.ModelManager.func_110549_a(ModelManager.java:30)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:120)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:478)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_66, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 237959184 bytes (226 MB) / 1093664768 bytes (1043 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.19 Powered by Forge 11.15.0.1684 4 mods loaded, 4 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.18} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.0.1684.jar) 
	UCH	Forge{11.15.0.1684} [Minecraft Forge] (forge-1.8.9-11.15.0.1684.jar) 
	UCH	BiomesOPlenty{3.0.0} [Biomes O' Plenty] (BiomesOPlenty-1.8.9-3.0.0.1768-universal.jar) 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13399 Compatibility Profile Context 15.200.1062.1004' Renderer: 'AMD Radeon R9 200 Series'
	Launched Version: 1.8.9-forge1.8.9-11.15.0.1684
	LWJGL: 2.9.4
	OpenGL: AMD Radeon R9 200 Series GL version 4.5.13399 Compatibility Profile Context 15.200.1062.1004, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: ZRayBiomesOPlenty
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x AMD FX(tm)-8120 Eight-Core Processor

**Comment by Adubbz** [comment]
That's not the full log, that's still just the crash report. Nevertheless, I think the issue is that resource pack you seem to have installed "ZRayBiomesOPlenty"

**Comment by Sylvestrina** [comment]
It wasn't the resource pack, but Forge. After deleting all my profiles and reinstalling Forge, it works now.

Thanks for your time!
/closed

**Comment by Adubbz** [comment]
Interesting, well, glad you managed to fix it. I'm not entirely sure why Forge isn't showing a screen beforehand with the minimum version requirements, I guess another thing to look at
