### ISSUE TITLE
My game crashes

### ISSUE THREAD

**Issue by Snowylei** [Glitchfiend/BiomesOPlenty#675]
My game started crashing when I downloaded Biomes o' plently, I'm not sure whats causing this to happen

**Comment by GirafiStudios** [comment]
What version of Biomes O Plenty are you using? Do you have any crashlog? (Please use Pastebin to post it)

**Comment by Snowylei** [comment]
I'm using 1.8.9  and how do i use pastebin to post the crash log?

**Comment by GirafiStudios** [comment]
You got to http://pastebin.com/ , copy/paste in the crashlog and press create new paste.

**Comment by Snowylei** [comment]
---- Minecraft Crash Report ----
 
WARNING: coremods are present:
Contact their authors BEFORE contacting forge
 
// On the bright side, I bought you a teddy bear!
 
Time: 2/14/16 11:30 AM
Description: Unexpected error
 
java.lang.NullPointerException: Unexpected error
    at Variables.renderItem(Variables.java:616)
    at WrappedItemStack.render(WrappedItemStack.java:42)
    at eu.the5zig.mod.render.item.ItemRenderItem.render(ItemRenderItem.java:24)
    at eu.the5zig.mod.render.DisplayRenderer.renderDisplay(DisplayRenderer.java:217)
    at eu.the5zig.mod.render.DisplayRenderer.drawScreen(DisplayRenderer.java:102)
    at eu.the5zig.mod.render.GuiIngame.renderGameOverlay(GuiIngame.java:26)
    at BytecodeHook.onRenderGameOverlay(BytecodeHook.java:82)
    at net.minecraftforge.client.GuiIngameForge.renderHUDText(GuiIngameForge.java)
    at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:149)
    at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1331)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1051)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
 
 
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
 
-- Head --
Stacktrace:
    at Variables.renderItem(Variables.java:616)
    at WrappedItemStack.render(WrappedItemStack.java:42)
    at eu.the5zig.mod.render.item.ItemRenderItem.render(ItemRenderItem.java:24)
    at eu.the5zig.mod.render.DisplayRenderer.renderDisplay(DisplayRenderer.java:217)
    at eu.the5zig.mod.render.DisplayRenderer.drawScreen(DisplayRenderer.java:102)
    at eu.the5zig.mod.render.GuiIngame.renderGameOverlay(GuiIngame.java:26)
    at BytecodeHook.onRenderGameOverlay(BytecodeHook.java:82)
    at net.minecraftforge.client.GuiIngameForge.renderHUDText(GuiIngameForge.java)
    at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:149)
 
-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityPlayerSP['Ninjablaze78'/79, l='MpServer', x=-266.50, y=4.00, z=-450.50]]
    Chunk stats: MultiplayerChunkCache: 250, 250
    Level seed: 0
    Level generator: ID 01 - flat, ver 0. Features enabled: false
    Level generator options:
    Level spawn location: -260.00,4.00,-442.00 - World: (-260,4,-442), Chunk: (at 12,0,6 in -17,-28; contains blocks -272,0,-448 to -257,255,-433), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
    Level time: 39 game time, 39 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
    Forced entities: 1 total; [EntityPlayerSP['Ninjablaze78'/79, l='MpServer', x=-266.50, y=4.00, z=-450.50]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:404)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2536)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
 
-- System Details --
Details:
    Minecraft Version: 1.8.9
    Operating System: Windows 8.1 (amd64) version 6.3
    CPU: 4x Intel(R) Celeron(R) CPU N2920 @ 1.86GHz
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 336321552 bytes (320 MB) / 798007296 bytes (761 MB) up to 1060372480 bytes (1011 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP 9.19 Powered by Forge 11.15.1.1722 Optifine OptiFine_1.8.9_HD_U_H2 9 mods loaded, 9 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.19} [Minecraft Coder Pack] (minecraft.jar)
    UCHIJAAAA   FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.1722.jar)
    UCHIJAAAA   Forge{11.15.1.1722} [Minecraft Forge] (forge-1.8.9-11.15.1.1722.jar)
    UCHIJAAAA   BiomesOPlenty{3.0.0} [Biomes O' Plenty] (BiomesOPlenty-1.8.9-3.0.0.1890-universal.jar)
    UCHIJAAAA   InventoryPets{1.3.91} [Inventory Pets] (inventorypets-1.8.9-1.3.91.jar)
    UCHIJAAAA   JEI{2.25.11.150} [Just Enough Items] (jei_1.8.9-2.25.11.150.jar)
    UCHIJAAAA   RadixCore{1.8.9-2.1.0} [RadixCore] (RadixCore-1.8.9-2.1.0-universal.jar)
    UCHIJAAAA   MCA{1.8.9-5.1.1.2} [Minecraft Comes Alive] (MCA-1.8.9-5.1.1.2-universal.jar)
    UCHIJAAAA   cfm{3.6} [MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.6.1(1.8.9).jar)
    Loaded coremods (and transformers):
    GL info: ' Vendor: 'Intel' Version: '4.0.0 - Build 10.18.10.3349' Renderer: 'Intel(R) HD Graphics'
    Launched Version: 1.8.9-forge1.8.9-11.15.1.1722
    LWJGL: 2.9.4
    OpenGL: Intel(R) HD Graphics GL version 4.0.0 - Build 10.18.10.3349, Intel
    GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.
 
    Using VBOs: No
    Is Modded: Definitely; Client brand changed to 'fml,forge'
    Type: Client (map_client.txt)
    Resource Packs: Plast Pack - modified by lolboatz.zip
    Current Language: English (UK)
    Profiler Position: N/A (disabled)
    CPU: 4x Intel(R) Celeron(R) CPU N2920 @ 1.86GHz
    The 5zig Mod Version: 3.4.1
    Forge: true

**Comment by GirafiStudios** [comment]
Well that is not using pastebin, but okay..
And this have nothing to do with Biomes O plenty it's caused by "eu.the5zig.mod". Looks like you're trying to run a bukkit plugin on a forge server..

**Comment by Snowylei** [comment]
ohh....

**Comment by GirafiStudios** [comment]
Not 100% but some sort of announcement plugin I think?
But yeah anyways this have nothing to do with Biomes O Plenty, so please close :)

**Comment by Snowylei** [comment]
ok, thanks for your help

**Comment by Snowylei** [comment]
closes #675
