### ISSUE TITLE
Exception in server tick loop

### ISSUE THREAD

**Issue by alexho66** [Glitchfiend/BiomesOPlenty#735]
---- Minecraft Crash Report ----
// Why did you do that?

Time: 08.04.16 14:56
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: net/minecraftforge/event/entity/player/EntityInteractEvent
	at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:179)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:559)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:93)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:320)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:119)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoClassDefFoundError: net/minecraftforge/event/entity/player/EntityInteractEvent
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
	at java.lang.Class.privateGetPublicMethods(Unknown Source)
	at java.lang.Class.getMethods(Unknown Source)
	at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:60)
	at biomesoplenty.common.init.ModHandlers.init(ModHandlers.java:38)
	at biomesoplenty.core.BiomesOPlenty.preInit(BiomesOPlenty.java:76)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:560)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:228)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:206)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.Eus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:556)
	... 5 more
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.event.entity.player.EntityInteractEvent
	at net.minecraft.lauventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBnchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 39 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 41 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 283115048 bytes (269 MB) / 428867584 bytes (409 MB) up to 954728448 bytes (910 MB)
	JVM Flags: 1 total; -Xmx1G
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.23 Powered by Forge 12.16.0.1858 4 mods loaded, 4 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.9-12.16.0.1858-1.9-universal.jar) 
	UCH	Forge{12.16.0.1858} [Minecraft Forge] (forge-1.9-12.16.0.1858-1.9-universal.jar) 
	UCE	BiomesOPlenty{4.0.0} [Biomes O' Plenty] (BiomesOPlenty-1.9-4.0.0.1948-universal.jar) 
	Loaded coremods (and transformers): 
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by alexho66** [comment]
# pls help or fix

**Comment by GirafiStudios** [comment]
Update to latest version of Biomes O' Plenty and Forge.

**Comment by alexho66** [comment]
forge-1.9-12.16.0.1858-1.9-universal
BiomesOPlenty-1.9-4.0.0.1948-universal

**Comment by GirafiStudios** [comment]
Your version of Biomes O' Plenty is 53 versions behind..

**Comment by alexho66** [comment]
oh

**Comment by alexho66** [comment]
omg

**Comment by alexho66** [comment]
what is the best Version

**Comment by GirafiStudios** [comment]
Latest version, as I said.

**Comment by alexho66** [comment]
wht is the newest

**Comment by GirafiStudios** [comment]
1948 + 53 = 2001, so 4.0.0.2001.

**Comment by alexho66** [comment]
2001 is for 1.8.9 ? http://mods.curse.com/mc-mods/minecraft/220318-biomes-o-plenty#t1:other-downloads
2000 is for 1.9

**Comment by Adubbz** [comment]
Please read the issue template, in particular, the section where it says in all capitals: BEFORE SUBMITTING! Under that section this exact solution was listed and you needed to make sure of it first:

- [ ] Biomes O' Plenty is updated to the latest available version

I understand you may not be familiar with how this works, and that's fine, but please for both your own sake and ours read what's there. The latest version for 1.9 is 2000. It's always what's listed at the top.

**Comment by GirafiStudios** [comment]
You're right. 2000 it's then..

**Comment by alexho66** [comment]
sorry
