### ISSUE TITLE
[4.0.2.2011] Crash: A generator with name grass_splatter_new already exists!

### ISSUE THREAD

**Issue by Syndaryl** [Glitchfiend/BiomesOPlenty#745]
#### Issue Description:
Minecraft crashes with Exception in server tick loop upon world loading

#### Steps to reproduce:

Annoyingly, this occurs /sometimes/. 
I created a new world with the seed "Fox In Net". I walked around a little bit (1-2 minutes) then restarted Minecraft for Reasons ( = I misclicked). Upon reloading my world it suddenly exited with the following exception (see Additional Information for stack trace)
I can't seem to reliably repeat this behavior, which is frustrating.

#### Additional Information:

Time: 15/04/16 10:27 AM
Description: Exception in server tick loop

java.lang.RuntimeException: A generator with name grass_splatter_new already exists!
	at biomesoplenty.api.biome.generation.GenerationManager.addGenerator(GenerationManager.java:28)
	at biomesoplenty.api.biome.BOPBiome.addGenerator(BOPBiome.java:261)
	at biomesoplenty.common.biome.overworld.BiomeGenOutback.applySettings(BiomeGenOutback.java:90)
	at biomesoplenty.common.world.BiomeProviderBOP.<init>(BiomeProviderBOP.java:73)
	at biomesoplenty.common.world.BiomeProviderBOP.<init>(BiomeProviderBOP.java:86)
	at biomesoplenty.common.world.WorldTypeBOP.getBiomeProvider(WorldTypeBOP.java:33)
	at net.minecraft.world.WorldProvider.func_76572_b(WorldProvider.java:55)
	at net.minecraft.world.WorldProvider.func_76558_a(WorldProvider.java:38)
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:112)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:84)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:119)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at java.lang.Thread.run(Unknown Source)

____
#### Affected Versions (Exact numbers, do *not* use "latest"):

- Biomes O' Plenty:  4.0.2.2011
- Minecraft: Version 1.9.0
- Forge: 1.9-12.16.0.1865-1.9

No Optifine, Cauldron, etc.

**Comment by Adubbz** [comment]
Should be fixed now

**Comment by Ozzymud** [comment]
It's back in 1.9.4 it seems, same randomness as the original.

`java.lang.RuntimeException: A generator with name grass_splatter_new already exists!
	at biomesoplenty.common.world.GenerationManager.addGenerator(GenerationManager.java:31)
	at biomesoplenty.common.biome.overworld.BOPBiome.addGenerator(BOPBiome.java:268)
	at biomesoplenty.common.biome.overworld.BiomeGenQuagmire.applySettings(BiomeGenQuagmire.java:94)
	at biomesoplenty.common.world.BiomeProviderBOP.<init>(BiomeProviderBOP.java:74)
	at biomesoplenty.common.world.BiomeProviderBOP.<init>(BiomeProviderBOP.java:87)
	at biomesoplenty.common.world.WorldTypeBOP.getBiomeProvider(WorldTypeBOP.java:33)
	at net.minecraft.world.WorldProvider.func_76572_b(WorldProvider.java:56)
	at net.minecraft.world.WorldProvider.func_76558_a(WorldProvider.java:39)
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:113)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:84)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:119)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:429)
	at java.lang.Thread.run(Unknown Source)`

- BiomesOPlenty: 1.9.4-4.1.0.2026 through 4.1.0.2029
- Minecraft: Version 1.9.4
- Forge: 1.9.4-12.17.0.1965

Didn't test earlier then 2026, it was the starting version in the "All the Mods" pack.

**Comment by Syndaryl** [comment]
Can confirm. Disabling BIOP soil types isn't stopping it either this time, which surprised me.
