### ISSUE TITLE
BOP 1.9 Crash

### ISSUE THREAD

**Issue by Peach774** [Glitchfiend/BiomesOPlenty#751]
Forge 1865
Minecraft 1.9
Optifine installed
Newest BoP version

Exception in server tick loop

java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=variant, clazz=class biomesoplenty.common.block.BlockBOPGrass$BOPGrassType, values=[spectral_moss, smoldering, loamy, sandy, silty, origin, overgrown_netherrack, daisy]} as it does not exist in BlockStateContainer{block=minecraft:air, properties=[]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:192)
	at biomesoplenty.common.block.BlockBOPGrass.canSustainPlantType(BlockBOPGrass.java:123)
	at biomesoplenty.common.block.BlockBOPGrass.canSustainPlant(BlockBOPGrass.java:164)
	at net.minecraft.block.BlockCactus.func_176586_d(BlockCactus.java:114)
	at net.minecraft.world.gen.feature.WorldGenCactus.func_180709_b(SourceFile:19)
	at rtg.world.biome.realistic.vanilla.RealisticBiomeVanillaMesa.rDecorate(RealisticBiomeVanillaMesa.java:135)
	at rtg.world.gen.ChunkProviderRTG.func_185931_b(ChunkProviderRTG.java:601)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:996)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:979)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:52)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:12)
	at net.minecraftforge.common.util.AsynchronousExecutor$Task.finish(AsynchronousExecutor.java:188)
	at net.minecraftforge.common.util.AsynchronousExecutor$Task.access$800(AsynchronousExecutor.java:73)
	at net.minecraftforge.common.util.AsynchronousExecutor.finishActive(AsynchronousExecutor.java:353)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:30)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:669)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:609)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:239)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:467)
	at java.lang.Thread.run(Thread.java:745)

Full crash log and fml-client log are attached.
[crash-2016-05-01_15.16.34-server.txt](https://github.com/Glitchfiend/BiomesOPlenty/files/244384/crash-2016-05-01_15.16.34-server.txt)

**Comment by Awkanic** [comment]
I have also experienced this. To reproduce, try to place a cactus on a bop sandy-grass block in an Outback Biome.

**Comment by Morpheus1101** [comment]
I to am getting this crash http://pastebin.com/Vd8ZF3Vy  difference being i cant load the game without a crash on a brand new world

**Comment by swyrl** [comment]
@awkanic In my crash the world cannot generate at all.

**Comment by dannydjdk** [comment]
Similar crash http://pastebin.com/83cuFvfk when loading Mesa Biome. Game crashes repeatedly until player is moved using MCEdit. Seems to only happen with newly loaded chunks. If I go back to the same area later, I can get a little further into the Mesa before it crashes again.
It appears Peach774 and I are both using Realistic Terrain Gen, but Morpheus1101 is not. In all 3 cases it appears another mod is trying to place some kind of plant on a BOP block.

**Comment by dannydjdk** [comment]
Here's a crash report on a clean install with nothing but forge 12.16.1.1891 and BOP 1.9-4.0.2.2018.
http://pastebin.com/gyA14R24

Steps to produce:
- Placed a Sandy Grass block
- Attempt to place a cactus on the Sandy Grass block. (as Awkanic suggested)

**Comment by ClockwerkKaiser** [comment]
I'm having the same exact issue.

To play around this, you can disable BoP Soils and BoP Grass under the "customize" setting when creating a new world. 

That way you get the BoP worldgen, flowers, tress, etc. That's what I'll be doing until this bug is fixed.

**Comment by GirafiStudios** [comment]
It is a Forge bug. See the comment in https://github.com/Glitchfiend/BiomesOPlenty/issues/763
