### ISSUE TITLE
Severe Problem During Mod Loading

### ISSUE THREAD

**Issue by WAC02mc** [Glitchfiend/BiomesOPlenty#765]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  NowWithRendering (redstonepaste-mc1.9-1.7.3.jar)
  FldLoadingPlugin (FastLeafDecay-1.9-1.6.jar)
  LoadingPlugin (RandomThings-MC1.9-3.7.jar)
  BetterFoliageLoader (BetterFoliage-MC1.9-2.0.11.jar)
  BiomeTweakerCore (BiomeTweaker-1.9-2.1.210.jar)
  MalisisCorePlugin (malisiscore-1.9-3.0.6.jar)
  MalisisSwitchesPlugin (malisisswitches-1.9-2.0.0.jar)
  LoadingPlugin (Bloodmoon-MC1.9-1.4.1.jar)
Contact their authors BEFORE contacting forge

// Quite honestly, I wouldn't worry myself about that.

Time: 5/20/16 5:15 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: net/minecraftforge/event/entity/player/EntityInteractEvent
	at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:179)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:553)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:210)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:434)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:346)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: net/minecraftforge/event/entity/player/EntityInteractEvent
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2693)
	at java.lang.Class.getDeclaredMethods(Class.java:1967)
	at net.minecraftforge.fml.common.FMLModContainer.gatherAnnotations(FMLModContainer.java:345)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:534)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:228)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:206)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:522)
	... 10 more
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.event.entity.player.EntityInteractEvent
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 36 more
Caused by: java.lang.ArrayIndexOutOfBoundsException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 271299808 bytes (258 MB) / 1272971264 bytes (1214 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.23 Powered by Forge 12.16.1.1907 59 mods loaded, 58 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UC	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UC	FML{8.0.99.99} [Forge Mod Loader] (forge-1.9-12.16.1.1907.jar) 
	UC	Forge{12.16.1.1907} [Minecraft Forge] (forge-1.9-12.16.1.1907.jar) 
	UC	additionalbanners{1.1.0.11} [Additional Banners] (AdditionalBanners-1.9-1.1.0.16.jar) 
	UC	animalbikes{1.8} [Animal Bikes] (AnimalBikes_1.9.0(26mar16).jar) 
	UC	armorplus{1.13.2-1.9} [ArmorPlus] (ArmorPlus1.13.2(1.9).jar) 
	UC	bagginses{2.3.0b} [Bagginses] (Bagginses-1.9-2.3.0b.jar) 
	UC	Baubles{1.2.0.2} [Baubles] (Baubles-1.9-1.2.0.2.jar) 
	UC	BaublesHud{2.3.0} [Baubles-Hud] (BaublesHud-1.9-2.3.0.jar) 
	UC	BetterAchievements{0.2.5.20} [Better Achievements] (BetterAchievements-1.9-0.2.5.20.jar) 
	UC	BetterFoliage{2.0.11} [Better Foliage] (BetterFoliage-MC1.9-2.0.11.jar) 
	UC	BiomeTweaker{2.1.210} [BiomeTweaker] (BiomeTweaker-1.9-2.1.210.jar) 
	UC	JEI{3.4.0.204} [Just Enough Items] (jei_1.9.4-3.4.0.204.jar) 
	UC	BloodMagic{1.9-2.0.0-38} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.9-2.0.0-38.jar) 
	UC	Bloodmoon{1.2} [Bloodmoon] (Bloodmoon-MC1.9-1.4.1.jar) 
	UC	Chameleon{1.9-2.1.3} [Chameleon] (Chameleon-1.9-2.1.3.jar) 
	UC	chisel{@VERSION@} [Chisel] (Chisel-MC1.9-0.0.4.14.jar) 
	UC	customnpcs{1.9.0_beta} [CustomNPCs] (CustomNPCs_1.9.0_beta(20may16).jar) 
	UC	DurabilityShow{3.0.2} [Durability Show] (Durability Show-1.9-3.0.2.jar) 
	UC	emeraldobsidianmod{1.4} [Emerald & Obsidian tools/armor mod] (emeraldobsidianmod-1.9-1.4(beta).jar) 
	UC	ExtraFood{@VERSION@} [Extra Food] (ExtraFood-1.9-0.8.2.jar) 
	UC	golems{4.03} [Extra Golems] (ExtraGolems[1.9]-4.03.jar) 
	UC	fastleafdecay{1.6} [Fast Leaf Decay] (FastLeafDecay-1.9-1.6.jar) 
	UC	HealthBar{1.0.2} [Health Bar] (HealthBar-1.9-1.0.2-13.jar) 
	UC	hopperducts{1.4.7} [Hopper Ducts] (hopperducts-mc1.9-1.4.7.jar) 
	UE	samshorsefood{1.1.3} [Horse Upgrade Food] (HorseUpgradeFood-1.9-1.1.3.jar) 
	UC	IronChest{6.0.138.779} [Iron Chest] (ironchest-1.9-6.0.138.779.jar) 
	UC	journeymap{1.9-5.2.0b1} [JourneyMap] (journeymap-1.9-5.2.0b1-unlimited.jar) 
	UC	jeresources{0.4.5.29} [Just Enough Resources] (JustEnoughResources-1.9-0.4.5.29.jar) 
	UC	JET{1.2.28} [JustEnoughTooltips] (JustEnoughTooltips-1.9-1.2.28.jar) 
	UC	malisiscore{1.9-3.0.6} [MalisisCore] (malisiscore-1.9-3.0.6.jar) 
	UC	malisisblocks{1.9-3.0.1} [Malisis Blocks] (malisisblocks-1.9-3.0.1.jar) 
	UC	malisisdoors{1.9-4.0.1} [MalisisDoors] (malisisdoors-1.9-4.0.1.jar) 
	UC	malisisswitches{1.9-2.0.0} [Malisis Switches] (malisisswitches-1.9-2.0.0.jar) 
	UC	mantle{1.9-0.10.0.jenkins132} [Mantle] (Mantle-1.9-0.10.0.jar) 
	UC	Waila{1.7.0} [Waila] (Waila-1.7.0-B2_1.9.jar) 
	UC	moarsigns{3.0.0} [MoarSigns] (MoarSigns-1.9-3.0.0.jar) 
	UC	morefood{1.15d} [More Foods] (morefood-1.9-1854-1.15d.jar) 
	UC	moreplayermodels{1.9.0} [MorePlayerModels] (MorePlayerModels_1.9.0beta(01apr16).jar) 
	UC	nmsot{1.1.3-mc1.9} [No Mob Spawning on Trees] (NoMobSpawningOnTrees-1.1.3-mc1.9.jar) 
	UC	fodc{1.8.1} [Ore Dictionary Converter] (OreDictionaryConverter-1.8.1.jar) 
	UC	samsapples{1.1.5} [Power Apples] (PowerApples-1.9-1.1.5.jar) 
	UC	randomthings{3.7} [Random Things] (RandomThings-MC1.9-3.7.jar) 
	UC	redstonepaste{1.7.3} [Redstone Paste] (redstonepaste-mc1.9-1.7.3.jar) 
	UC	Roguelike{1.5.0} [Roguelike Dungeons] (RoguelikeDungeons-1.9-1.5.0.jar) 
	UC	SilentLib{1.0.7} [Silent Lib] (SilentLib-1.9-1.0.7-13.jar) 
	UC	SilentGems{2.0.11} [Silent's Gems] (SilentsGems-1.9-2.0.11-29.jar) 
	UC	SimpleLabels{0.0.1} [SimpleLabels] (simplelabels-0.0.2.jar) 
	UC	StorageDrawers{1.9-3.1.6} [Storage Drawers] (StorageDrawers-1.9-3.1.6.jar) 
	UC	tconstruct{1.9-2.3.0.jenkins193} [Tinkers' Construct] (TConstruct-1.9-2.3.0.jar) 
	UC	VeinMiner{0.31.5_build.forgePost18010} [Vein Miner] (VeinMiner-1.9_0.31.5.forgePost18010.jar) 
	UC	VeinMinerModSupport{0.31.5_build.forgePost18010} [Mod Support] (VeinMiner-1.9_0.31.5.forgePost18010.jar) 
	UC	WailaHarvestability{1.1.7} [Waila Harvestability] (WailaHarvestability-mc1.9-1.1.7.jar) 
	UC	ICSE{1.0.0.0} [I Can See Everything] (Wawla-1.9-2.2.0.186.jar) 
	UC	wawla{2.2.0.178} [What Are We Looking At] (Wawla-1.9-2.2.0.186.jar) 
	UC	weaponcaseloot{3.0.0-alpha} [WeaponCaseLoot] (weaponcaseloot-3.0.0-alpha.jar) 
	UC	worldedit{6.1.2} [WorldEdit] (worldedit-forge-mc1.9-6.1.2-dist.jar) 
	UC	WorldEditCuiFe{1.0.2} [WorldEdit CUI Forge Edition] (WorldEditCuiFe-v1.0.2-mf-1.9-12.16.1.1907.jar) 
	UD	BiomeTweakerCore{2.1.210} [BiomeTweaker Core] (minecraft.jar) 
	Loaded coremods (and transformers): 
NowWithRendering (redstonepaste-mc1.9-1.7.3.jar)
  net.fybertech.nwr.NowWithRendering
FldLoadingPlugin (FastLeafDecay-1.9-1.6.jar)
  com.olafski.fastleafdecay.FldTransformer
LoadingPlugin (RandomThings-MC1.9-3.7.jar)
  lumien.randomthings.asm.ClassTransformer
BetterFoliageLoader (BetterFoliage-MC1.9-2.0.11.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
BiomeTweakerCore (BiomeTweaker-1.9-2.1.210.jar)
  me.superckl.biometweaker.core.BiomeTweakerASMTransformer
MalisisCorePlugin (malisiscore-1.9-3.0.6.jar)
  net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
  net.malisis.core.util.chunkblock.ChunkBlockTransformer
  net.malisis.core.renderer.transformer.MalisisRendererTransformer
  net.malisis.core.renderer.icon.asm.TextureMapTransformer
MalisisSwitchesPlugin (malisisswitches-1.9-2.0.0.jar)
  net.malisis.switches.asm.MalisisSwitchesTransformer
LoadingPlugin (Bloodmoon-MC1.9-1.4.1.jar)
  lumien.bloodmoon.asm.ClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 361.43' Renderer: 'GeForce GTX 750 Ti/PCIe/SSE2'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)

Please help!

**Comment by GirafiStudios** [comment]
This is caused by the "new" PlayerInteractEvent, which EntityInteractEvent is now a part of too. Making sure you have all your mods on latest version should fix your problem :)
I'm not really sure why this is reported to Biomes O' Plenty, it's not even in your modpack?
