### ISSUE TITLE
Cannot get property PropertyEnum

### ISSUE THREAD

**Issue by ShadowDrakken** [Glitchfiend/BiomesOPlenty#778]
This is a server-side crash, doesn't affect the client except for the obvious disconnect when the server goes down. BoP Version 1.9-4.0.2.2018

Seems to be connected to sandy dirt and sandy grass biomes

Description: Exception in server tick loop

java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=variant, clazz=class biomesoplenty.common.block.BlockBOPGrass$BOPGrassType, values=[spectral_moss, smoldering, loamy, sandy, silty, origin, overgrown_netherrack, daisy]} as it does not exist in BlockStateContainer{block=minecraft:air, properties=[]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:192)
	at biomesoplenty.common.block.BlockBOPGrass.canSustainPlantType(BlockBOPGrass.java:123)
	at biomesoplenty.common.block.BlockBOPGrass.canSustainPlant(BlockBOPGrass.java:164)
	at net.minecraft.block.BlockCactus.func_176586_d(BlockCactus.java:114)
	at com.pam.harvestcraft.worldgen.LogFruitTreeWorldGen.generateAridGarden(LogFruitTreeWorldGen.java:63)
	at com.pam.harvestcraft.worldgen.LogFruitTreeWorldGen.generate(LogFruitTreeWorldGen.java:31)
	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:113)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:998)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:971)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:90)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:128)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:669)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:386)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:609)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:467)
	at java.lang.Thread.run(Thread.java:745)

**Comment by B0bbyD0llar** [comment]
Same problem here.

**Comment by Adubbz** [comment]
See https://github.com/Glitchfiend/BiomesOPlenty/issues/763
