### ISSUE TITLE
Game crashes when I load biomes o' plenty map

### ISSUE THREAD

**Issue by Darkorinth** [Glitchfiend/BiomesOPlenty#787]
I have map that worked just fine last night, but when I try to load it today the game crashes. Biomes o' Plenty should be theonly mod. It is for 1.9. I tried updating Forge, but it didn't help. The crash report was:
--- Minecraft Crash Report ----
// Sorry :(

Time: 6/8/16 4:55 PM
Description: Ticking player

java.lang.NullPointerException: Ticking player
	at net.minecraft.world.World.func_180495_p(World.java:828)
	at net.minecraft.block.BlockChest.func_185496_a(BlockChest.java:68)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185900_c(BlockStateContainer.java:422)
	at net.minecraft.block.Block.func_180646_a(Block.java:346)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185890_d(BlockStateContainer.java:412)
	at net.minecraft.block.Block.func_185477_a(Block.java:328)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185908_a(BlockStateContainer.java:417)
	at net.minecraft.world.World.func_184144_a(World.java:1239)
	at net.minecraft.entity.Entity.func_70091_d(Entity.java:633)
	at net.minecraft.entity.EntityLivingBase.func_70612_e(EntityLivingBase.java:1751)
	at net.minecraft.entity.player.EntityPlayer.func_70612_e(EntityPlayer.java:1782)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2165)
	at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:499)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1961)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:226)
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:301)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:163)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:193)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:286)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:728)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:609)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:148)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:467)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.world.World.func_180495_p(World.java:828)
	at net.minecraft.block.BlockChest.func_185496_a(BlockChest.java:68)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185900_c(BlockStateContainer.java:422)
	at net.minecraft.block.Block.func_180646_a(Block.java:346)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185890_d(BlockStateContainer.java:412)
	at net.minecraft.block.Block.func_185477_a(Block.java:328)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185908_a(BlockStateContainer.java:417)
	at net.minecraft.world.World.func_184144_a(World.java:1239)
	at net.minecraft.entity.Entity.func_70091_d(Entity.java:633)
	at net.minecraft.entity.EntityLivingBase.func_70612_e(EntityLivingBase.java:1751)
	at net.minecraft.entity.player.EntityPlayer.func_70612_e(EntityPlayer.java:1782)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2165)
	at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:499)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1961)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:226)

-- Player being ticked --
Details:
	Entity Type: null (net.minecraft.entity.player.EntityPlayerMP)
	Entity ID: 48
	Entity Name: darkorinth
	Entity's Exact location: 1033.61, 196.00, -273.28
	Entity's Block location: World: (1033,196,-274), Chunk: (at 9,12,14 in 64,-18; contains blocks 1024,0,-288 to 1039,255,-273), Region: (2,-1; contains chunks 64,-32 to 95,-1, blocks 1024,0,-512 to 1535,255,-1)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:301)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:163)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:193)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:286)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@1e69caf7
Stacktrace:
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:728)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:609)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:148)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:467)
	at java.lang.Thread.run(Thread.java:745)

What do I do?

**Comment by GirafiStudios** [comment]
Could you please provide the full crash report on something like Pastebin ? :) Or inform what versions of Forge and Biomes O' Plenty you're using.
When that is said, this does not look like a BoP issue.

**Comment by Darkorinth** [comment]
I figured out what the problem was. The latest version of Forge did not install properly. I had to download a different installer and get the 1.94 BOP then it worked. Thank you for trying to help.

**Comment by GirafiStudios** [comment]
No problem :) Please close the issue, now that it's resolved!

**Comment by Darkorinth** [comment]
I'm new thiss, I will now. Thank you aggain
