### ISSUE TITLE
1.9.4 version crashing

### ISSUE THREAD

**Issue by RobotoMochacho** [Glitchfiend/BiomesOPlenty#791]
I am building a 1.9.4 modpack and want biomes o plenty in it but it crashes on start up here is the crash report.

---- Minecraft Crash Report ----
// Oops.

Time: 6/16/16 9:04 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: java.lang.IllegalAccessError: tried to access method net.minecraftforge.common.util.EnumHelper.addEnum([[Ljava/lang/Class;Ljava/lang/Class;Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/Enum; from class biomesoplenty.common.init.ModItems
	at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:179)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:589)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:249)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:437)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.IllegalAccessError: tried to access method net.minecraftforge.common.util.EnumHelper.addEnum([[Ljava/lang/Class;Ljava/lang/Class;Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/Enum; from class biomesoplenty.common.init.ModItems
	at biomesoplenty.common.init.ModItems.addArmorMaterial(ModItems.java:321)
	at biomesoplenty.common.init.ModItems.registerItems(ModItems.java:211)
	at biomesoplenty.common.init.ModItems.init(ModItems.java:149)
	at biomesoplenty.core.BiomesOPlenty.preInit(BiomesOPlenty.java:72)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:566)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:228)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:206)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:586)
	... 10 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.9.4
	Operating System: Mac OS X (x86_64) version 10.11.1
	Java Version: 1.8.0_91, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 152428328 bytes (145 MB) / 347226112 bytes (331 MB) up to 3207856128 bytes (3059 MB)
	JVM Flags: 5 total; -Xmx3G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.28 Powered by Forge 12.17.0.1962 4 mods loaded, 4 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.9.4-12.17.0.1962.jar) 
	UCH	Forge{12.17.0.1962} [Minecraft Forge] (forge-1.9.4-12.17.0.1962.jar) 
	UCE	BiomesOPlenty{4.1.0.2021} [Biomes O' Plenty] (BiomesOPlenty-1.9.4-4.1.0.2021-universal (1).jar) 
	Loaded coremods (and transformers): 

please help

**Comment by GirafiStudios** [comment]
In the future, please check if your problem have already been reported, which it already have a couple of times in this case. You just simply have to update Biomes O Plenty, you're using an old version.

**Comment by RobotoMochacho** [comment]
sorry, I though I was using the newest. I'll make sure to read through other threads before. Thank you
