### ISSUE TITLE
Lowercase mod id

### ISSUE THREAD

**Issue by Nentify** [Glitchfiend/BiomesOPlenty#819]
```
[08:03:35] [Server thread/WARN] [FML]: ****************************************
[08:03:35] [Server thread/WARN] [FML]: * The modid BiomesOPlenty is not the same as it's lowercase version. Lowercasing will be enforced in 1.11
[08:03:35] [Server thread/WARN] [FML]: *  at net.minecraftforge.fml.common.FMLModContainer.sanityCheckModId(FMLModContainer.java:139)
[08:03:35] [Server thread/WARN] [FML]: *  at net.minecraftforge.fml.common.FMLModContainer.<init>(FMLModContainer.java:124)
[08:03:35] [Server thread/WARN] [FML]: *  at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[08:03:35] [Server thread/WARN] [FML]: *  at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[08:03:35] [Server thread/WARN] [FML]: *  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[08:03:35] [Server thread/WARN] [FML]: *  at java.lang.reflect.Constructor.newInstance(Constructor.java:423)...
[08:03:35] [Server thread/WARN] [FML]: ****************************************
```

**Comment by Adubbz** [comment]
Added in 1.11
