### ISSUE TITLE
[1.10.2] Exception in server tick loop in World gen following BOP soil/grass disabling

### ISSUE THREAD

**Issue by MrNinja93** [Glitchfiend/BiomesOPlenty#857]
> Time: 9/6/16 8:02 AM

Description: Exception in server tick loop 

>java.lang.RuntimeException: A generator with name grass_splatter_new already exists!
	at biomesoplenty.common.world.GenerationManager.addGenerator(GenerationManager.java:31)
	at biomesoplenty.common.biome.overworld.BOPBiome.addGenerator(BOPBiome.java:268)
	at biomesoplenty.common.biome.overworld.BiomeGenQuagmire.applySettings(BiomeGenQuagmire.java:131)
	at biomesoplenty.common.world.BiomeProviderBOP.<init>(BiomeProviderBOP.java:74)
	at biomesoplenty.common.world.BiomeProviderBOP.<init>(BiomeProviderBOP.java:87)
	at biomesoplenty.common.world.WorldTypeBOP.getBiomeProvider(WorldTypeBOP.java:33)
	at net.minecraft.world.WorldProvider.func_76572_b(WorldProvider.java:56)
	at net.minecraft.world.WorldProvider.func_76558_a(WorldProvider.java:39)
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:113)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:85)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:120)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431)
	at java.lang.Thread.run(Thread.java:745)

----

#### Issue Description:
Crash on worldgen/entering worlds (sporadic) 

Disabling bop soils/grass seems to cause it (never noticed it prior to doing so)

Disabling outback seems to fix it (or at least lets worlds that would crash before generating to generate and load)   hard to tell if proper fix or luck.

Also FYI disabling grass/soils due to https://github.com/Glitchfiend/BiomesOPlenty/issues/807
https://github.com/SleepyTrousers/EnderIO/issues/3501

#### Steps to reproduce:

1. Create new world custom settings disabling BOP soils and grass

#### Additional Information:
[crash-2016-09-06_09.37.35-server.txt](https://github.com/Glitchfiend/BiomesOPlenty/files/456276/crash-2016-09-06_09.37.35-server.txt)

____
#### Affected Versions (Exact numbers, do *not* use "latest"):

- Biomes O' Plenty: 1.10.2-5.0.0.2081
- Minecraft: 1.10.2
- Forge: 12.18.1.2076

No other mods

**Comment by MrNinja93** [comment]
Appears to be same as reported at  https://github.com/Glitchfiend/BiomesOPlenty/issues/745 back in 1.9.4 and labelled fixed/closed.

**Comment by Forstride** [comment]
I just pushed a fix for it.  I only tested it a little bit, but like you said, it's sporadic, so I'm not sure if it actually fixed it or not.  New build should be up shortly.

**Comment by GirafiStudios** [comment]
@MrNinja93 does this still happen with latest version of BoP? :)
