### ISSUE TITLE
Crash with GregTech

### ISSUE THREAD

**Issue by GordonHollow** [Glitchfiend/BiomesOPlenty#897]
#### Issue Description:
Game crashes with BOP and GregTech both installed, when i pick up any gregore. crashreport says this cause ahievement code such us https://github.com/Glitchfiend/BiomesOPlenty/issues/786
Without BOP it's not crashed.

Turn off BOP-achievements will fix it, but i not found this function in config

#### Steps to reproduce:

1. Install latest BOP and GregTechUnofficial on Minecraft 1.10.2
2. Mine and pick up in inventory any gregore
3. When it's picked up - game crashes

#### Additional Information:

PM
Description: Ticking player

java.lang.IllegalArgumentException: Cannot set property PropertyInteger{name=metadata, clazz=class java.lang.Integer, values=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]} to 535 on block gregtech:gt.blockores, it is not an allowed value
	at net.minecraftforge.common.property.ExtendedBlockState$ExtendedStateImplementation.func_177226_a(ExtendedBlockState.java:100)
	at gregtech.api.items.GT_Generic_Block.func_176203_a(GT_Generic_Block.java:49)
	**at biomesoplenty.common.handler.AchievementEventHandler.onItemPickup(AchievementEventHandler.java:58)**
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_189_AchievementEventHandler_onItemPickup_ItemPickupEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.fml.common.FMLCommonHandler.firePlayerItemPickupEvent(FMLCommonHandler.java:580)
	at net.minecraft.entity.item.EntityItem.func_70100_b_(EntityItem.java:410)
	at net.minecraft.entity.player.EntityPlayer.func_71044_o(EntityPlayer.java:578)
	at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:570)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2013)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:233)
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:303)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:162)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:213)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:732)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Unknown Source)

____
#### Affected Versions (Exact numbers, do *not* use "latest"):

- Biomes O' Plenty: BiomesOPlenty-1.10.2-5.0.0.2094-universal
- Minecraft: 1.10.2
- GregtechUnofficial: gregtech-5.10.06
- Forge: forge-1.10.2-12.18.2.2122 (also try 2099, nothing changes)

**Comment by GordonHollow** [comment]
Nope, it's not work. Same crash again.

**Comment by GordonHollow** [comment]
https://github.com/Blood-Asp/GT5-Unofficial/issues/756

GregTech developers say this - it isn't GT issue, it's BoP issue and has the same issue in AbyssalCraft

**Comment by Adubbz** [comment]
I admit I did make an oversight in my previous change, and I do apologise for that, it has now been addressed. If the problem still persists, I eagerly await an explanation from the GregTech developers.

**Comment by GordonHollow** [comment]
Great! Now all works =)

**Comment by Dragon2488** [comment]
Cool. My congrats.
