### ISSUE TITLE
[1.10.2] Server thread crash placing EnderIO Farming Station in BoP biomes

### ISSUE THREAD

**Issue by ouTPhaze** [Glitchfiend/BiomesOPlenty#909]
#### Issue Description:

This has been posted before, but the issue was closed without a resolution.

When you have Ender IO, BoP and a mod that adds plants (like Immersive Engineering or Extra Utilities), server crashes when checking for places to place plants while in BoP biomes.

#### Steps to reproduce:

1. Go to a biome with special dirt (like a Marsh or similar)
2. Place farm
3. Run machine (might need to use a mod plant aswell, in my test I was using Immersive Engineering's Industrial Hemp)

#### Additional Information:

- fml-client-latest.log or fml-server-latest.log:
---- Minecraft Crash Report ----

WARNING: coremods are present:
  BiomeTweakerCore (BiomeTweaker-1.10.2-2.1.229.jar)
  LoadingPlugin (Quark-r1.0-59.jar)
  ChiselCorePlugin (Chisel-MC1.10.2-0.0.7.3.jar)
  BookshelfLoadingPlugin (Bookshelf-1.10.2-1.4.2.331.jar)
  LoadingPlugin (ResourceLoader-MC1.9.4-1.5.1.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.60-beta.jar)
  CoreMod (Aroma1997Core-1.9.4-1.1.1.0.jar)
  LoadingHook (Mekanism-1.10.2-9.2.0.292.jar)
  AppEngCore (appliedenergistics2-rv4-alpha-6.jar)
  SFRCore (SolarFluxReborn_1.10.2-1.4r.jar)
  IC2core (industrialcraft-2-2.6.87-ex110.jar)
  LoadingPlugin (RandomThings-MC1.10.2-3.7.6.jar)
  Default Options (DefaultOptions_1.10.2-6.1.5.jar)
  ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.2.jar)
  DepLoader (BrandonsCore-1.10.2-2.1.1.60-universal.jar)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
  TransformerLoader (OpenComputers-MC1.10.2-1.6.0.3-rc.1.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.4.3.124-universal.jar)
Contact their authors BEFORE contacting forge

// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 11/21/16 12:00 PM
Description: Ticking block entity

java.lang.ArrayIndexOutOfBoundsException: 8
	at biomesoplenty.common.block.BlockBOPGrass.canSustainPlantType(BlockBOPGrass.java:135)
	at biomesoplenty.common.block.BlockBOPGrass.canSustainPlant(BlockBOPGrass.java:163)
	at crazypants.enderio.machine.farm.farmers.CustomSeedFarmer.canPlant(CustomSeedFarmer.java:232)
	at crazypants.enderio.machine.farm.farmers.CustomSeedFarmer.plantFromInventory(CustomSeedFarmer.java:141)
	at crazypants.enderio.machine.farm.farmers.CustomSeedFarmer.prepareBlock(CustomSeedFarmer.java:128)
	at crazypants.enderio.machine.farm.farmers.FarmersCommune.prepareBlock(FarmersCommune.java:60)
	at crazypants.enderio.machine.farm.TileFarmStation.doTick(TileFarmStation.java:486)
	at crazypants.enderio.machine.farm.TileFarmStation.checkProgress(TileFarmStation.java:438)
	at crazypants.enderio.machine.AbstractPoweredTaskEntity.processTasks(AbstractPoweredTaskEntity.java:114)
	at crazypants.enderio.machine.AbstractMachineEntity.doUpdate(AbstractMachineEntity.java:290)
	at crazypants.enderio.machine.AbstractPoweredMachineEntity.doUpdate(AbstractPoweredMachineEntity.java:73)
	at crazypants.enderio.machine.farm.TileFarmStation.doUpdate(TileFarmStation.java:423)
	at com.enderio.core.common.TileEntityBase.func_73660_a(TileEntityBase.java:36)
	at net.minecraft.world.World.func_72939_s(World.java:1804)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:619)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at biomesoplenty.common.block.BlockBOPGrass.canSustainPlantType(BlockBOPGrass.java:135)
	at biomesoplenty.common.block.BlockBOPGrass.canSustainPlant(BlockBOPGrass.java:163)
	at crazypants.enderio.machine.farm.farmers.CustomSeedFarmer.canPlant(CustomSeedFarmer.java:232)
	at crazypants.enderio.machine.farm.farmers.CustomSeedFarmer.plantFromInventory(CustomSeedFarmer.java:141)
	at crazypants.enderio.machine.farm.farmers.CustomSeedFarmer.prepareBlock(CustomSeedFarmer.java:128)
	at crazypants.enderio.machine.farm.farmers.FarmersCommune.prepareBlock(FarmersCommune.java:60)
	at crazypants.enderio.machine.farm.TileFarmStation.doTick(TileFarmStation.java:486)
	at crazypants.enderio.machine.farm.TileFarmStation.checkProgress(TileFarmStation.java:438)
	at crazypants.enderio.machine.AbstractPoweredTaskEntity.processTasks(AbstractPoweredTaskEntity.java:114)
	at crazypants.enderio.machine.AbstractMachineEntity.doUpdate(AbstractMachineEntity.java:290)
	at crazypants.enderio.machine.AbstractPoweredMachineEntity.doUpdate(AbstractPoweredMachineEntity.java:73)
	at crazypants.enderio.machine.farm.TileFarmStation.doUpdate(TileFarmStation.java:423)
	at com.enderio.core.common.TileEntityBase.func_73660_a(TileEntityBase.java:36)

-- Block entity being ticked --
Details:
	Name: blockFarmStationTileEntity // crazypants.enderio.machine.farm.TileFarmStation
	Block type: ID #2007 (tile.blockFarmStation // crazypants.enderio.machine.farm.BlockFarmStation)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-994,81,-1098), Chunk: (at 14,5,6 in -63,-69; contains blocks -1008,0,-1104 to -993,255,-1089), Region: (-2,-3; contains chunks -64,-96 to -33,-65, blocks -1024,0,-1536 to -513,255,-1025)
	Actual block type: ID #2007 (tile.blockFarmStation // crazypants.enderio.machine.farm.BlockFarmStation)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1804)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:619)

____
#### Affected Versions (Exact numbers, do *not* use "latest"):

- Biomes O' Plenty: 5.0.0.2091
- Minecraft: 1.10.2
- Forge:12.18.2.2122

**Comment by GirafiStudios** [comment]
This was fixed in BoP version 5.0.0.2092. Another time please make sure you have the latest version of BoP before reporting.
